export const INDEXABLE_STATIC_PATHS = [
  "/",
  "/explore",
  "/explore/trip-planner",
  "/explore/attractions-comparison",
  "/explore/painted-churches",
  "/explore/painted-churches-plan",
  "/explore/painted-churches/map",
  "/explore/painted-churches/compare",
  "/explore/painted-churches/how-many",
  "/explore/painted-churches/methodology",
  "/explore/painted-churches/census",
  "/explore/painted-churches/techniques",
  "/explore/painted-churches/symbols",
  "/explore/painted-churches/people",
  "/explore/painted-churches/heritage",
  "/explore/painted-churches/preservation",
  "/explore/painted-churches/knowledge-graph",
  "/explore/painted-churches/harwood-archive",
  "/explore/painted-churches/how-to-read",
  "/explore/painted-churches/glossary",
  "/explore/painted-churches/timeline",
  "/explore/painted-churches/routes",
  "/explore/painted-churches/guides",
  "/explore/painted-churches/print-guide",
  "/explore/painted-churches/media",
  "/explore/painted-churches/cite",
  "/explore/painted-churches/then-and-now",
  "/explore/top-attractions",
  "/explore/top-attractions/methodology",
  "/explore/top-attractions/road-trips",
  "/fishing",
  "/fishing/lakes",
  "/fishing/plan",
  "/fishing/compare",
  "/fishing/seasons",
  "/fishing/techniques",
  "/fishing/techniques/soft-plastics",
  "/fishing/techniques/crankbaits",
  "/fishing/techniques/spinnerbaits",
  "/fishing/techniques/topwater",
  "/fishing/techniques/trolling",
  "/fishing/techniques/vertical-jigging",
  "/fishing/techniques/jigs-and-minnows",
  "/fishing/techniques/live-bait",
  "/fishing/techniques/cut-bait",
  "/fishing/regulations",
  "/fishing/species",
  "/fishing/species/largemouth-bass",
  "/fishing/guides",
  "/fishing/reports",
  "/fishing/access",
  "/fishing/services",
  "/sports",
  "/sports-venues",
  "/sports-venues/compare",
  "/sports-venues/dallas-fort-worth",
  "/sports-venues/houston",
  "/sports-venues/austin-central-texas",
  "/sports-venues/san-antonio",
  "/sports-venues/waco",
  "/sports-venues/college-station",
  "/sports-venues/el-paso",
  "/sports-venues/lubbock",
  "/sports-venues/football",
  "/sports-venues/baseball",
  "/sports-venues/basketball",
  "/sports-venues/motorsports",
  "/sports-venues/college-sports",
  "/sports-venues/high-school-football",
  "/sports-venues/rodeo-western",
  "/sports-venues/golf",
  "/sports-venues/soccer",
  "/sports-venue/jones-att-stadium",
  "/events",
  "/texas-history",
  "/texas-symbols",
  "/texas-facts",
  "/things-unique-to-texas",
  "/things-unique-to-texas/methodology",
  "/things-unique-to-texas/food-drink",
  "/things-unique-to-texas/texas-brands",
  "/things-unique-to-texas/natural-wonders",
  "/things-unique-to-texas/landmarks",
  "/things-unique-to-texas/roadside-small-towns",
  "/things-unique-to-texas/culture-music",
  "/things-unique-to-texas/wildlife-landscape",
  "/things-unique-to-texas/slang-folklore",
  "/texas-food-history",
  "/texas-food-trail",
  "/texas-roadside-oddities",
  "/texas-slang-explained",
  "/texas-dance-halls-honky-tonks",
  "/texas-homecoming-mums",
  "/texas-natural-wonders-bucket-list",
  "/german-czech-texas-towns",
  "/texas-brand-origin-stories",
  "/made-in-texas",
  "/texas-chili-con-carne-history",
  "/texas-chicken-fried-steak-guide",
  "/texas-breakfast-taco-guide",
  "/barbacoa-big-red-san-antonio",
  "/san-antonio-puffy-taco-history",
  "/dr-pepper-texas-history",
  "/texas-ranch-water-guide",
  "/moving-to-texas",
  "/moving-to-texas-checklist",
  "/home-garden",
  "/real-estate",
  "/property",
  "/guides",
  "/texas-living",
  "/texas-resources",
  "/texas-explained",
  "/texas-data",
  "/texas-data/city-county-relationships",
  "/county",
  "/property-tax-guides",
  "/property-tax-calculators",
  "/property-tax/counties",
  "/learn/property-taxes",
  "/learn/property-tax-payments",
  "/learn/appraisal-districts",
  "/learn/agricultural-valuation",
  "/learn/wildlife-management-valuation",
  "/learn/disabled-veteran-property-tax-benefits",
  "/learn/over-65-property-tax-guide",
  "/learn/mud-taxes-explained",
  "/learn/property-tax-deadlines",
  "/learn/property-tax-appeals-arbitration",
  "/learn/homebuyer-property-tax-checklist",
  "/decide/property-taxes",
  "/decide/financial-tools",
  "/do/homestead-exemption",
  "/do/property-tax-protest",
  "/browse/counties",
  "/browse/cities",
  "/find-my-dmv",
  "/find-my-school-district",
  "/shop",
  "/about",
  "/partner-with-us",
  "/citation-guide",
  "/texas-agricultural-valuation-calculator",
  "/texas-budget-planner",
  "/texas-closing-cost-calculator",
  "/texas-cost-of-living-calculator",
  "/texas-disabled-veteran-property-tax-calculator",
  "/texas-down-payment-assistance-calculator",
  "/texas-down-payment-calculator",
  "/texas-first-time-homebuyer-programs",
  "/texas-home-affordability-calculator",
  "/texas-home-equity-calculator",
  "/texas-home-equity-growth-calculator",
  "/texas-home-insurance-calculator",
  "/texas-homeownership-cost-calculator",
  "/texas-homestead-savings-calculator",
  "/texas-mortgage-calculator",
  "/texas-mortgage-payoff-calculator",
  "/texas-moving-cost-calculator",
  "/texas-over-65-property-tax-calculator",
  "/texas-property-tax-county-comparison-calculator",
  "/texas-property-tax-escrow-calculator",
  "/texas-property-tax-protest-savings-calculator",
  "/texas-refinance-savings-calculator",
  "/texas-rent-vs-buy-calculator",
  "/texas-salary-calculator",
  "/texas-salary-comparison-by-city",
  "/texas-sales-tax-explained",
  "/texas-utility-cost-calculator",
] as const;

export const CONDITIONAL_INDEXABLE_PUBLIC_PATHS = [
  "/news",
  "/texas-data/county-growth",
  "/texas-data/county-housing-costs",
] as const;

export const REDIRECT_ONLY_PATHS = [
  "/tools",
  "/mortgage-calculator",
  "/calculators/texas-home-affordability",
  "/calculators/texas-property-tax",
  "/tax-calculator",
  "/texas-financial-tools",
  "/texas-property-tax-increase-calculator",
  "/texas-property-tax-protest-guide",
  "/fishing/lake/lake-conroe",
  "/lakes/lake-conroe.html",
  "/destination/enchanted-rock",
  "/destination/palo-duro-canyon",
  "/explore/texas-state-parks-guide",
  "/explore/texas-lakes-guide",
  "/explore/texas-camping-guide",
  "/explore/texas-scenic-drives",
  "/explore/texas-wildflower-seasons",
  "/explore/national-wildlife-refuges",
  "/explore/wildlife-management-areas",
  "/explore/lighthouses",
  "/explore/spring-fed-swimming",
  "/explore/hill-country-springs",
  "/explore/spring-conservation-and-education",
] as const;

export const NON_INDEXABLE_PUBLIC_PATHS = [
  "/search",
  "/explore/search",
  "/fishing/guides/submit",
  "/fishing/reports/submit",
  "/shop/cart",
  "/shop/checkout-return",
  "/sports-venues/compare.csv",
  "/top-25-texas-attractions.csv",
  "/top-25-texas-attractions.json",
  "/things-that-define-texas.csv",
  "/things-that-define-texas.json",
  "/painted-churches.csv",
  "/painted-churches.json",
  "/painted-churches-checklist.txt",
  "/texas-data/county-growth.csv",
  "/texas-data/county-housing-costs.csv",
  "/texas-data/city-county-relationships.csv",
] as const;

const NON_INDEXABLE_PREFIXES = ["/admin", "/api/"] as const;

export function normalizePublicPath(path: string) {
  const value = path.trim();
  if (!value || !value.startsWith("/") || value.startsWith("//")) return null;
  if (value.includes("?") || value.includes("#") || /[\u0000-\u001F\u007F]/.test(value)) return null;
  if (value === "/") return value;
  return value.replace(/\/{2,}/g, "/").replace(/\/+$/, "");
}

export function isExploreSitemapOwnedPath(path: string) {
  const normalized = normalizePublicPath(path);
  if (!normalized) return false;
  return normalized === "/explore"
    || normalized.startsWith("/explore/")
    || normalized.startsWith("/destination/");
}

export function isIndexablePublicPath(path: string) {
  const normalized = normalizePublicPath(path);
  if (!normalized) return false;
  return !NON_INDEXABLE_PREFIXES.some((prefix) => normalized === prefix.replace(/\/$/, "") || normalized.startsWith(prefix))
    && !(REDIRECT_ONLY_PATHS as readonly string[]).includes(normalized)
    && !(NON_INDEXABLE_PUBLIC_PATHS as readonly string[]).includes(normalized);
}
