import { createFileRoute, Link } from '@tanstack/react-router';
import { Container } from '@/components/layout/Container';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { buildMeta, canonicalLink } from '@/lib/seo';

const description = 'Use official Texas education and local district resources to identify the public school district serving an address.';
export const Route = createFileRoute('/find-my-school-district')({ head: () => ({ meta: buildMeta(texasDefinedBrand, {
      canonicalPath: '/find-my-school-district',
      title: 'Find My Texas School District', description }),
    links: [canonicalLink(texasDefinedBrand, '/find-my-school-district')] }), component: Page });
function Page() { return <Container className="py-16 sm:py-24"><article className="prose prose-gray mx-auto max-w-4xl"><p className="eyebrow text-primary">Schools and communities</p><h1>Find My Texas School District</h1><p className="lead">{description}</p><h2>Why the mailing address is not enough</h2><p>City names, ZIP codes, school-district boundaries, attendance zones, and county lines do not always match. Verify the exact property with official mapping and the district before relying on a listing or informal map.</p><h2>Recommended process</h2><ol><li>Open the Texas Education Agency school and district tools.</li><li>Use the exact property address in an official district or county mapping tool.</li><li>Confirm the assigned campus directly with the district.</li><li>Ask whether boundary changes, transfer rules, or new-campus assignments are pending.</li><li>For a purchase or lease, retain the district’s written confirmation.</li></ol><div className="not-prose my-8 grid gap-4 sm:grid-cols-2"><a className="rounded-lg border p-5 font-medium" href="https://tea.texas.gov/texas-schools" rel="noreferrer">Texas Education Agency school resources</a><a className="rounded-lg border p-5 font-medium" href="https://txschools.gov/" rel="noreferrer">TXschools.gov</a><Link className="rounded-lg border p-5 font-medium" to="/browse/cities">Browse Texas cities</Link><Link className="rounded-lg border p-5 font-medium" to="/browse/counties">Browse Texas counties</Link></div><aside className="not-prose rounded-lg bg-muted p-5 text-sm text-muted-foreground">TexasDefined does not store the entered address or claim a boundary match. The district is the final source for campus assignment.</aside></article></Container>; }
