import { createFileRoute, Link } from '@tanstack/react-router';
import { Container } from '@/components/layout/Container';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { buildMeta, canonicalLink } from '@/lib/seo';

const description = 'New-resident vehicle-registration steps, official Texas agency links, and county tax-office resources without storing an address.';
export const Route = createFileRoute('/find-my-dmv')({ head: () => ({ meta: buildMeta(texasDefinedBrand, {
      canonicalPath: '/find-my-dmv',
      title: 'Register a Vehicle in Texas', description }),
    links: [canonicalLink(texasDefinedBrand, '/find-my-dmv')] }), component: Page });
function Page() { return <Container className="py-16 sm:py-24"><article className="prose prose-gray mx-auto max-w-4xl"><p className="eyebrow text-primary">Vehicles and identification</p><h1>Register a Vehicle in Texas</h1><p className="lead">{description}</p><h2>Use the right office</h2><p>Texas vehicle registration is generally handled through the county tax assessor-collector, while driver licenses are handled through the Texas Department of Public Safety. Confirm requirements and appointments on the official sites before visiting.</p><h2>New-resident checklist</h2><ol><li>Arrange Texas-compliant insurance.</li><li>Complete any inspection or emissions step that applies to the vehicle and county.</li><li>Gather title, registration, identification, ownership, and residency documents.</li><li>Open the official county tax-office page and verify fees and accepted payment methods.</li><li>Handle the Texas driver-license process separately through DPS.</li></ol><div className="not-prose my-8 grid gap-4 sm:grid-cols-2"><a className="rounded-lg border p-5 font-medium" href="https://www.txdmv.gov/motorists/new-to-texas" rel="noreferrer">TxDMV new-to-Texas guidance</a><a className="rounded-lg border p-5 font-medium" href="https://www.dps.texas.gov/section/driver-license" rel="noreferrer">Texas DPS driver-license services</a><Link className="rounded-lg border p-5 font-medium" to="/browse/counties">Find your county directory</Link><Link className="rounded-lg border p-5 font-medium" to="/moving-to-texas-checklist">Moving checklist</Link></div><aside className="not-prose rounded-lg bg-muted p-5 text-sm text-muted-foreground">This page does not collect or store an address. Use the official county and state tools for the current office, fees, deadlines, and document requirements.</aside></article></Container>; }
