import { createFileRoute, Link } from "@tanstack/react-router";

import { texasDefinedBrand } from "@/brand/texasdefined";
import { Container } from "@/components/layout/Container";
import { fishingFoundationAnchor, isCompleteFishingLakeSlug } from "@/data/fishing/slugs";
import { buildMeta, canonicalLink } from "@/lib/seo";

export const Route = createFileRoute("/fishing")({
  loader: async ({ context }) => {
    const { fishSpeciesQuery, fishingLakesQuery, lakeSpeciesProfilesQuery } = await import("@/data/fishing/queries");
    const [lakes, species, lakeSpecies] = await Promise.all([
      context.queryClient.ensureQueryData(fishingLakesQuery({ featured: true, limit: 12 })),
      context.queryClient.ensureQueryData(fishSpeciesQuery({ limit: 50 })),
      context.queryClient.ensureQueryData(lakeSpeciesProfilesQuery()),
    ]);
    return { lakes, species, lakeSpecies };
  },
  head: () => ({ meta: buildMeta(texasDefinedBrand, { title: "Texas Fishing Guide — Lakes, Fish Species & Local Fishing", description: "Explore Texas fishing lake by lake, with verified lake facts, target species, seasonal patterns, access, reports and verified local guide infrastructure.", canonicalPath: "/fishing" }), links: [canonicalLink(texasDefinedBrand, "/fishing")] }),
  component: FishingPage,
});

function FishingPage() {
  const { lakes, species, lakeSpecies } = Route.useLoaderData();
  const speciesById = new Map(species.map((row) => [row.id, row]));
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/" className="hover:text-foreground">Front page</Link></li><li aria-hidden>·</li><li aria-current="page">Fishing</li></ol></nav></Container>
    <section className="mt-5 border-b border-border bg-ink text-ink-foreground"><Container className="py-16 sm:py-24"><p className="eyebrow text-ink-foreground/70">Texas Defined Fishing</p><h1 className="mt-4 max-w-4xl font-display text-5xl leading-[0.96] sm:text-7xl">Fishing Texas, lake by lake.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/82">A statewide fishing guide built around the water itself: what lives there, how anglers target it, how seasons change the approach, and the local access, guides and businesses that make a trip easier.</p><div className="mt-8 flex flex-wrap gap-5 text-sm"><Link to="/fishing/lakes/lake-conroe" className="border-b border-ink-foreground pb-1 font-semibold text-ink-foreground">Lake Conroe →</Link><Link to="/fishing/species" className="border-b border-ink-foreground/50 pb-1 text-ink-foreground/75">Browse fish species →</Link></div></Container></section>
    <Container className="py-14 sm:py-20">
      <section aria-labelledby="showcase-lakes"><div className="max-w-3xl"><p className="eyebrow text-primary">Showcase lakes</p><h2 id="showcase-lakes" className="mt-3 font-display text-4xl sm:text-5xl">Five complete lake guides now define the statewide template.</h2><p className="mt-4 text-base leading-7 text-muted-foreground">Lake Conroe, Lake Fork, Sam Rayburn Reservoir, Lake Livingston and Lake Texoma each have a full fishing-first destination with fish, access, boating, regulations, camping, nearby trip planning, reports and verified-guide infrastructure.</p></div>
      <div className="mt-9 grid gap-x-8 border-t border-border lg:grid-cols-2">{lakes.map((lake) => { const relationships = lakeSpecies.filter((relation) => relation.lakeId === lake.id); const targets = relationships.map((relation) => ({ relation, species: speciesById.get(relation.speciesId) })).filter((row) => Boolean(row.species)).slice(0, 6); const hasCompleteGuide = isCompleteFishingLakeSlug(lake.slug); return <article id={`lake-${lake.slug}`} key={lake.id} className="scroll-mt-28 border-b border-border py-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-primary">{lake.region.replaceAll("-", " ")}</p><h3 className="mt-2 font-display text-3xl">{hasCompleteGuide ? <a href={fishingFoundationAnchor("lake", lake.slug)} className="hover:text-primary">{lake.name}</a> : lake.name}</h3></div>{lake.surfaceAcres && <p className="text-sm text-muted-foreground">{lake.surfaceAcres.toLocaleString("en-US")} acres</p>}</div><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{lake.summary}</p><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2">{lake.maxDepthFeet && <div><dt className="eyebrow text-muted-foreground">Maximum depth</dt><dd className="mt-1">{lake.maxDepthFeet} ft</dd></div>}{lake.primaryWaterway && <div><dt className="eyebrow text-muted-foreground">Waterway</dt><dd className="mt-1">{lake.primaryWaterway}</dd></div>}{lake.counties.length > 0 && <div><dt className="eyebrow text-muted-foreground">Counties</dt><dd className="mt-1">{lake.counties.join(", ")}</dd></div>}{lake.controllingAuthorities.length > 0 && <div><dt className="eyebrow text-muted-foreground">Controlling authority</dt><dd className="mt-1">{lake.controllingAuthorities.join(", ")}</dd></div>}</dl>{targets.length > 0 && <div className="mt-6"><p className="eyebrow text-muted-foreground">Fishing targets</p><ul className="mt-3 flex flex-wrap gap-2">{targets.map(({ relation, species: target }) => <li key={relation.id} className="border border-border px-3 py-1.5 text-xs">{target?.commonName} · {relation.quality}</li>)}</ul></div>}{hasCompleteGuide && <a href={fishingFoundationAnchor("lake", lake.slug)} className="eyebrow mt-6 inline-block border-b border-primary pb-1 text-primary">Complete fishing guide →</a>}</article>; })}</div></section>
      <section aria-labelledby="species-heading" className="mt-16 border-t border-border pt-10"><p className="eyebrow text-primary">Fish the state by species</p><h2 id="species-heading" className="mt-3 font-display text-4xl">One species can connect dozens of Texas lakes.</h2><p className="mt-4 max-w-3xl text-base leading-7 text-muted-foreground">Species records are independent from lake records, so statewide bass, crappie, catfish and striped-bass guidance can connect back to every complete lake destination without duplicating lake facts.</p><Link to="/fishing/species" className="mt-5 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Browse the statewide fish-species directory →</Link><div className="mt-8 grid border-t border-border sm:grid-cols-2 lg:grid-cols-3">{species.map((row) => <article id={`species-${row.slug}`} key={row.id} className="scroll-mt-28 border-b border-border py-6 sm:px-5 sm:first:pl-0"><p className="eyebrow text-primary">{row.taxonKind === "group" ? "Fishing group" : "Fish species"}</p><h3 className="mt-2 font-display text-2xl"><a href={fishingFoundationAnchor("species", row.slug)} className="hover:text-primary">{row.commonName}</a></h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{row.summary}</p></article>)}</div></section>
      <section className="mt-16 border-t border-border pt-10"><p className="eyebrow text-primary">Built for local depth</p><h2 className="mt-3 font-display text-4xl">Reports, guides and lake-area businesses can now attach to every showcase lake.</h2><div className="mt-7 grid gap-6 text-sm leading-7 text-muted-foreground sm:grid-cols-2 lg:grid-cols-4"><div><h3 className="font-display text-xl text-foreground">Local guides</h3><p className="mt-2">Only verified profiles publish, and a guide can connect to every lake and species actually served.</p></div><div><h3 className="font-display text-xl text-foreground">Fishing reports</h3><p className="mt-2">Dated reports remain separate from evergreen seasonal patterns so old bite claims do not masquerade as current.</p></div><div><h3 className="font-display text-xl text-foreground">Access & services</h3><p className="mt-2">Ramps, marinas, tackle, lodging and other services attach to lake geography instead of generic directories.</p></div><div><h3 className="font-display text-xl text-foreground">Local sponsorships</h3><p className="mt-2">Paid placements are explicitly labeled and never alter fish ratings or editorial lake recommendations.</p></div></div><p className="mt-8 text-xs leading-6 text-muted-foreground">Showcase lake data checked against official fisheries and managing-agency sources on August 13, 2026. Conditions, regulations and access can change; confirm current official information before travel.</p></section>
    </Container>
  </>;
}
