import { createFileRoute } from '@tanstack/react-router';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { PropertyClusterGuidePage } from '@/components/guides/PropertyClusterGuidePage';
import { buildMeta, canonicalLink, jsonLd } from '@/lib/seo';

const canonicalPath = '/learn/disabled-veteran-property-tax-benefits';
const description = 'Texas disabled veteran property-tax exemption guide with 2026 rating tiers, the 100% residence-homestead exemption, surviving-spouse rules and filing steps.';
const siteUrl = `https://${texasDefinedBrand.identity.domain}`;
const pageUrl = `${siteUrl}${canonicalPath}`;
const pageTitle = 'Texas Disabled Veteran Property Tax Exemption';
const heading = 'Texas disabled veteran property tax exemptions: 2026 guide';
const faqs = [
  { question: 'Do disabled veterans get a property-tax exemption in Texas?', answer: 'Yes. Texas provides partial property-tax exemptions tied to qualifying service-connected disability ratings, and separate law provides a total residence-homestead exemption for some veterans receiving 100% disability compensation because of a 100% disability rating or individual unemployability.' },
  { question: 'What are the Texas disabled-veteran exemption tiers?', answer: 'Under Tax Code Section 11.22, the exemption is up to $5,000 of property value for a 10%–29% disability rating, $7,500 for 30%–49%, $10,000 for 50%–69%, and $12,000 for 70%–100%. Separate rules can provide a $12,000 exemption for certain veterans age 65 or older, totally blind, or who have lost use of one or more limbs.' },
  { question: 'Can a 100% disabled veteran owe no property tax on a Texas homestead?', answer: 'A qualifying veteran can receive an exemption of the total appraised value of the residence homestead under Tax Code Section 11.131. The veteran must satisfy the statutory VA-compensation and disability requirements, and the exemption applies to the residence homestead rather than every property the veteran owns.' },
  { question: 'Is a VA disability rating enough by itself to determine the Texas exemption?', answer: 'No. VA or military disability documentation is important, but the appraisal district must apply Texas property-tax law to the application, ownership, residence and other eligibility requirements.' },
  { question: 'What is Texas Form 50-135?', answer: 'Form 50-135 is the Texas Comptroller application for the partial disabled-veteran or survivor exemption under Tax Code Section 11.22. File the applicable current form with the appraisal district that appraises the property, not with the Comptroller.' },
  { question: 'Can a surviving spouse continue the benefit?', answer: 'Some surviving spouses can continue a veteran-related exemption if statutory conditions are met. The exact rule depends on which veteran exemption applied, and requirements can include residence and remarriage conditions.' },
  { question: 'Where do I apply for a disabled-veteran property-tax exemption?', answer: 'Apply with the appraisal district that appraises the property, using the current official application and supporting VA or military documentation. Do not file the local exemption application with the Texas Comptroller.' },
];

export const Route = createFileRoute('/learn/disabled-veteran-property-tax-benefits')({
  head: () => ({ meta: buildMeta(texasDefinedBrand, { canonicalPath, title: pageTitle, description }), links: [canonicalLink(texasDefinedBrand, canonicalPath)], scripts: [jsonLd({ '@context': 'https://schema.org', '@graph': [
    { '@type': 'Article', headline: heading, description, url: pageUrl, dateModified: '2026-08-25', publisher: { '@id': `${siteUrl}/#organization` } },
    { '@type': 'FAQPage', mainEntity: faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) },
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: `${siteUrl}/` }, { '@type': 'ListItem', position: 2, name: 'Property taxes', item: `${siteUrl}/learn/property-taxes` }, { '@type': 'ListItem', position: 3, name: 'Disabled veteran benefits', item: pageUrl }] },
  ] })] }),
  component: () => <PropertyClusterGuidePage eyebrow="Veteran property-tax relief" title={heading} intro="Texas disabled-veteran property-tax relief includes rating-based partial exemptions and, for some qualifying veterans, a total residence-homestead exemption. This guide separates those benefits, gives the current rating tiers, explains the 100% rule and shows where to file locally." officialUrl="https://comptroller.texas.gov/taxes/property-tax/exemptions/disabledvet-faq.php" officialLabel="Texas Comptroller disabled veteran exemption guidance" faqs={faqs} sections={[
    { id: 'tiers', title: '2026 disabled-veteran exemption amounts by disability rating', paragraphs: ['Texas Tax Code Section 11.22 provides a partial exemption from the property value used for taxation. It is not a percentage reduction in the tax bill and it is different from the separate total residence-homestead exemption for qualifying 100% disabled veterans.'], bullets: ['10%–29% service-connected disability: up to $5,000 of property value exempted.', '30%–49%: up to $7,500 of property value exempted.', '50%–69%: up to $10,000 of property value exempted.', '70%–100%: up to $12,000 of property value exempted.', 'A separate $12,000 rule can apply to certain veterans age 65 or older with at least a 10% rating, veterans who are totally blind, or veterans who have lost use of one or more limbs.'] },
    { id: 'total', title: '100% disabled veteran residence-homestead exemption', paragraphs: ['Tax Code Section 11.131 provides an exemption of the total appraised value of the residence homestead for a qualifying disabled veteran awarded 100% disability compensation because of a 100% disability rating or a determination of individual unemployability by the U.S. Department of Veterans Affairs.', 'This total exemption applies to the qualifying residence homestead. It does not automatically make every other property owned by the veteran tax-exempt. A veteran may also qualify for the separate Section 11.22 partial exemption on one property when its requirements are met.'] },
    { id: 'forms', title: 'Which application goes to the appraisal district?', paragraphs: ['The appraisal district—not the tax office and not the Texas Comptroller—receives the local exemption application. Texas Comptroller Form 50-135 is the Disabled Veteran’s or Survivor’s Exemption Application for the partial Section 11.22 exemption. The 100% disabled-veteran residence-homestead exemption is claimed through the applicable residence-homestead application and supporting documentation.', 'Use the current form supplied by the Comptroller or appraisal district and verify the filing instructions for the tax year in question.'] },
    { id: 'donated-home', title: 'Donated-home provisions', paragraphs: ['Separate relief may apply to qualifying disabled veterans who receive a donated residence from a charitable organization. The benefit depends on disability rating, donation terms and statutory qualifications.'] },
    { id: 'survivors', title: 'Surviving spouses and children', paragraphs: ['Texas law provides continuation or separate relief for some surviving spouses and, in limited cases, children. Eligibility depends on which veteran exemption applied and can include residence, remarriage, ownership and age requirements. For the Section 11.131 total residence-homestead exemption, the Comptroller states that an eligible surviving spouse must not have remarried and must satisfy the residence-homestead conditions.'] },
    { id: 'filing', title: 'How to apply in your Texas county', paragraphs: ['File with the appraisal district that appraises the property and include the current application plus qualifying military or VA documentation. Keep the approval notice and verify the exemption on the appraisal record and tax bill. Use the county guide to find the correct appraisal district before filing.', 'The Comptroller lists April 30 as the normal deadline for disabled-veteran exemptions, while Texas law also permits certain late applications. If a deadline has passed, check the current Comptroller guidance and your appraisal district rather than assuming the benefit is lost.'], bullets: ['/property-tax/counties', '/texas-disabled-veteran-property-tax-calculator'] },
    { id: 'mistakes', title: 'Common mistakes', paragraphs: ['Frequent problems include filing with the tax office instead of the appraisal district, assuming benefits transfer automatically after a move, confusing the Section 11.22 partial exemption with the Section 11.131 total homestead exemption, treating the VA rating as the only requirement, failing to update ownership and not checking whether the exemption appears for every applicable taxing unit.'] },
  ]} />,
});
