import { createFileRoute, Link } from '@tanstack/react-router';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { Container } from '@/components/layout/Container';
import { buildMeta, canonicalLink } from '@/lib/seo';

const description='A plain-English guide to property-tax deadlines, escrow, payment options, late charges, agreements, refunds, liens and tax sales.';
export const Route=createFileRoute('/learn/property-tax-payments')({head:()=>({meta: buildMeta(texasDefinedBrand, {
      canonicalPath: '/learn/property-tax-payments',
      title:'Texas Property-Tax Payments and Collections',description}),
    links: [canonicalLink(texasDefinedBrand, '/learn/property-tax-payments')]}),component:Page});
function Page(){return <Container className="py-16 sm:py-24"><article className="mx-auto max-w-4xl"><p className="eyebrow text-primary">When the bill arrives</p><h1 className="mt-3 font-display text-4xl sm:text-6xl">Paying Your Property Taxes</h1><p className="mt-5 text-lg text-muted-foreground">{description}</p><p className="mt-3 text-sm text-muted-foreground">Reviewed August 3, 2026. Your collecting office has the final word on account-specific dates and balances.</p>
<div className="mt-12 space-y-12">
<Section title="Start with the bill itself"><p>Check the owner, account number, legal description, property address, tax year, each taxing unit, taxable value, exemptions, rate, amount due and delinquency date. One statement may include a county, city, school district, MUD, hospital district, emergency-services district, college district and other local units.</p><Callout>Didn’t receive a bill? Contact the collector anyway. A missing bill usually does not erase the tax, penalties, interest or lien.</Callout></Section>
<Section title="Know the deadline"><p>Taxes are generally due when the bill arrives. In an ordinary year, January 31 is the last day to pay before delinquency and unpaid taxes become delinquent February 1. Corrected bills, late-mailed bills, split-payment plans, protests, disasters and other circumstances can change that date, so use the deadline printed on your statement.</p><p>Continuing a value appeal? You may still need to pay a required amount before delinquency to preserve the appeal.</p></Section>
<Section title="Choose the payment method that fits"><p>Collectors may accept checks, money orders, cash, electronic transfers, e-checks, bank drafts and credit cards. Online and card payments may include processing fees. Check timestamp rules, mailing addresses, rejected-payment policies and what counts as proof of payment.</p><p>Early-payment discounts, split payments and partial payments are available only when the collector offers them.</p></Section>
<Section title="Keep an eye on escrow"><p>Mortgage servicers commonly collect part of the projected annual taxes and insurance with each monthly payment. Even when escrow is supposed to handle the bill, check the tax account after payment season. Make sure the servicer paid the correct account and received any corrected or supplemental bills.</p><p>Escrow shortages can raise monthly payments when taxes, insurance, values or exemption assumptions change.</p></Section>
<Section title="Installments and deferrals"><p>Some homeowners who are 65 or older, disabled, or eligible under certain disabled-veteran provisions may qualify for four installments. Certain disaster-affected owners may qualify too. Eligibility and first-payment deadlines matter.</p><p>A homestead deferral postpones collection; it does not erase the debt. The balance remains tied to the property and generally continues to accrue interest.</p></Section>
<Section title="What happens after delinquency"><p>For an ordinary February 1 delinquency, penalties and interest begin to accumulate. The penalty generally grows monthly until reaching 12 percent on July 1, while interest generally continues at one percent for each month or part of a month. A referral to a delinquent-tax attorney can add collection charges.</p><Callout>Ask for a payoff amount valid through the date you expect to pay. Flag failed escrow, returned payments, ownership errors or corrected bills, and get every agreement in writing.</Callout></Section>
<Section title="Payment agreements"><p>Some collectors offer installment agreements that stretch payments over several months. Terms may require a down payment, current-year taxes to stay current and every installment to arrive on time. Read the years, properties, penalties, fees and default terms before signing.</p></Section>
<Section title="Waivers and refunds"><p>Limited waivers may apply when a taxpayer relied on incorrect government information or another defined circumstance can be proven. Refund requests have deadlines and documentation requirements. Put the request in writing and keep copies of notices, receipts and supporting evidence.</p></Section>
<Section title="Liens, lawsuits and tax sales"><p>Property taxes are secured by a lien. Continued delinquency can lead to a collection lawsuit, judgment, foreclosure and tax sale. Waiting until a lawsuit begins usually makes the problem more expensive and leaves fewer options.</p></Section>
<section className="rounded-md border border-border p-6"><h2 className="font-display text-2xl">Before you send payment</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm text-muted-foreground"><li>Verify the account, year and taxing units.</li><li>Use the delinquency date printed on the bill.</li><li>Confirm exemptions and who is responsible for escrow.</li><li>Save receipts and confirmation numbers.</li><li>Check that the payment reached the correct account.</li><li>Call the collector early when full payment is not possible.</li></ol></section>
</div><div className="mt-12 flex flex-wrap gap-4"><a className="underline" href="https://comptroller.texas.gov/taxes/property-tax/" target="_blank" rel="noreferrer">Check official state guidance</a><Link className="underline" to="/learn/property-taxes">Understand the full tax bill</Link><Link className="underline" to="/browse/counties">Find your county office</Link></div></article></Container>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="font-display text-3xl">{title}</h2><div className="mt-4 space-y-4 leading-7 text-muted-foreground">{children}</div></section>}
function Callout({children}:{children:React.ReactNode}){return <div className="rounded-md bg-muted p-5 text-foreground">{children}</div>}
