import { createFileRoute, Link } from '@tanstack/react-router';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { Container } from '@/components/layout/Container';
import { buildMeta, canonicalLink } from '@/lib/seo';

const description='Texas property-tax payment deadlines, escrow, installment options, delinquency charges, payment agreements, waivers, refunds, liens and tax sales.';
export const Route=createFileRoute('/learn/property-tax-payments')({head:()=>({meta:buildMeta(texasDefinedBrand,{title:'Texas Property-Tax Payments and Collections',description}),links:[canonicalLink(texasDefinedBrand,'/learn/property-tax-payments')]}),component:Page});
function Page(){return <Container className="py-16 sm:py-24"><article className="mx-auto max-w-4xl"><p className="eyebrow text-primary">Texas Home & Property</p><h1 className="mt-3 font-display text-4xl sm:text-6xl">Texas Property-Tax Payments and Collections</h1><p className="mt-5 text-lg text-muted-foreground">{description}</p><p className="mt-3 text-sm text-muted-foreground">Last reviewed August 3, 2026. Verify account-specific dates and balances with the collecting office.</p>
<div className="mt-12 space-y-12">
<Section title="Reading the tax bill"><p>Check the owner, account number, legal description, property address, tax year, each taxing unit, taxable value, exemptions, rate, amount due and delinquency date. A single statement may collect for a county, city, school district, MUD, hospital district, emergency-services district, college district and other units.</p><Callout>Not receiving a bill generally does not erase the tax, penalties, interest, lien or collection action. Contact the collector when a bill has not arrived.</Callout></Section>
<Section title="Ordinary payment deadlines"><p>Taxes are generally due upon receipt. In ordinary cases, January 31 is the last day to pay before delinquency and unpaid taxes become delinquent February 1. Late-mailed bills, corrected bills, split-payment programs, protests, disasters and other statutory situations can produce a different date, so the date printed on the actual bill controls.</p><p>Owners continuing a value appeal generally must still pay the amount required by law before delinquency to preserve the appeal.</p></Section>
<Section title="Ways to pay"><p>Collectors may accept check, money order, currency, electronic transfer, electronic check, bank draft and credit card. Card and online payments may carry processing fees. Confirm timestamp rules, mailing addresses, rejected-payment policies and proof-of-payment requirements.</p><p>Early-payment discounts, split payments and partial payments exist only when authorized and offered by the collector.</p></Section>
<Section title="Mortgage escrow"><p>Mortgage servicers commonly collect one-twelfth of projected annual taxes and insurance each month. Review the collector's account after payment season even when escrow is expected to pay. Confirm the servicer used the right account and tax year and received corrected or supplemental bills.</p><p>Escrow shortages may raise monthly payments when taxes, insurance, values or exemption assumptions change.</p></Section>
<Section title="Installments and deferrals"><p>Qualifying homeowners who are age 65 or older, disabled, or eligible under specified disabled-veteran provisions may qualify for four installments. Certain disaster-affected owners may also qualify. Eligibility, notice and first-payment deadlines matter.</p><p>A residence-homestead deferral postpones collection but does not forgive the debt. The balance remains secured by the tax lien and generally accrues interest while the deferral remains in effect.</p></Section>
<Section title="Delinquency, penalties and interest"><p>For an ordinary February 1 delinquency, penalty and interest begin accumulating. The penalty generally increases monthly until reaching 12 percent on July 1, while interest generally continues at one percent for each month or part of a month. Referral to a delinquent-tax attorney can add collection charges.</p><Callout>Request a payoff amount valid through the expected payment date. Identify failed escrow, returned payments, ownership errors or corrected bills, and obtain every payment agreement in writing.</Callout></Section>
<Section title="Delinquent payment agreements"><p>Collectors may offer installment agreements, sometimes extending for many months. Terms can require a down payment, current-year taxes to remain current and strict compliance with each installment. Signing may constitute an admission that covered taxes are owed, so review the years, properties, penalties, fees and default terms before signing.</p></Section>
<Section title="Waivers and refunds"><p>Limited statutory waivers may apply when a taxpayer relied on incorrect government information or when another defined circumstance is proven. Refund claims have deadlines and documentation requirements. Submit requests in writing and keep copies of notices, receipts and supporting evidence.</p></Section>
<Section title="Tax liens, lawsuits and tax sales"><p>Texas property taxes are secured by a lien. Continued delinquency can lead to a collection lawsuit, judgment, foreclosure and tax sale. Other lienholders and owners receive process under applicable law, but waiting until litigation begins usually increases costs and reduces options.</p></Section>
<section className="rounded-md border border-border p-6"><h2 className="font-display text-2xl">Payment checklist</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm text-muted-foreground"><li>Verify the account, year and taxing units.</li><li>Use the delinquency date printed on the bill.</li><li>Confirm exemptions and escrow responsibility.</li><li>Save receipts and confirmation numbers.</li><li>Check that payment posted to the correct account.</li><li>Contact the collector promptly when full payment is not possible.</li></ol></section>
</div><div className="mt-12 flex flex-wrap gap-4"><a className="underline" href="https://comptroller.texas.gov/taxes/property-tax/" target="_blank" rel="noreferrer">Texas Comptroller official guidance</a><Link className="underline" to="/learn/property-taxes">Complete property-tax guide</Link><Link className="underline" to="/browse/counties">Find county resources</Link></div></article></Container>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="font-display text-3xl">{title}</h2><div className="mt-4 space-y-4 leading-7 text-muted-foreground">{children}</div></section>}
function Callout({children}:{children:React.ReactNode}){return <div className="rounded-md bg-muted p-5 text-foreground">{children}</div>}
