import { createFileRoute, Link } from '@tanstack/react-router';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { buildMeta, canonicalLink } from '@/lib/seo';
import { Container } from '@/components/layout/Container';
const canonicalPath='/moving-to-texas/tools';
const description='TexasDefined tools for county, school, utility, voter, homestead, property-tax, ZIP and city research when moving to Texas.';
const tools=[['Find my Texas county','/find-my-county','Use the address-level county utility already built on TexasDefined.'],['Find my school district','/find-my-school-district','Verify the exact address with Texas education sources.'],['Find my utilities','/find-my-utilities','Research electric, water and sewer service territories.'],['Find voter registration','/find-my-voter-registration','Continue to official Texas registration records.'],['Find homestead filing','/find-my-homestead-exemption','Reach the correct appraisal-district filing path.'],['Find property-tax offices','/find-my-property-tax','Find appraisal and tax-office resources.'],['Emergency & community services','/find-my-emergency-services','Connect local context with emergency and 2-1-1 resources.'],['Texas ZIP explorer','/texas-zip-code-explorer','Use a ZIP as a starting point without treating it as a legal boundary.'],['Compare Texas cities','/compare-texas-cities','Compare city and county context side by side.']] as const;
function Page(){return <Container className="pb-16 pt-12 sm:pb-24 sm:pt-16"><article className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="border-b border-border pb-4 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span className="mx-2">/</span><Link to="/moving-to-texas">Moving to Texas</Link><span className="mx-2">/</span><span>Tools</span></nav><header className="border-b border-border py-10"><p className="eyebrow text-primary">Moving to Texas</p><h1 className="mt-3 font-display text-5xl sm:text-7xl">Texas relocation tools</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Move from broad Texas research to the exact official source for an address without treating a mailing city or ZIP code as if it defines every local boundary.</p></header><section className="grid gap-px border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{tools.map(([name,to,copy])=><Link key={to} to={to} className="group bg-background p-6"><h2 className="font-display text-2xl group-hover:text-primary">{name}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p><span className="mt-5 inline-block text-sm font-semibold text-primary">Open tool →</span></Link>)}</section></article></Container>}
export const Route=createFileRoute('/moving-to-texas/tools')({head:()=>({meta:buildMeta(texasDefinedBrand,{canonicalPath,title:'Texas Relocation Tools',description}),links:[canonicalLink(texasDefinedBrand,canonicalPath)]}),component:Page});
