import { createFileRoute, Link } from '@tanstack/react-router';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { Container } from '@/components/layout/Container';
import { absoluteUrl, buildMeta, canonicalLink, jsonLd } from '@/lib/seo';
const canonicalPath='/property-tax-calculators';const description='Texas property-tax calculators for homestead savings, protest savings, escrow, age-65 scenarios, disabled-veteran exemptions, agricultural valuation and location comparisons.';
export const Route=createFileRoute('/property-tax-calculators')({head:()=>({meta:buildMeta(texasDefinedBrand,{canonicalPath,title:'Texas Property Tax Calculator Toolkit',description}),links:[canonicalLink(texasDefinedBrand,canonicalPath)],scripts:[jsonLd({'@context':'https://schema.org','@type':'CollectionPage','@id':`${absoluteUrl(texasDefinedBrand,canonicalPath)}#collection`,name:'Texas Property Tax Calculator Toolkit',description,url:absoluteUrl(texasDefinedBrand,canonicalPath)})]}),component:Page});
const tools=[
['Homestead savings','Estimate school and other local tax effects without applying one exemption to every taxing unit.','/texas-homestead-savings-calculator'],
['Property-tax protest savings','Model the tax effect of reducing a proposed appraisal to a supportable target value.','/texas-property-tax-protest-savings-calculator'],
['Escrow','Estimate monthly property-tax, insurance and HOA funding.','/texas-property-tax-escrow-calculator'],
['Age 65+','Model entered exemptions and an existing school-tax ceiling.','/texas-over-65-property-tax-calculator'],
['Disabled veteran','Estimate savings from a verified disabled-veteran exemption amount.','/texas-disabled-veteran-property-tax-calculator'],
['Agricultural valuation','Compare market-value and productivity-value tax scenarios.','/texas-agricultural-valuation-calculator'],
['Location comparison','Compare two exact local rate and exemption scenarios.','/texas-property-tax-county-comparison-calculator'],
] as const;
function Page(){return <Container className="pb-16 pt-12 sm:pb-24 sm:pt-16"><article className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="border-b border-border pb-4 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span className="mx-2">/</span><Link to="/property">Property</Link><span className="mx-2">/</span><span>Calculators</span></nav><header className="border-b border-border py-10"><p className="eyebrow text-primary">Property Taxes</p><h1 className="mt-3 max-w-4xl font-display text-5xl leading-[0.98] sm:text-7xl">Texas property-tax calculator toolkit</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Choose the calculator that matches the decision you are making. Each production tool keeps assumptions explicit and links estimates back to the relevant Texas property-tax guidance.</p></header><div className="grid gap-x-8 md:grid-cols-2">{tools.map(([title,copy,to])=><Link key={to} to={to} className="border-b border-border py-8"><span className="eyebrow text-primary">Calculator</span><h2 className="mt-2 font-display text-3xl">{title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{copy}</p><span className="mt-5 inline-block font-semibold text-primary">Open calculator →</span></Link>)}</div><p className="mt-10 border-t border-border pt-6 text-sm leading-6 text-muted-foreground">These are planning tools. Verify appraisal values, exemptions, adopted rates, tax ceilings and eligibility with the responsible local authorities before making a financial decision.</p></article></Container>}
