import { createFileRoute, Link } from '@tanstack/react-router';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { Container } from '@/components/layout/Container';
import { absoluteUrl, buildMeta, canonicalLink, jsonLd } from '@/lib/seo';

const canonicalPath='/property-tax-calculators';
const description='Free Texas property-tax calculators for homestead savings, appraisal protests, escrow, age-65 scenarios, disabled-veteran exemptions, agricultural valuation and county comparisons.';
const tools=[
  ['Homestead savings','Estimate how entered homestead exemptions can change taxable value and annual taxes without assuming every taxing unit offers the same exemption.','/texas-homestead-savings-calculator','I want to estimate homestead-exemption savings'],
  ['Property-tax protest savings','Compare the tax effect of the proposed appraisal with a lower, supportable target value before deciding whether a protest may be worthwhile.','/texas-property-tax-protest-savings-calculator','I am considering an appraisal protest'],
  ['Escrow','Estimate the monthly amount needed for property taxes, homeowners insurance and HOA costs alongside a mortgage payment.','/texas-property-tax-escrow-calculator','I need a monthly housing-cost estimate'],
  ['Age 65+','Model entered exemptions and an existing school-tax ceiling without treating the ceiling as a universal freeze on the entire tax bill.','/texas-over-65-property-tax-calculator','I am planning around age-65 tax benefits'],
  ['Disabled veteran','Estimate savings from a verified disabled-veteran exemption amount using the local values and rates you enter.','/texas-disabled-veteran-property-tax-calculator','I need to model a disabled-veteran exemption'],
  ['Agricultural valuation','Compare a market-value scenario with a productivity-value scenario for land that may qualify for agricultural appraisal.','/texas-agricultural-valuation-calculator','I am evaluating agricultural valuation'],
  ['County / location comparison','Compare two exact property-tax scenarios using local taxable values, rates and exemptions instead of relying on county averages.','/texas-property-tax-county-comparison-calculator','I am comparing places to live'],
] as const;

export const Route=createFileRoute('/property-tax-calculators')({
  head:()=>{
    const pageUrl=absoluteUrl(texasDefinedBrand,canonicalPath);
    const siteUrl=absoluteUrl(texasDefinedBrand,'/');
    return {meta:buildMeta(texasDefinedBrand,{canonicalPath,title:'Texas Property Tax Calculators | Free Planning Tools',description}),links:[canonicalLink(texasDefinedBrand,canonicalPath)],scripts:[jsonLd({'@context':'https://schema.org','@graph':[
      {'@type':'CollectionPage','@id':`${pageUrl}#page`,name:'Texas Property Tax Calculators',description,url:pageUrl,isPartOf:{'@id':`${siteUrl}#website`},mainEntity:{'@id':`${pageUrl}#tools`},breadcrumb:{'@id':`${pageUrl}#breadcrumb`}},
      {'@type':'ItemList','@id':`${pageUrl}#tools`,numberOfItems:tools.length,itemListElement:tools.map(([title,,to],index)=>({'@type':'ListItem',position:index+1,name:`Texas ${title} calculator`,url:absoluteUrl(texasDefinedBrand,to)}))},
      {'@type':'BreadcrumbList','@id':`${pageUrl}#breadcrumb`,itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:siteUrl},{'@type':'ListItem',position:2,name:'Property',item:absoluteUrl(texasDefinedBrand,'/property')},{'@type':'ListItem',position:3,name:'Property-tax calculators',item:pageUrl}]}
    ]})]};
  },component:Page
});

function Page(){return <Container className="pb-16 pt-12 sm:pb-24 sm:pt-16"><article className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="border-b border-border pb-4 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span className="mx-2">/</span><Link to="/property">Property</Link><span className="mx-2">/</span><span>Calculators</span></nav><header className="grid gap-8 border-b border-border py-10 lg:grid-cols-[minmax(0,1fr)_19rem] lg:items-end"><div><p className="eyebrow text-primary">Property Taxes</p><h1 className="mt-3 max-w-4xl font-display text-5xl leading-[0.98] sm:text-7xl">Texas property-tax calculators</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Free planning tools for Texas homeowners, homebuyers and landowners. Choose the question you are trying to answer, enter the local values and rates you know, and keep the assumptions visible.</p></div><p className="border-l border-border pl-6 text-sm leading-6 text-muted-foreground">There is no single Texas property-tax rate. For the most useful estimate, use the actual appraisal, exemptions and taxing-unit rates for the property.</p></header>
<section className="border-b border-border py-10"><p className="eyebrow text-primary">Choose by question</p><h2 className="mt-2 font-display text-4xl">Which calculator should I use?</h2><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{tools.map(([title,,to,question])=><Link key={`${to}-question`} to={to} className="rounded-md border border-border p-5 hover:border-primary/50"><span className="text-sm leading-6 text-muted-foreground">{question}</span><strong className="mt-2 block font-display text-2xl">{title} →</strong></Link>)}</div></section>
<section className="py-10"><div className="border-b border-border pb-4"><p className="eyebrow text-primary">All tools</p><h2 className="mt-2 font-display text-4xl">Calculate a Texas property-tax scenario</h2></div><div className="grid gap-x-8 md:grid-cols-2">{tools.map(([title,copy,to])=><Link key={to} to={to} className="border-b border-border py-8"><span className="eyebrow text-primary">Calculator</span><h3 className="mt-2 font-display text-3xl">Texas {title} calculator</h3><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{copy}</p><span className="mt-5 inline-block font-semibold text-primary">Open calculator →</span></Link>)}</div></section>
<section className="grid gap-8 border-t border-border py-10 lg:grid-cols-2"><div><p className="eyebrow text-primary">Need the local inputs?</p><h2 className="mt-2 font-display text-3xl">Start with your county guide</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Use the county directory to find appraisal records, exemption information, protest resources, payment offices and other official local starting points before running a scenario.</p><Link to="/property-tax/counties" className="mt-5 inline-block font-semibold text-primary underline decoration-primary/40 underline-offset-4">Browse all 254 county property-tax guides →</Link></div><div><p className="eyebrow text-primary">Need the rules first?</p><h2 className="mt-2 font-display text-3xl">Read the Texas property-tax guide</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Understand appraised value, taxable value, taxing units, exemptions, protests and payments before interpreting a calculator result.</p><Link to="/learn/property-taxes" className="mt-5 inline-block font-semibold text-primary underline decoration-primary/40 underline-offset-4">How Texas property taxes work →</Link></div></section>
<p className="border-t border-border pt-6 text-sm leading-6 text-muted-foreground">These calculators are planning tools, not tax statements or eligibility determinations. Verify appraisal values, exemptions, adopted rates, tax ceilings and eligibility with the responsible appraisal district, taxing unit or collecting office before making a financial decision.</p></article></Container>}
