import { createLazyFileRoute, Link } from '@tanstack/react-router';
import { useMemo, useState, type ReactNode } from 'react';

import { CitationTrustPanel } from '@/components/authority/CitationTrustPanel';
import { Container } from '@/components/layout/Container';
import type { SchoolDistrictTaxRateData, SchoolDistrictTaxRateRow } from '@/data/school-district-tax-rates';
import type { TexasDataset } from '@/data/texas-data-center';

export const Route = createLazyFileRoute('/texas-data/$datasetSlug')({ component: Page });

function Page() {
  const data = Route.useLoaderData() as TexasDataset & { schoolRates?: SchoolDistrictTaxRateData | null };
  return data.schoolRates ? <SchoolDistrictRates data={data.schoolRates} /> : <GenericDataset dataset={data} />;
}

function SchoolDistrictRates({ data }: { data: SchoolDistrictTaxRateData }) {
  const [query, setQuery] = useState('');
  const [county, setCounty] = useState('');
  const [sort, setSort] = useState('district');
  const counties = useMemo(() => [...new Set(data.rows.flatMap((row) => row.countySlugs))].sort(), [data.rows]);
  const reported = useMemo(() => data.rows.filter((row) => row.rate != null && !row.variableRate), [data.rows]);
  const values = useMemo(() => reported.map((row) => row.rate as number).sort((a, b) => a - b), [reported]);
  const average = values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
  const median = values.length ? (values.length % 2 ? values[Math.floor(values.length / 2)] : (values[values.length / 2 - 1] + values[values.length / 2]) / 2) : null;
  const low = reported.reduce<SchoolDistrictTaxRateRow | null>((best, row) => !best || (row.rate ?? Infinity) < (best.rate ?? Infinity) ? row : best, null);
  const high = reported.reduce<SchoolDistrictTaxRateRow | null>((best, row) => !best || (row.rate ?? -Infinity) > (best.rate ?? -Infinity) ? row : best, null);
  const comparable = data.rows.filter((row) => row.rate != null && row.priorRate != null && !row.variableRate);
  const biggestIncrease = [...comparable].sort((a, b) => change(b) - change(a))[0];
  const biggestDecrease = [...comparable].sort((a, b) => change(a) - change(b))[0];
  const rows = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return data.rows.filter((row) => (!needle || row.name.toLowerCase().includes(needle) || row.countySlugs.some((slug) => label(slug).toLowerCase().includes(needle))) && (!county || row.countySlugs.includes(county))).sort((a, b) => compare(a, b, sort));
  }, [county, data.rows, query, sort]);

  return <Container className="pb-16 pt-12 sm:pb-24 sm:pt-16"><article className="mx-auto max-w-7xl">
    <nav aria-label="Breadcrumb" className="border-b border-border pb-4 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span className="mx-2">/</span><Link to="/texas-data">Texas data</Link><span className="mx-2">/</span><span>School district tax rates</span></nav>
    <header className="grid gap-8 border-b border-border py-10 lg:grid-cols-[1fr_20rem] lg:items-end"><div><p className="eyebrow text-primary">Texas data · {data.year}</p><h1 className="mt-3 max-w-5xl font-display text-5xl leading-[0.98] sm:text-7xl">Texas School District Property Tax Rates — {data.year}</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-muted-foreground">Search Texas school districts statewide, compare {data.year} with {data.priorYear}, and see adopted M&O, I&S and total rates in the official dollars-per-$100 format.</p><div className="mt-6 flex flex-wrap gap-3"><a href={data.sourceWorkbook} className="border border-foreground px-4 py-2 text-sm font-semibold">Official {data.year} XLSX</a><button onClick={() => downloadCsv(data)} className="border border-border px-4 py-2 text-sm font-semibold">Download CSV</button></div></div><dl className="border-l border-border pl-6 text-sm"><Meta label="Source" value="Texas Comptroller PTAD"/><Meta label="Published" value="July 30, 2026"/><Meta label="Updated" value="October 4, 2026"/><Meta label="District records" value={data.rows.length.toLocaleString()} last/></dl></header>
    <section className="my-10 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><Stat label="Median rate" value={rate(median)} note="Unweighted district median"/><Stat label="Average rate" value={rate(average)} note={`${reported.length.toLocaleString()} single-rate districts`}/><Stat label="Lowest reported" value={rate(low?.rate ?? null)} note={low?.name ?? '—'}/><Stat label="Highest reported" value={rate(high?.rate ?? null)} note={high?.name ?? '—'}/></section>
    <section className="grid gap-8 border-y border-border py-9 lg:grid-cols-3"><Explainer title="How to read the rate">Rates are dollars per $100 of taxable value. A $1.1000 rate equals $1,100 per $100,000 of taxable value, before county, city and special-district taxes.</Explainer><Explainer title="M&O vs. I&S"><strong>M&O</strong> funds school operations. <strong>I&S</strong> funds voter-approved debt and facilities. Components appear when present in the source-backed record.</Explainer><Explainer title="Largest year-over-year moves">Increase: <strong>{biggestIncrease?.name ?? '—'}</strong> {delta(biggestIncrease ? change(biggestIncrease) : null)}. Decrease: <strong>{biggestDecrease?.name ?? '—'}</strong> {delta(biggestDecrease ? change(biggestDecrease) : null)}.</Explainer></section>
    <section className="py-10"><div className="flex flex-col gap-5 border-b border-border pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow text-primary">Statewide database</p><h2 className="mt-2 font-display text-4xl">Find a Texas school district</h2><p className="mt-3 text-sm text-muted-foreground">Showing {rows.length.toLocaleString()} of {data.rows.length.toLocaleString()} records.</p></div><div className="grid gap-3 sm:grid-cols-3 lg:min-w-[42rem]"><Control label="Search"><input className="mt-2 w-full border border-border bg-background px-3 py-2 text-sm" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="District or county"/></Control><Control label="County"><select className="mt-2 w-full border border-border bg-background px-3 py-2 text-sm" value={county} onChange={(event) => setCounty(event.target.value)}><option value="">All counties</option>{counties.map((slug) => <option key={slug} value={slug}>{label(slug)}</option>)}</select></Control><Control label="Sort"><select className="mt-2 w-full border border-border bg-background px-3 py-2 text-sm" value={sort} onChange={(event) => setSort(event.target.value)}><option value="district">District A–Z</option><option value="rate-high">Rate high–low</option><option value="rate-low">Rate low–high</option><option value="change-up">Largest increases</option><option value="change-down">Largest decreases</option></select></Control></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[72rem] border-collapse text-left text-sm"><thead><tr className="border-b border-border text-[0.68rem] uppercase tracking-[0.12em] text-muted-foreground"><th className="py-3 pr-4">District</th><th className="px-3 py-3">County / counties</th><th className="px-3 py-3 text-right">{data.year} total</th><th className="px-3 py-3 text-right">M&O</th><th className="px-3 py-3 text-right">I&S</th><th className="px-3 py-3 text-right">{data.priorYear}</th><th className="px-3 py-3 text-right">Change</th><th className="py-3 pl-3 text-right">Tax / $100K</th></tr></thead><tbody>{rows.map((row) => <tr key={row.slug} className="border-b border-border/70"><td className="py-4 pr-4"><strong>{row.name}</strong>{row.variableRate ? <div className="text-xs text-muted-foreground">Variable reported rate</div> : null}</td><td className="px-3 py-4 text-muted-foreground">{row.countySlugs.map(label).join(', ') || '—'}</td><td className="px-3 py-4 text-right font-semibold">{rowRate(row)}</td><td className="px-3 py-4 text-right">{rate(row.maintenanceOperationsRate)}</td><td className="px-3 py-4 text-right">{rate(row.debtServiceRate)}</td><td className="px-3 py-4 text-right">{rate(row.priorRate)}</td><td className="px-3 py-4 text-right">{delta(changeOrNull(row))}</td><td className="py-4 pl-3 text-right">{tax100k(row)}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-8 border-y border-border py-9 lg:grid-cols-2"><div><p className="eyebrow text-primary">Recommended citation</p><p className="mt-3 text-sm leading-7 text-muted-foreground">TexasDefined editorial staff. “Texas School District Property Tax Rates — {data.year}.” TexasDefined.com. Published July 30, 2026; updated October 4, 2026. Source: Texas Comptroller of Public Accounts, Property Tax Assistance Division.</p></div><div><p className="eyebrow text-primary">Scope</p><p className="mt-3 text-sm leading-7 text-muted-foreground">These are adopted school-district rates, not parcel-specific bills. Verify exemptions and all taxing units for a specific property.</p></div></section>
    <CitationTrustPanel className="mt-10" title="Sources, methodology and verification" lastVerified="October 4, 2026" sources={[{name:`${data.sourceName} — ${data.year} School District Rates and Levies`,url:data.sourceWorkbook,note:'Official statewide workbook used by the production dataset.'},{name:data.sourceName,url:data.sourcePage,note:'Official annual rate-and-levy source page.'},{name:'Texas Education Agency — School District Property Values and Tax Rates',url:'https://tea.texas.gov/about-tea/state-funding/additional-finance-resources/school-district-property-values-and-tax-rates',note:'Official school-finance reference for M&O and I&S terminology.'}]} methodology={`TexasDefined reads its production school-district records from the Texas Comptroller-backed statewide dataset. ${data.year} rows are matched to ${data.priorYear} by stable district slug. Summary statistics exclude missing or variable total rates. Rates are dollars per $100 of taxable value.`}/>
    <footer className="flex flex-wrap gap-6 py-8 text-sm font-semibold"><Link to="/texas-data">More Texas data</Link><Link to="/learn/property-taxes">Property-tax guide</Link><Link to="/texas-property-tax-bill-breakdown">Property-tax bill calculator</Link><Link to="/browse/counties">County directory</Link></footer>
  </article></Container>;
}

function GenericDataset({ dataset }: { dataset: TexasDataset }) {
  const relocation = ['Relocation and migration','Insurance','Jobs','Transportation'].includes(dataset.category);
  return <Container className="pb-16 pt-12 sm:pb-24 sm:pt-16"><article className="mx-auto max-w-6xl"><nav className="border-b border-border pb-4 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span className="mx-2">/</span><Link to="/texas-data">Texas data</Link><span className="mx-2">/</span>{dataset.title}</nav><header className="grid gap-8 border-b border-border py-10 lg:grid-cols-[1fr_18rem] lg:items-end"><div><p className="eyebrow text-primary">Texas data · {dataset.year}</p><h1 className="mt-3 max-w-4xl font-display text-5xl leading-[0.98] sm:text-7xl">{dataset.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{dataset.description}</p></div><dl className="border-l border-border pl-6 text-sm"><Meta label="Source" value={dataset.sourceName}/><Meta label="Last verified" value={formatDate(dataset.updated)}/><Meta label="Coverage" value={String(dataset.year)} last/></dl></header><section className="py-10"><p className="eyebrow text-primary">Key findings</p><h2 className="mt-2 border-b border-border pb-4 font-display text-4xl">What the numbers show</h2><div className="divide-y divide-border border-b border-border">{dataset.rows.map((row) => <div key={row.label} className="grid gap-2 py-5 sm:grid-cols-[1.2fr_.7fr_1.5fr] sm:gap-6"><h3 className="font-display text-xl">{row.label}</h3><p className="font-display text-2xl font-semibold text-primary">{formatValue(row.value,dataset.unit)}</p><p className="text-sm leading-6 text-muted-foreground">{row.note ?? 'No additional note.'}</p></div>)}</div></section><CitationTrustPanel sources={[{name:dataset.sourceName,url:dataset.sourceUrl,note:`Authoritative source for the ${dataset.year} coverage shown in this brief.`}]} methodology={dataset.methodology} lastVerified={formatDate(dataset.updated)} title="Sources, methodology and verification"/><footer className="flex flex-wrap gap-6 py-7 text-sm font-semibold"><Link to="/texas-data">More Texas data</Link>{relocation ? <><Link to="/moving-to-texas">Moving to Texas</Link><Link to="/browse/cities">Compare cities</Link></> : <><Link to="/learn/property-taxes">Property-tax guide</Link><Link to="/browse/counties">County directory</Link></>}</footer></article></Container>;
}

function Meta({label: name,value,last=false}:{label:string;value:string;last?:boolean}){return <div className={`${last?'':'border-b border-border'} py-3`}><dt className="text-[0.68rem] uppercase tracking-[0.16em] text-muted-foreground">{name}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
function Stat({label: name,value,note}:{label:string;value:string;note:string}){return <div className="bg-background p-5"><p className="text-[0.68rem] uppercase tracking-[0.14em] text-muted-foreground">{name}</p><p className="mt-2 font-display text-3xl font-semibold text-primary">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></div>}
function Explainer({title,children}:{title:string;children:ReactNode}){return <div><h2 className="font-display text-3xl">{title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{children}</p></div>}
function Control({label: name,children}:{label:string;children:ReactNode}){return <label className="text-xs font-semibold uppercase tracking-[0.12em]">{name}{children}</label>}
function change(row:SchoolDistrictTaxRateRow){return (row.rate??0)-(row.priorRate??0)}
function changeOrNull(row:SchoolDistrictTaxRateRow){return row.rate!=null&&row.priorRate!=null&&!row.variableRate?change(row):null}
function compare(a:SchoolDistrictTaxRateRow,b:SchoolDistrictTaxRateRow,sort:string){if(sort==='rate-high')return n(b.rate,-Infinity)-n(a.rate,-Infinity)||a.name.localeCompare(b.name);if(sort==='rate-low')return n(a.rate,Infinity)-n(b.rate,Infinity)||a.name.localeCompare(b.name);if(sort==='change-up')return n(changeOrNull(b),-Infinity)-n(changeOrNull(a),-Infinity)||a.name.localeCompare(b.name);if(sort==='change-down')return n(changeOrNull(a),Infinity)-n(changeOrNull(b),Infinity)||a.name.localeCompare(b.name);return a.name.localeCompare(b.name)}
function n(value:number|null,fallback:number){return value==null||!Number.isFinite(value)?fallback:value}
function rate(value:number|null){return value==null?'—':`$${value.toFixed(4)}`}
function delta(value:number|null){return value==null?'—':`${value>0?'+':''}${value.toFixed(4)}`}
function rowRate(row:SchoolDistrictTaxRateRow){if(row.variableRate&&row.rateVariants.length>1){const values=[...row.rateVariants].sort((a,b)=>a-b);return `${rate(values[0])}–${rate(values.at(-1)??null)}`}return rate(row.rate)}
function tax100k(row:SchoolDistrictTaxRateRow){if(row.variableRate&&row.rateVariants.length>1){const values=[...row.rateVariants].sort((a,b)=>a-b);return `${money(values[0]*1000)}–${money((values.at(-1)??0)*1000)}`}return row.rate==null?'—':money(row.rate*1000)}
function money(value:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value)}
function label(slug:string){return slug.replaceAll('-',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase())}
function formatDate(value:string){const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'}).format(date)}
function formatValue(value:number,unit:TexasDataset['unit']){return unit==='dollars'?money(value):unit==='percent'?`${value.toFixed(4)}%`:new Intl.NumberFormat('en-US').format(value)}
function downloadCsv(data:SchoolDistrictTaxRateData){const cell=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;const lines=[['school_district','counties',`${data.year}_total_rate_per_100`,'m_and_o_rate_per_100','i_and_s_rate_per_100',`${data.priorYear}_total_rate_per_100`,'year_over_year_change','tax_per_100k_taxable_value','source_status'].map(cell).join(','),...data.rows.map((row)=>[row.name,row.countySlugs.map(label).join('; '),row.rate,row.maintenanceOperationsRate,row.debtServiceRate,row.priorRate,changeOrNull(row),row.rate==null||row.variableRate?null:row.rate*1000,row.sourceStatus].map(cell).join(','))];const href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=href;a.download=`texas-school-district-tax-rates-${data.year}.csv`;a.click();URL.revokeObjectURL(href)}
