import { createFileRoute } from '@tanstack/react-router';
import { Container } from '@/components/layout/Container';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { buildMeta, canonicalLink } from '@/lib/seo';

const description = 'Understand Texas state and local sales tax, exemptions, online purchases, use tax, permits, and official transaction verification.';
export const Route = createFileRoute('/texas-sales-tax-explained')({ head: () => ({ meta: buildMeta(texasDefinedBrand, {
      canonicalPath: '/texas-sales-tax-explained',
      title: 'Texas Sales Tax Explained', description }),
    links: [canonicalLink(texasDefinedBrand, '/texas-sales-tax-explained')] }), component: Page });
function Page() { return <Container className="py-16 sm:py-24"><article className="prose prose-gray mx-auto max-w-4xl"><p className="eyebrow text-primary">Texas taxes</p><h1>Texas Sales Tax Explained</h1><p className="lead">{description}</p><h2>State and local tax</h2><p>A taxable transaction may include the statewide rate plus city, county, transit, or special-purpose district components. The correct combined rate depends on the transaction, location, delivery destination, and Texas sourcing rules.</p><h2>Taxable and exempt purchases</h2><p>Many sales of tangible personal property are taxable unless an exemption applies. Some services are taxable, while many basic grocery items and qualifying medical, agricultural, manufacturing, resale, or exempt-organization purchases may receive different treatment. Documentation must match the legal exemption.</p><h2>Online purchases and use tax</h2><p>Marketplace providers and remote sellers may collect Texas tax at checkout. When tax is not collected on a taxable purchase, Texas use-tax obligations may still apply.</p><h2>Business permits and records</h2><p>A seller of taxable goods or services should determine whether a Texas sales-tax permit, collection, filing, and recordkeeping are required. Resale certificates apply to qualifying purchases for resale—not ordinary business consumption.</p><h2>Verify a transaction</h2><ol><li>Identify the exact product or service.</li><li>Confirm whether it is taxable.</li><li>Check any exemption and required certificate.</li><li>Determine the correct transaction location.</li><li>Use the official rate and guidance tools.</li><li>Retain invoices and supporting records.</li></ol><p><a href="https://comptroller.texas.gov/taxes/sales/" rel="noreferrer">Texas Comptroller sales and use tax guidance</a></p><aside className="not-prose mt-10 rounded-lg bg-muted p-5 text-sm text-muted-foreground">Tax rules and administrative guidance can change. Confirm a specific filing or exemption with the Texas Comptroller or a qualified professional.</aside></article></Container>; }
