import { createFileRoute, Link } from '@tanstack/react-router';
import { useCallback, useMemo, useState } from 'react';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { CalculatorActions, CalculatorResult, CalculatorSection, CurrencyInput, ResultGrid, formatMoney, useCalculatorPersistence, useUrlStateDefaults, type CalculatorState } from '@/components/property/PropertyCalculatorFramework';
import { Container } from '@/components/layout/Container';
import { absoluteUrl, buildMeta, canonicalLink, jsonLd } from '@/lib/seo';

const canonicalPath = '/texas-property-tax-escrow-calculator';
const description = 'Estimate monthly Texas escrow for property taxes, homeowners insurance and HOA costs.';
const pageUrl = absoluteUrl(texasDefinedBrand, canonicalPath);
type EscrowState = { annualTax:number; annualInsurance:number; annualHoa:number; currentMonthlyEscrow:number };
const DEFAULTS: EscrowState & CalculatorState = { annualTax:7200, annualInsurance:3600, annualHoa:0, currentMonthlyEscrow:900 };
export const Route = createFileRoute('/texas-property-tax-escrow-calculator')({ head:()=>({ meta:buildMeta(texasDefinedBrand,{canonicalPath,title:'Texas Property Tax Escrow Calculator',description}), links:[canonicalLink(texasDefinedBrand,canonicalPath)], scripts:[jsonLd({'@context':'https://schema.org','@type':'WebApplication','@id':`${pageUrl}#calculator`,name:'Texas Property Tax Escrow Calculator',description,url:pageUrl,applicationCategory:'FinanceApplication',operatingSystem:'Any'})]}), component:EscrowCalculator });
function EscrowCalculator(){
 const initial=useUrlStateDefaults(DEFAULTS); const [state,setState]=useState<EscrowState>({annualTax:Number(initial.annualTax),annualInsurance:Number(initial.annualInsurance),annualHoa:Number(initial.annualHoa),currentMonthlyEscrow:Number(initial.currentMonthlyEscrow)});
 const update=useCallback(<K extends keyof EscrowState>(k:K,v:EscrowState[K])=>setState(s=>({...s,[k]:v})),[]);
 const r=useMemo(()=>{const yearly=Math.max(0,state.annualTax)+Math.max(0,state.annualInsurance)+Math.max(0,state.annualHoa);const monthly=yearly/12;return{yearly,monthly,difference:monthly-Math.max(0,state.currentMonthlyEscrow)}},[state]);
 const p=useCalculatorPersistence({storageKey:'texasdefined:property-tax-escrow-calculator',state,onRestore:(s)=>setState({annualTax:Number(s.annualTax),annualInsurance:Number(s.annualInsurance),annualHoa:Number(s.annualHoa),currentMonthlyEscrow:Number(s.currentMonthlyEscrow)})});
 return <Container className="pb-16 pt-12 sm:pb-24 sm:pt-16"><article className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="border-b border-border pb-4 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span className="mx-2">/</span><Link to="/property">Property</Link><span className="mx-2">/</span><Link to="/property-tax-calculators">Calculators</Link><span className="mx-2">/</span><span>Escrow</span></nav><header className="border-b border-border py-10"><p className="eyebrow text-primary">Property-tax calculator</p><h1 className="mt-3 font-display text-5xl sm:text-7xl">Texas property-tax escrow calculator</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Estimate the monthly amount needed for property taxes, homeowners insurance and HOA costs. Mortgage servicers may calculate required escrow differently.</p></header><CalculatorSection eyebrow="Inputs" title="Enter annual housing costs"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><CurrencyInput label="Annual property tax" value={state.annualTax} onChange={v=>update('annualTax',v)}/><CurrencyInput label="Annual homeowners insurance" value={state.annualInsurance} onChange={v=>update('annualInsurance',v)}/><CurrencyInput label="Annual HOA dues" value={state.annualHoa} onChange={v=>update('annualHoa',v)}/><CurrencyInput label="Current monthly escrow" value={state.currentMonthlyEscrow} onChange={v=>update('currentMonthlyEscrow',v)}/></div></CalculatorSection><section className="border-y border-border py-10"><ResultGrid><CalculatorResult label="Annual escrowed costs" value={formatMoney(r.yearly)}/><CalculatorResult label="Estimated monthly amount" value={formatMoney(r.monthly)}/><CalculatorResult label="Difference from current escrow" value={`${r.difference>=0?'+':''}${formatMoney(r.difference)}`}/></ResultGrid></section><div className="mt-8"><CalculatorActions onSave={p.save} onRestore={p.restore} onShare={p.share} onPrint={p.print} status={p.status}/></div><p className="mt-8 text-sm leading-6 text-muted-foreground">This planning estimate does not model servicer reserve cushions, escrow shortages, escrow advances or payment timing.</p></article></Container>;
}
