import { createFileRoute, Link } from '@tanstack/react-router';
import { Container } from '@/components/layout/Container';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { buildMeta, canonicalLink } from '@/lib/seo';

const description = 'A plain-English starting point for mortgage help, down-payment assistance, homebuyer classes, lender questions and the programs worth checking first.';
export const Route = createFileRoute('/texas-first-time-homebuyer-programs')({
  head: () => ({ meta: buildMeta(texasDefinedBrand, {
      canonicalPath: '/texas-first-time-homebuyer-programs',
      title: 'Texas First-Time Homebuyer Programs', description }),
    links: [canonicalLink(texasDefinedBrand, '/texas-first-time-homebuyer-programs')] }),
  component: Page,
});
function Page() { return <Container className="py-16 sm:py-24"><article className="prose prose-gray mx-auto max-w-4xl"><p className="eyebrow text-primary">Buying a Texas home</p><h1>Texas First-Time Homebuyer Programs</h1><p className="lead">{description}</p><h2>First, find your comfortable number</h2><p>Start with the full monthly cost—not just the mortgage. Add property taxes, homeowners insurance, mortgage insurance, HOA dues, utilities, maintenance and room for the unexpected.</p><div className="not-prose my-8 grid gap-4 sm:grid-cols-3"><Link className="rounded-lg border p-5 font-medium" to="/texas-home-affordability-calculator">See what feels affordable</Link><Link className="rounded-lg border p-5 font-medium" to="/texas-down-payment-assistance-calculator">Estimate possible assistance</Link><Link className="rounded-lg border p-5 font-medium" to="/texas-closing-cost-calculator">Plan for closing costs</Link></div><h2>What assistance can look like</h2><p>Help may come as a grant, a forgivable lien, a deferred loan, a second mortgage, a mortgage-credit certificate or a lender-specific offer. Compare the interest rate, repayment terms, cash needed at closing and what happens if you sell or refinance.</p><h2>Your homebuyer checklist</h2><ol><li>Review your credit reports and settle on a monthly budget you can live with.</li><li>Take an accepted homebuyer class early.</li><li>Check the current income, purchase-price, property and location limits.</li><li>Use an approved lender when a program requires one.</li><li>Ask for side-by-side written estimates with and without assistance.</li><li>Keep some cash in reserve after closing.</li></ol><h2>Good places to start</h2><ul><li><a href="https://welcomehome.tdhca.texas.gov/" rel="noreferrer">Texas Department of Housing and Community Affairs homebuyer programs</a></li><li><a href="https://www.tdhca.texas.gov/help-for-texans" rel="noreferrer">TDHCA Help for Texans</a></li><li><a href="https://www.hud.gov/states/texas" rel="noreferrer">HUD resources for Texas buyers</a></li></ul><aside className="not-prose mt-10 rounded-lg bg-muted p-5 text-sm text-muted-foreground">Programs, rates, funding and limits change. Confirm the details with the agency and participating lender before making a decision.</aside></article></Container>; }
