import { Link, createLazyFileRoute } from "@tanstack/react-router";
import { Container } from "@/components/layout/Container";

const officialCodeUrl = "https://statutes.capitol.texas.gov/Docs/ED/htm/ED.25.htm#25.082";
const historicalSourceUrl = "https://www.tsl.texas.gov/ref/abouttx/flagpledge.html";

export const Route = createLazyFileRoute("/texas-pledge")({ component: TexasPledgePage });

function TexasPledgePage() { return <main>
  <section className="border-b border-border bg-muted/30 py-14 sm:py-20"><Container>
    <nav aria-label="Breadcrumb" className="mb-8 text-sm text-muted-foreground"><Link to="/">Home</Link><span className="mx-2">/</span><Link to="/texas-symbols">Official Texas Symbols</Link><span className="mx-2">/</span><span className="text-foreground">Texas Pledge</span></nav>
    <p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Texas civic tradition</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[.98] sm:text-6xl lg:text-7xl">The Texas pledge</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Texas has its own pledge to the Texas flag. Here are the current words, the history behind them, and the places Texans are most likely to hear it.</p>
  </Container></section>
  <section className="py-14 sm:py-20"><Container><article className="max-w-4xl">
    <p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Current wording</p><h2 className="mt-3 font-display text-4xl">The pledge to the Texas flag</h2><blockquote className="mt-7 border-l-4 border-primary bg-muted/30 px-7 py-8 font-display text-2xl leading-10 sm:text-3xl">“Honor the Texas flag; I pledge allegiance to thee, Texas, one state under God, one and indivisible.”</blockquote><p className="mt-5 leading-7 text-muted-foreground">This is the wording in Texas Education Code §25.082. It is a pledge to the Texas flag, so it is separate from the U.S. Pledge of Allegiance.</p>
    <section className="mt-14"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">A short history</p><h2 className="mt-3 font-display text-4xl">The words did not always say “one state under God”</h2><p className="mt-5 leading-7 text-muted-foreground">The Texas pledge dates to 1933. Its earlier form ended “one and indivisible.” In 2007, the Legislature added “under God,” producing the wording Texans use today. That change matters because older programs, documents, recordings and recollections may preserve the earlier language.</p><p className="mt-5 leading-7 text-muted-foreground">The pledge reflects a Texas civic identity tied to the Lone Star Flag. It does not suggest that Texas is a separate nation; Texas is a state in the United States, and the Texas pledge is a state-level observance.</p></section>
    <section className="mt-14 border-y border-border py-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Where it is used</p><h2 className="mt-3 font-display text-4xl">Most Texans encounter it at school</h2><p className="mt-5 leading-7 text-muted-foreground">Texas law requires each public school day to provide a moment for students to recite the U.S. Pledge of Allegiance and the Texas pledge. A parent or guardian may submit a written request excusing a student from reciting either pledge. Schools also observe a minute of silence after the pledges.</p><p className="mt-5 leading-7 text-muted-foreground">Outside schools, the Texas pledge may be included at civic meetings, heritage programs, veterans events, flag ceremonies and other Texas-focused gatherings. Those uses are customary choices by organizers, not a rule that every event must follow.</p></section>
    <section className="mt-14"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Do not mix them up</p><h2 className="mt-3 font-display text-4xl">Pledge, state song, and national pledge</h2><div className="mt-7 grid gap-4 sm:grid-cols-3"><Card title="Texas pledge" text="A spoken pledge to the Texas flag, with school-day treatment in state law." link="/texas-pledge" /><Card title="U.S. Pledge" text="A separate pledge to the flag of the United States." /><Card title="Texas, Our Texas" text="The official state song, adopted in 1929 and used at selected civic and ceremonial programs." link="/texas-symbols/song" /></div></section>
    <section className="mt-14 rounded-sm border border-border bg-muted/30 p-7"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Sources of record</p><h2 className="mt-3 font-display text-3xl">Read the law and historical reference</h2><p className="mt-4 leading-7 text-muted-foreground">TexasDefined uses the current Education Code for the school-day requirement and the Texas State Library and Archives Commission for the pledge's historical reference.</p><div className="mt-5 flex flex-wrap gap-5"><a href={officialCodeUrl} target="_blank" rel="noreferrer" className="font-semibold text-primary">Texas Education Code §25.082 ↗</a><a href={historicalSourceUrl} target="_blank" rel="noreferrer" className="font-semibold text-primary">Texas State Library history ↗</a></div></section>
  </article></Container></section>
</main>; }
function Card({ title, text, link }: { title: string; text: string; link?: string }) { const body=<><h3 className="font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></>; return link ? <Link to={link as any} className="border border-border bg-background p-6 hover:border-primary">{body}</Link> : <div className="border border-border bg-background p-6">{body}</div>; }
