import { createFileRoute, Link } from '@tanstack/react-router';
import { Container } from '@/components/layout/Container';
import { texasDefinedBrand } from '@/brand/texasdefined';
import { buildMeta, canonicalLink } from '@/lib/seo';

const description = 'A practical starting point for Texas mortgage assistance, down-payment help, homebuyer education, lender questions, and official program verification.';
export const Route = createFileRoute('/texas-first-time-homebuyer-programs')({
  head: () => ({ meta: buildMeta(texasDefinedBrand, { title: 'Texas First-Time Homebuyer Programs', description }), links: [canonicalLink(texasDefinedBrand, '/texas-first-time-homebuyer-programs')] }),
  component: Page,
});
function Page() { return <Container className="py-16 sm:py-24"><article className="prose prose-gray mx-auto max-w-4xl"><p className="eyebrow text-primary">Buying a Texas home</p><h1>Texas First-Time Homebuyer Programs</h1><p className="lead">{description}</p><h2>Start with affordability</h2><p>Estimate the complete monthly payment before comparing assistance. Include principal, interest, property taxes, homeowners insurance, mortgage insurance, HOA dues, utilities, maintenance, and an emergency reserve.</p><div className="not-prose my-8 grid gap-4 sm:grid-cols-3"><Link className="rounded-lg border p-5 font-medium" to="/texas-home-affordability-calculator">Affordability calculator</Link><Link className="rounded-lg border p-5 font-medium" to="/texas-down-payment-assistance-calculator">Assistance calculator</Link><Link className="rounded-lg border p-5 font-medium" to="/texas-closing-cost-calculator">Closing-cost calculator</Link></div><h2>How assistance may be structured</h2><p>Programs may use grants, forgivable liens, deferred loans, repayable second mortgages, mortgage-credit certificates, or lender-specific mortgage products. Compare the interest rate, repayment terms, cash to close, second-lien conditions, and what happens after a sale or refinance.</p><h2>Application checklist</h2><ol><li>Review credit reports and establish a sustainable budget.</li><li>Complete accepted homebuyer education early.</li><li>Check current income, purchase-price, property, and geographic limits.</li><li>Use an approved participating lender when the program requires one.</li><li>Request side-by-side written estimates with and without assistance.</li><li>Keep cash reserves after closing.</li></ol><h2>Official starting points</h2><ul><li><a href="https://welcomehome.tdhca.texas.gov/" rel="noreferrer">Texas Department of Housing and Community Affairs homebuyer programs</a></li><li><a href="https://www.tdhca.texas.gov/help-for-texans" rel="noreferrer">TDHCA Help for Texans directory</a></li><li><a href="https://www.hud.gov/states/texas" rel="noreferrer">HUD Texas resources</a></li></ul><aside className="not-prose mt-10 rounded-lg bg-muted p-5 text-sm text-muted-foreground">Program availability, rates, funding, limits, and terms change. Verify every option with the official agency and participating lender.</aside></article></Container>; }
