import { createLazyFileRoute, Link } from '@tanstack/react-router';
import { CalculatorPage } from '@/components/calculators/CalculatorPage';
import { RentVsBuyCalculator } from '@/components/calculators/TexasPlanningCalculators';

const description = 'Compare renting and buying in Texas across a chosen time horizon, including the ownership costs and flexibility tradeoffs that a simple monthly rent-versus-mortgage comparison misses.';

const faqs = [
  { question: 'Is buying always better if the mortgage payment is close to the rent?', answer: 'No. Buying also involves transaction costs, taxes, insurance, maintenance and less flexibility. The useful comparison includes the expected time in the home and the complete ownership budget.' },
  { question: 'Why does the time horizon matter?', answer: 'Buying has upfront and selling costs that are spread across the years you own the property. A short expected stay can produce a different result from a long holding period even when the monthly payments are similar.' },
  { question: 'Should I assume a home will appreciate?', answer: 'Use more than one scenario. Appreciation is uncertain, so compare a conservative assumption with a higher-growth case rather than making the decision depend on one future market outcome.' },
  { question: 'What costs should renters include?', answer: 'Include rent, renters insurance, recurring fees, utilities that are not included and likely increases. Also value the flexibility of moving without selling a property when that matters to the household.' },
  { question: 'What does this calculator still leave out?', answer: 'It does not model income-tax effects, mortgage insurance, special-district charges, tax-exemption caps, investment returns or address-specific insurance changes. Treat the result as a scenario comparison and replace the defaults with quotes and local tax information before making a housing decision.' },
];

export const Route = createLazyFileRoute('/texas-rent-vs-buy-calculator')({ component: TexasRentVsBuyCalculatorPage });

function TexasRentVsBuyCalculatorPage() {
  return <CalculatorPage eyebrow="One of the big decisions" title="Texas rent vs buy calculator" description={description}>
    <RentVsBuyCalculator />
    <section className="mt-14 border-t border-border pt-10" aria-labelledby="rent-buy-heading"><p className="eyebrow text-primary">Compare the same years</p><h2 id="rent-buy-heading" className="mt-3 font-display text-3xl">Rent and mortgage are not the only two numbers</h2><div className="mt-5 max-w-3xl space-y-4 text-base leading-7 text-muted-foreground"><p>The calculator now amortizes a fixed-rate mortgage month by month instead of treating every owner payment as a simple expense. It tracks principal reduction, interest, the remaining loan balance, property taxes, homeowners insurance, maintenance, HOA dues, buyer closing costs and selling costs, then offsets those owner cash outflows with estimated sale equity at the end of the comparison period.</p><p>The rental side compounds the rent-growth assumption across the same months and includes renters insurance. Run a shorter and longer holding period and change the appreciation assumption rather than letting one optimistic future-home-value number decide the result.</p><p>Texas property taxes are local, not a single statewide rate. The rate field is a scenario input, and the model does not try to predict exemptions, appraisal caps or special-district charges for a specific address. Use the county appraisal district and taxing-unit information for the property you are actually considering.</p></div></section>
    <section className="mt-12 border-t border-border pt-10" aria-labelledby="rent-buy-links-heading"><p className="eyebrow text-primary">Build both sides of the comparison</p><h2 id="rent-buy-links-heading" className="mt-3 font-display text-3xl">Use the Texas home-buying assumptions that actually apply</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Link to="/article/renting-vs-buying-in-texas" className="border border-border p-5 hover:border-primary"><strong className="font-display text-xl">Renting vs. buying guide</strong><span className="mt-2 block text-sm leading-6 text-muted-foreground">Compare flexibility, equity, taxes, insurance, maintenance and break-even considerations.</span></Link>
      <Link to="/texas-homeownership-cost-calculator" className="border border-border p-5 hover:border-primary"><strong className="font-display text-xl">Full ownership cost</strong><span className="mt-2 block text-sm leading-6 text-muted-foreground">Build the ownership side from mortgage, taxes, insurance, utilities and maintenance.</span></Link>
      <Link to="/texas-closing-cost-calculator" className="border border-border p-5 hover:border-primary"><strong className="font-display text-xl">Closing costs</strong><span className="mt-2 block text-sm leading-6 text-muted-foreground">Include transaction costs instead of comparing rent with mortgage payment alone.</span></Link>
      <Link to="/texas-home-affordability-calculator" className="border border-border p-5 hover:border-primary"><strong className="font-display text-xl">Home affordability</strong><span className="mt-2 block text-sm leading-6 text-muted-foreground">Test whether the buying scenario fits the household income and debt budget.</span></Link>
    </div></section>
    <section className="mt-12 border-t border-border pt-10" aria-labelledby="rent-buy-sources-heading"><p className="eyebrow text-primary">Check the assumptions</p><h2 id="rent-buy-sources-heading" className="mt-3 font-display text-3xl">Use official mortgage and Texas property-tax guidance</h2><div className="mt-5 max-w-3xl space-y-3 text-base leading-7 text-muted-foreground"><p>The Consumer Financial Protection Bureau explains how fixed-rate mortgage amortization shifts each payment between interest and principal over time. The Texas Comptroller explains that Texas property taxes are locally assessed and administered, and that exemptions can reduce taxable value for qualifying owners.</p><p><a href="https://www.consumerfinance.gov/ask-cfpb/how-does-paying-down-a-mortgage-work-en-1943/" target="_blank" rel="noreferrer" className="font-semibold text-primary underline-offset-4 hover:underline">CFPB: How paying down a mortgage works</a></p><p><a href="https://comptroller.texas.gov/taxes/property-tax/exemptions/" target="_blank" rel="noreferrer" className="font-semibold text-primary underline-offset-4 hover:underline">Texas Comptroller: Property-tax exemptions</a></p></div></section>
    <section className="mt-12 border-t border-border pt-10" aria-labelledby="rent-buy-faq-heading"><p className="eyebrow text-primary">Common questions</p><h2 id="rent-buy-faq-heading" className="mt-3 font-display text-3xl">Texas rent vs buy calculator FAQ</h2><div className="mt-6 divide-y divide-border border-y border-border">{faqs.map((faq) => <div key={faq.question} className="py-6"><h3 className="font-display text-2xl">{faq.question}</h3><p className="mt-3 max-w-3xl text-base leading-7 text-muted-foreground">{faq.answer}</p></div>)}</div></section>
  </CalculatorPage>;
}
