import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import {
  HUNTING_AUTHORITY_TOPICS,
  HUNTING_HUB_GROUPS,
  HUNTING_OFFICIAL_SOURCES,
  HUNTING_REGULATION_FRESHNESS,
  type HuntingAuthorityLink,
  type HuntingAuthorityTopic,
} from "@/data/hunting/authority";

function ResourceLink({ link }: { link: HuntingAuthorityLink }) {
  if (link.external) return <a href={link.href} target="_blank" rel="noreferrer" className="font-semibold text-primary underline decoration-primary/40 underline-offset-4 hover:decoration-primary">{link.label} ↗</a>;
  return <Link to={link.href} className="font-semibold text-primary underline decoration-primary/40 underline-offset-4 hover:decoration-primary">{link.label}</Link>;
}

function FreshnessPanel() {
  return <section className="border-y border-border bg-surface py-8"><Container><div className="grid gap-5 lg:grid-cols-[15rem_1fr] lg:items-start"><div><p className="eyebrow text-primary">Regulatory freshness</p><p className="mt-2 font-display text-2xl">TPWD {HUNTING_REGULATION_FRESHNESS.seasonYear}</p><p className="mt-2 text-xs uppercase tracking-[0.16em] text-muted-foreground">Verified {HUNTING_REGULATION_FRESHNESS.lastVerifiedLabel}</p></div><div><p className="max-w-4xl text-sm leading-7 text-muted-foreground">{HUNTING_REGULATION_FRESHNESS.disclaimer}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-3 text-sm"><ResourceLink link={HUNTING_OFFICIAL_SOURCES.regulations} /><ResourceLink link={HUNTING_OFFICIAL_SOURCES.seasonDates} /></div></div></div></Container></section>;
}

export function HuntingAuthorityHub() {
  return <main>
    <section className="border-b border-border bg-muted/30 py-14 md:py-20"><Container><nav aria-label="Breadcrumb" className="mb-8 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span aria-hidden="true" className="mx-2">/</span><span aria-current="page">Hunting</span></nav><p className="eyebrow text-primary">Texas hunting authority</p><h1 className="mt-3 max-w-5xl font-display text-5xl leading-none md:text-7xl">Hunting Texas: licenses, public land, species and season planning</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Start with access and legal planning, then connect the hunt to wildlife habitat, counties, camping, fishing, parks and trip planning. Current-rule questions route back to Texas Parks and Wildlife Department instead of treating an independent publication as the legal authority.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/hunting/public-hunting" className="inline-flex items-center bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Find public hunting →</Link><Link to="/hunting/texas-hunting-license" className="inline-flex items-center border border-border px-5 py-3 text-sm font-semibold hover:border-primary hover:text-primary">Hunting licenses →</Link><Link to="/explore/outdoors" className="inline-flex items-center border border-border px-5 py-3 text-sm font-semibold hover:border-primary hover:text-primary">Public lands & outdoors →</Link><Link to="/explore/trip-planner" className="inline-flex items-center border border-border px-5 py-3 text-sm font-semibold hover:border-primary hover:text-primary">Build a trip →</Link></div></Container></section>
    <FreshnessPanel />
    <section className="py-12 md:py-16"><Container><div className="grid gap-12">{HUNTING_HUB_GROUPS.map((group) => <section key={group.title}><div className="grid gap-4 border-b border-border pb-5 lg:grid-cols-[1fr_2fr] lg:items-end"><h2 className="font-display text-3xl md:text-4xl">{group.title}</h2><p className="max-w-2xl text-sm leading-7 text-muted-foreground">{group.description}</p></div><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{group.slugs.map((slug) => { const topic = HUNTING_AUTHORITY_TOPICS[slug]; return <Link key={slug} to={`/hunting/${slug}`} className="group border border-border p-5 transition hover:border-primary"><p className="eyebrow text-primary">{topic.eyebrow}</p><h3 className="mt-2 font-display text-2xl leading-tight group-hover:text-primary">{topic.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{topic.description}</p><span className="mt-4 inline-block text-sm font-semibold text-primary">Open guide →</span></Link>; })}</div></section>)}</div></Container></section>
    <section className="border-y border-border bg-muted/30 py-12"><Container><div className="grid gap-8 lg:grid-cols-[1fr_2fr]"><div><p className="eyebrow text-primary">Connected Texas discovery</p><h2 className="mt-3 font-display text-4xl">A hunt is also a place-based trip</h2></div><div className="grid gap-5 sm:grid-cols-2"><p className="text-sm leading-7 text-muted-foreground">Public hunting works best when access records connect to counties, regions, wildlife habitat and nearby destinations. Use TexasDefined's outdoor and wildlife systems to understand the place around the hunt.</p><p className="text-sm leading-7 text-muted-foreground">Camping, fishing, parks and trip-planning links make it easier to turn a permit or drawn hunt into a realistic itinerary without weakening the distinction between travel guidance and legal hunting rules.</p></div><div className="lg:col-start-2 flex flex-wrap gap-x-6 gap-y-3 text-sm"><Link to="/explore/outdoors" className="font-semibold text-primary underline decoration-primary/40 underline-offset-4">Public lands & outdoors</Link><Link to="/explore/wildlife" className="font-semibold text-primary underline decoration-primary/40 underline-offset-4">Wildlife</Link><Link to="/best-places-to-go-camping-in-texas" className="font-semibold text-primary underline decoration-primary/40 underline-offset-4">Camping</Link><Link to="/fishing" className="font-semibold text-primary underline decoration-primary/40 underline-offset-4">Fishing</Link><Link to="/explore/state-parks" className="font-semibold text-primary underline decoration-primary/40 underline-offset-4">State parks</Link><Link to="/browse/counties" className="font-semibold text-primary underline decoration-primary/40 underline-offset-4">Counties</Link></div></div></Container></section>
  </main>;
}

export function HuntingAuthorityTopicPage({ topic }: { topic: HuntingAuthorityTopic }) {
  const officialSources = [...new Map(topic.sections.flatMap((section) => section.links ?? []).filter((link) => link.external).map((link) => [link.href, link] as const)).values()];
  return <main>
    <section className="border-b border-border bg-muted/30 py-14 md:py-20"><Container><nav aria-label="Breadcrumb" className="mb-8 text-xs uppercase tracking-[0.14em] text-muted-foreground"><Link to="/">Front page</Link><span aria-hidden="true" className="mx-2">/</span><Link to="/hunting">Hunting</Link><span aria-hidden="true" className="mx-2">/</span><span aria-current="page">{topic.title}</span></nav><p className="eyebrow text-primary">{topic.eyebrow}</p><h1 className="mt-3 max-w-5xl font-display text-5xl leading-none md:text-7xl">{topic.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{topic.description}</p><p className="mt-5 text-xs uppercase tracking-[0.18em] text-muted-foreground">TPWD season source {HUNTING_REGULATION_FRESHNESS.seasonYear} · verified {HUNTING_REGULATION_FRESHNESS.lastVerifiedLabel}</p></Container></section>
    <section className="border-b border-border py-8"><Container><div className="max-w-4xl border-l-2 border-primary pl-5"><p className="eyebrow text-primary">Quick answer</p><p className="mt-3 text-lg leading-8">{topic.quickAnswer}</p></div></Container></section>
    <FreshnessPanel />
    <section className="py-12 md:py-16"><Container><div className="max-w-4xl divide-y divide-border">{topic.sections.map((section, index) => <section key={section.heading} className="py-8 first:pt-0"><p className="eyebrow text-muted-foreground">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-2 font-display text-3xl md:text-4xl">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-4 leading-8 text-muted-foreground">{paragraph}</p>)}{section.links?.length ? <div className="mt-5 flex flex-wrap gap-x-6 gap-y-3 text-sm">{section.links.map((link) => <ResourceLink key={`${link.href}-${link.label}`} link={link} />)}</div> : null}</section>)}</div></Container></section>
    <section className="border-t border-border bg-surface py-12" aria-labelledby="hunting-faq-heading"><Container><div className="max-w-4xl"><p className="eyebrow text-primary">Quick answers</p><h2 id="hunting-faq-heading" className="mt-2 font-display text-3xl md:text-4xl">Frequently asked questions</h2><div className="mt-6 divide-y divide-border border-y border-border">{topic.faq.map((item) => <details key={item.question} className="group py-5"><summary className="cursor-pointer list-none pr-8 font-display text-xl marker:hidden">{item.question}<span className="float-right text-primary group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">{item.answer}</p></details>)}</div></div></Container></section>
    {officialSources.length ? <section className="border-t border-border py-10"><Container><div className="grid max-w-4xl gap-6 lg:grid-cols-[14rem_1fr]"><div><p className="eyebrow text-primary">Verify with TPWD</p><h2 className="mt-2 font-display text-3xl">Current official sources</h2></div><div><p className="text-sm leading-7 text-muted-foreground">TexasDefined explains how the pieces fit together. Texas Parks and Wildlife Department remains the source to verify current licenses, seasons, limits, methods, tagging, reporting and public-hunt access.</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-3 text-sm">{officialSources.map((link) => <ResourceLink key={`source-${link.href}`} link={link} />)}</div></div></div></Container></section> : null}
    <section className="border-t border-border bg-muted/30 py-10"><Container><h2 className="font-display text-3xl">Related Texas guides</h2><div className="mt-5 flex flex-wrap gap-x-7 gap-y-3 text-sm"><ResourceLink link={{ label: "Texas hunting hub", href: "/hunting" }} />{topic.related.map((link) => <ResourceLink key={`${link.href}-${link.label}`} link={link} />)}</div></Container></section>
  </main>;
}
