import { Container } from "@/components/layout/Container";
import { GearUpNetworkCallout } from "@/components/gaming/GearUpNetworkCallout";
import { TEXAS_COLLEGE_ESPORTS, TEXAS_GAME_COMPANIES, TEXAS_GAMING_EVENTS, TEXAS_GAMING_PAGES, TEXAS_GAMING_SLUGS, TEXAS_GAMING_VERIFIED_AT, type GamingPage } from "@/data/texas-gaming-authority";

export function TexasGamingHub() {
  const pages = TEXAS_GAMING_SLUGS.map((slug) => TEXAS_GAMING_PAGES[slug]).filter(Boolean);
  return <main>
    <section className="border-b border-border bg-muted/30 py-16 sm:py-24"><Container>
      <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><a href="/" className="hover:text-foreground">Home</a><span className="mx-2">/</span><span className="text-foreground">Gaming & Esports</span></nav>
      <p className="mt-9 text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas technology · entertainment · competition</p>
      <h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.98] sm:text-6xl lg:text-7xl">Gaming & Esports in Texas</h1>
      <p className="mt-6 max-w-4xl text-lg leading-8 text-muted-foreground">A statewide guide to game development, studios, esports, college programs, careers, recurring events and the Internet infrastructure behind online play. The editorial section stands on its own; commercial tools appear only where they solve a relevant reader problem.</p>
      <p className="mt-6 text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Sources reviewed · {TEXAS_GAMING_VERIFIED_AT}</p>
    </Container></section>
    <section className="border-b border-border py-14 sm:py-20"><Container>
      <div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">The Texas gaming knowledge graph</p><h2 className="mt-3 font-display text-4xl">Start with the question you are trying to answer</h2><p className="mt-4 text-base leading-8 text-muted-foreground">Studio research, esports travel, college-program research and latency troubleshooting need different evidence. These guides connect where the topics genuinely overlap without treating every technology company, venue or data center as the same industry.</p></div>
      <div className="mt-9 grid gap-px border border-border bg-border md:grid-cols-2 xl:grid-cols-3">
        {pages.map((page) => <a key={page.slug} href={`/gaming/${page.slug}`} className="group bg-background p-6 transition-colors hover:bg-muted/30"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">{page.eyebrow}</p><h2 className="mt-2 font-display text-2xl leading-tight group-hover:text-primary">{page.h1}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{page.description}</p><span className="mt-5 block text-sm font-semibold">Open guide →</span></a>)}
      </div>
    </Container></section>
    <section className="border-b border-border bg-surface py-14 sm:py-20"><Container>
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">How the pieces connect</p><h2 className="mt-3 max-w-4xl font-display text-4xl">Texas has several gaming ecosystems, not one</h2>
      <div className="mt-8 grid gap-px border border-border bg-border lg:grid-cols-3">
        <Bridge title="Studios & careers" body="Austin/Central Texas and Dallas–Fort Worth anchor the verified studio directory, while career pages separate durable job families from fast-changing openings." href="/gaming/video-game-industry" label="Texas video game industry" />
        <Bridge title="Esports & events" body="Frisco, Arlington, Houston and university programs create a separate competitive-gaming layer with venues, tournaments and travel needs." href="/gaming/esports" label="Texas esports" />
        <Bridge title="Networks & latency" body="Dallas interconnection, ISP routing, server location, packet loss and jitter help explain online-play performance without inventing guaranteed ping numbers." href="/gaming/why-dallas-matters-online-gaming" label="Why Dallas matters" />
      </div>
      <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold"><a className="text-primary" href="/texas-industries">Texas industries →</a><a className="text-primary" href="/events">Texas events →</a><a className="text-primary" href="/browse/cities">Texas cities →</a><a className="text-primary" href="/browse/counties">Texas counties →</a></div>
    </Container></section>
    <section className="py-14 sm:py-20"><Container><div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Method & sourcing</p><h2 className="mt-3 font-display text-4xl">Current status beats a bigger unverified list</h2><p className="mt-5 text-base leading-8 text-muted-foreground">TexasDefined uses state agencies, company sites, universities, venue operators and technical infrastructure providers as primary sources. A historical studio does not automatically appear as a current employer; a student club is not called varsity unless the school does; and a data center is not treated as proof that a particular game runs servers there.</p><p className="mt-4 text-base leading-8 text-muted-foreground">The section deliberately avoids generic gamer imagery when a rights-cleared, story-specific visual is not available. No image is better than an unrelated RGB-computer filler image.</p></div></Container></section>
  </main>;
}

export function TexasGamingAuthorityPage({ page }: { page: GamingPage }) {
  const related = page.related.map((slug) => TEXAS_GAMING_PAGES[slug]).filter(Boolean);
  const showGearUp = page.slug === "why-dallas-matters-online-gaming" || page.slug === "online-gaming-latency-guide";
  return <main>
    <section className="border-b border-border bg-muted/30 py-14 sm:py-20"><Container>
      <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><a href="/" className="hover:text-foreground">Home</a><span className="mx-2">/</span><a href="/gaming" className="hover:text-foreground">Gaming & Esports</a><span className="mx-2">/</span><span className="text-foreground">{page.h1}</span></nav>
      <p className="mt-9 text-sm font-semibold uppercase tracking-[0.18em] text-primary">{page.eyebrow}</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.98] sm:text-6xl">{page.h1}</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-muted-foreground">{page.dek}</p><p className="mt-6 text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Sources reviewed · {TEXAS_GAMING_VERIFIED_AT}</p>
    </Container></section>
    <section className="border-b border-border py-14 sm:py-20"><Container><div className="grid gap-12 lg:grid-cols-[minmax(0,1fr)_20rem]">
      <article>{page.sections.map((section, index) => <section key={section.title} className={index ? "mt-12 border-t border-border pt-10" : ""}><h2 className="font-display text-4xl">{section.title}</h2><div className="mt-5 space-y-4 text-base leading-8 text-muted-foreground">{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>{section.bullets?.length ? <ul className="mt-6 grid gap-3 sm:grid-cols-2">{section.bullets.map((item) => <li key={item} className="border-t border-border pt-3 text-sm font-semibold">{item}</li>)}</ul> : null}</section>)}
        {page.slug === "video-game-companies" ? <CompanyDirectory /> : null}
        {page.slug === "college-esports" ? <CollegeDirectory /> : null}
        {page.slug === "gaming-events" ? <EventDirectory /> : null}
        {page.slug === "why-dallas-matters-online-gaming" ? <NetworkPath /> : null}
        {page.faq?.length ? <Faq items={page.faq} /> : null}
        {showGearUp ? <GearUpNetworkCallout placement={page.slug === "why-dallas-matters-online-gaming" ? "gaming-dallas-routing" : "gaming-latency-troubleshooting"} /> : null}
        {page.slug === "esports-stadium-arlington" ? <div className="mt-12" data-stay-nearby-slot data-stay-nearby-context="gaming-esports-stadium-arlington" /> : null}
      </article>
      <aside><div className="sticky top-24 border-t border-border pt-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Sources & official links</p><ul className="mt-4 space-y-4">{page.sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer" className="text-sm font-semibold underline decoration-primary/30 underline-offset-4 hover:text-primary">{source.label} ↗</a>{source.note ? <p className="mt-1 text-xs leading-5 text-muted-foreground">{source.note}</p> : null}</li>)}</ul></div></aside>
    </div></Container></section>
    <section className="py-14 sm:py-20"><Container><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Related Texas gaming guides</p><div className="mt-6 grid gap-px border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{related.map((item) => <a key={item.slug} href={`/gaming/${item.slug}`} className="group bg-background p-5"><strong className="font-display text-2xl group-hover:text-primary">{item.h1}</strong><span className="mt-3 block text-sm leading-6 text-muted-foreground">{item.description}</span></a>)}</div><a href="/gaming" className="mt-7 inline-block text-sm font-semibold text-primary">Back to Gaming & Esports in Texas →</a></Container></section>
  </main>;
}

function CompanyDirectory() { return <section className="mt-12 border-t border-border pt-10"><h2 className="font-display text-4xl">Verified Texas gaming companies</h2><div className="mt-6 divide-y divide-border border-y border-border">{TEXAS_GAME_COMPANIES.map((company) => <article key={company.name} className="py-6"><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-display text-2xl">{company.name}</h3><span className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">{company.city}</span></div><p className="mt-2 text-sm leading-7 text-muted-foreground"><strong className="text-foreground">{company.focus}.</strong> {company.status}</p><p className="mt-2 text-sm text-muted-foreground">Notable context: {company.notable}</p><div className="mt-3 flex flex-wrap gap-x-5 text-sm font-semibold"><a href={company.companyUrl} target="_blank" rel="noopener noreferrer" className="text-primary">Official site ↗</a><a href={company.careersUrl} target="_blank" rel="noopener noreferrer" className="text-primary">Careers ↗</a><a href={company.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-primary">Verification source ↗</a></div></article>)}</div></section>; }
function CollegeDirectory() { return <section className="mt-12 border-t border-border pt-10"><h2 className="font-display text-4xl">Verified college programs & facilities</h2><div className="mt-6 divide-y divide-border border-y border-border">{TEXAS_COLLEGE_ESPORTS.map((program) => <article key={program.school} className="py-6"><h3 className="font-display text-2xl">{program.school}</h3><p className="mt-1 text-xs font-semibold uppercase tracking-[0.12em] text-primary">{program.city} · {program.programType}</p><p className="mt-3 text-sm leading-7 text-muted-foreground">{program.games}</p><p className="mt-2 text-sm leading-7 text-muted-foreground">{program.facility}</p><a href={program.url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-sm font-semibold text-primary">Official program ↗</a></article>)}</div></section>; }
function EventDirectory() { return <section className="mt-12 border-t border-border pt-10"><h2 className="font-display text-4xl">Recurring events and current status</h2><div className="mt-6 divide-y divide-border border-y border-border">{TEXAS_GAMING_EVENTS.map((event) => <article key={event.name} className="py-6"><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-display text-2xl">{event.name}</h3><span className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">{event.city}</span></div><p className="mt-2 text-sm font-semibold">{event.status}</p><p className="mt-2 text-sm leading-7 text-muted-foreground">{event.summary}</p><p className="mt-2 text-sm leading-7 text-muted-foreground">{event.timing}</p><div className="mt-3 flex flex-wrap gap-x-5 text-sm font-semibold"><a href={event.href} target={event.href.startsWith("http") ? "_blank" : undefined} rel={event.href.startsWith("http") ? "noopener noreferrer" : undefined} className="text-primary">{event.href.startsWith("http") ? "Official event ↗" : "TexasDefined event guide →"}</a><a href={event.internalHref} className="text-primary">Texas event coverage →</a></div></article>)}</div></section>; }
function NetworkPath() { return <section className="mt-12 border-t border-border pt-10"><h2 className="font-display text-4xl">A simplified online-game path</h2><ol className="mt-6 grid gap-px border border-border bg-border sm:grid-cols-2"><li className="bg-background p-4"><strong>1. Player device</strong><span className="mt-1 block text-sm text-muted-foreground">PC, console or mobile device.</span></li><li className="bg-background p-4"><strong>2. Home network</strong><span className="mt-1 block text-sm text-muted-foreground">Ethernet or Wi-Fi to the modem/router.</span></li><li className="bg-background p-4"><strong>3. ISP</strong><span className="mt-1 block text-sm text-muted-foreground">The access provider and its regional network.</span></li><li className="bg-background p-4"><strong>4. Interconnection</strong><span className="mt-1 block text-sm text-muted-foreground">Peering or transit between networks.</span></li><li className="bg-background p-4 sm:col-span-2"><strong>5. Game hosting network and server</strong><span className="mt-1 block text-sm text-muted-foreground">The destination chosen by the game or player. Every step can influence the observed result.</span></li></ol></section>; }
function Faq({ items }: { items: readonly { question: string; answer: string }[] }) { return <section className="mt-12 border-t border-border pt-10"><h2 className="font-display text-4xl">Common questions</h2><div className="mt-5 divide-y divide-border border-y border-border">{items.map((item) => <details key={item.question} className="py-5"><summary className="cursor-pointer font-display text-xl">{item.question}</summary><p className="mt-3 text-sm leading-7 text-muted-foreground">{item.answer}</p></details>)}</div></section>; }
function Bridge({ title, body, href, label }: { title: string; body: string; href: string; label: string }) { return <article className="bg-background p-6"><h3 className="font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{body}</p><a href={href} className="mt-5 inline-block text-sm font-semibold text-primary">{label} →</a></article>; }
