import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import * as XLSX from "npm:xlsx@0.18.5";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";

type UnitType = "county" | "city" | "school-district" | "special-district";
type RawRecord = { type:UnitType; name:string; baseSlug:string; countySlug:string; officialId:string; officialBase:string; unavailable:boolean; totalRate:number|null; moRate:number|null; debtRate:number|null; levy:number|null; sourceUrl:string };
const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const FILES:Record<UnitType,string>={"school-district":"school-district-rates-levies.xlsx",city:"city-rates-levies.xlsx",county:"county-rates-levies.xlsx","special-district":"special-district-rates-levies.xlsx"};
const TEA_2025_MINIMUM_MCR=0.5689;
const clean=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim();
const slugify=(v:string)=>clean(v).toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const header=(v:unknown)=>clean(v).toUpperCase();
function numberValue(v:unknown):number|null{const n=typeof v==="number"?v:Number(String(v??"").replace(/[$,%]/g,""));return Number.isFinite(n)?n:null}
const hasSingleStar=(v:string)=>/\*\s*$/.test(clean(v))&&!/\*\*\s*$/.test(clean(v));
const stripTrailingStars=(v:string)=>clean(v).replace(/\s*\*+\s*$/,"").trim();
const stripCounty=(v:string)=>clean(v).replace(/\s+County$/i,"").trim();
function cleanCounty(v:string){return stripCounty(clean(v).replace(/\s*\*+\s*(?=County$|$)/i," "))}
function sumKnown(vs:Array<number|null>){const f=vs.filter((v):v is number=>v!=null);return f.length?f.reduce((a,b)=>a+b,0):null}
const uniqueNumbers=(vs:Array<number|null>)=>[...new Set(vs.filter((v):v is number=>v!=null).map(v=>Number(v.toFixed(8))))].sort((a,b)=>a-b);
const uniqueStrings=(vs:string[])=>[...new Set(vs.filter(Boolean))].sort();
function officialBase(id:string){const p=id.split("-").filter(Boolean);return p.slice(0,Math.min(3,p.length)).join("-")||id}
function locateRows(bytes:Uint8Array){const wb=XLSX.read(bytes,{type:"array",cellDates:false});for(const sn of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:null,raw:true}) as unknown[][];for(let i=0;i<Math.min(rows.length,30);i++){const hs=rows[i].map(header);if(hs.includes("TAXING UNIT ID")&&(hs.includes("TOTAL TAX RATE")||hs.includes("TOTAL COUNTY TAX RATE")))return{headers:hs,rows:rows.slice(i+1)}}}throw new Error("Could not locate Detail header row")}
function cellMap(headers:string[],row:unknown[]){const m=new Map<string,unknown>();headers.forEach((h,i)=>{if(h)m.set(h,row[i])});return m}
function pick(m:Map<string,unknown>,ks:string[]){for(const k of ks)if(m.has(k))return m.get(k);return null}
function parseWorkbook(type:UnitType,sourceUrl:string,bytes:Uint8Array):RawRecord[]{const{headers,rows}=locateRows(bytes);const out:RawRecord[]=[];for(const row of rows){const m=cellMap(headers,row);const countyRaw=clean(pick(m,["COUNTY NAME","COUNTY"]));const countyName=cleanCounty(countyRaw);const oid=clean(pick(m,["TAXING UNIT ID"]));if(!countyName||!oid)continue;const unitRaw=type==="county"?countyRaw:clean(pick(m,["TAXING UNIT NAME","TU NAME","DISTRICT NAME","CITY NAME"]));const unavailable=hasSingleStar(unitRaw);const name=type==="county"?`${countyName} County`:stripTrailingStars(unitRaw);if(!name)continue;const totalRate=numberValue(pick(m,type==="county"?["TOTAL COUNTY TAX RATE","TOTAL TAX RATE"]:["TOTAL TAX RATE"]));const moRate=type==="county"?sumKnown([numberValue(pick(m,["GF M&O TAX RATE"])),numberValue(pick(m,["R&B M&O TAX RATE"])),numberValue(pick(m,["FMFC M&O RATE"]))]):numberValue(pick(m,["M&O RATE","M&O TAX RATE"]));const debtRate=type==="county"?sumKnown([numberValue(pick(m,["GF I&S TAX RATE"])),numberValue(pick(m,["R&B I&S TAX RATE"])),numberValue(pick(m,["FMFC I&S RATE"]))]):numberValue(pick(m,["I&S RATE","I&S TAX RATE"]));out.push({type,name,baseSlug:slugify(name),countySlug:slugify(countyName),officialId:oid,officialBase:officialBase(oid),unavailable,totalRate,moRate,debtRate,levy:numberValue(pick(m,["CALCULATED LEVY","LEVY"])),sourceUrl})}return out}
function normalizeYear(raw:RawRecord[],year:number){const groups=new Map<string,RawRecord[]>();for(const r of raw){const k=`${r.type}:${r.officialBase}`;const g=groups.get(k)??[];g.push(r);groups.set(k,g)}const units:any[]=[];for(const group of groups.values()){const usable=group.filter(r=>!r.unavailable);const rateUnavailable=usable.length===0;const totals=uniqueNumbers(usable.map(r=>r.totalRate));const mos=uniqueNumbers(usable.map(r=>r.moRate));const debts=uniqueNumbers(usable.map(r=>r.debtRate));const names=uniqueStrings(group.map(r=>r.name));const name=names.sort((a,b)=>a.length-b.length||a.localeCompare(b))[0];const levies=usable.map(r=>r.levy).filter((v):v is number=>v!=null);units.push({year,type:group[0].type,name,baseSlug:slugify(name),officialBase:group[0].officialBase,county_slugs:uniqueStrings(group.map(r=>r.countySlug)),total_rate:rateUnavailable?null:(totals.length===1?totals[0]:null),maintenance_operations_rate:rateUnavailable?null:(mos.length===1?mos[0]:null),debt_service_rate:rateUnavailable?null:(debts.length===1?debts[0]:null),levy:rateUnavailable?null:(levies.length?levies.reduce((a,b)=>a+b,0):null),source_url:group[0].sourceUrl,source_status:rateUnavailable?"not-reported":(usable.length<group.length?"partial-reporting":"reported-final"),variable_rate:!rateUnavailable&&totals.length>1,rate_variants:rateUnavailable?[]:totals,official_taxing_unit_ids:uniqueStrings(group.map(r=>r.officialId)),split_across_cads:uniqueStrings(group.map(r=>r.countySlug)).length>1,rate_unavailable:rateUnavailable,imported_at:new Date().toISOString()})}const collisions=new Map<string,any[]>();for(const u of units){const k=`${u.type}:${u.baseSlug}`;const g=collisions.get(k)??[];g.push(u);collisions.set(k,g)}for(const u of units){const coll=collisions.get(`${u.type}:${u.baseSlug}`)??[];u.slug=coll.length>1?`${u.baseSlug}-${slugify(u.officialBase)}`:u.baseSlug;u.id=`${year}:${u.type}:${u.slug}`;delete u.baseSlug;delete u.officialBase;if(year===2025&&u.type==="school-district"&&!u.rate_unavailable&&u.maintenance_operations_rate!=null&&u.maintenance_operations_rate<TEA_2025_MINIMUM_MCR){u.source_status="cross-source-conflict";u.rate_unavailable=true}}return units}
Deno.serve(async(req:Request)=>{const url=new URL(req.url);const year=Number(url.searchParams.get("year")??String(new Date().getUTCFullYear()));const currentYear=new Date().getUTCFullYear();if(!Number.isInteger(year)||year<2021||year>currentYear)return Response.json({error:`year must be between 2021 and ${currentYear}`},{status:400});try{const raw:RawRecord[]=[];const diagnostics:any[]=[];for(const type of Object.keys(FILES) as UnitType[]){const sourceUrl=`https://comptroller.texas.gov/taxes/property-tax/docs/${year}-${FILES[type]}`;const response=await fetch(sourceUrl,{headers:{"user-agent":"TexasDefined tax-rate importer/4.1"}});if(!response.ok)throw new Error(`${type}: HTTP ${response.status}`);const records=parseWorkbook(type,sourceUrl,new Uint8Array(await response.arrayBuffer()));raw.push(...records);diagnostics.push({type,rawRows:records.length})}const normalized=normalizeYear(raw,year);const{error:de}=await supabase.from("texas_property_tax_rates").delete().eq("year",year);if(de)throw de;for(let i=0;i<normalized.length;i+=400){const{error}=await supabase.from("texas_property_tax_rates").upsert(normalized.slice(i,i+400),{onConflict:"id"});if(error)throw error}return Response.json({ok:true,year,rawCount:raw.length,normalizedCount:normalized.length,notReportedCount:normalized.filter(r=>r.source_status==="not-reported").length,crossSourceConflictCount:normalized.filter(r=>r.source_status==="cross-source-conflict").length,partialCount:normalized.filter(r=>r.source_status==="partial-reporting").length,variableCount:normalized.filter(r=>r.variable_rate).length,multiCountyCount:normalized.filter(r=>r.split_across_cads).length,diagnostics},{headers:{"cache-control":"no-store"}})}catch(error){return Response.json({ok:false,year,error:error instanceof Error?error.message:String(error)},{status:500})}});
