// AUTO-GENERATED by scripts/data/sync-property-tax-rates.py.
// The checked-in seed keeps the application buildable before the first sync run.

export type TexasTaxingUnitType = 'county' | 'city' | 'school-district' | 'special-district';

export type TexasTaxRateRecord = {
  id: string;
  year: number;
  type: TexasTaxingUnitType;
  name: string;
  slug: string;
  countySlugs: string[];
  totalRate: number | null;
  rateVariants: number[];
  variableRate: boolean;
  maintenanceOperationsRate: number | null;
  debtServiceRate: number | null;
  levy: number | null;
  sourceUrl: string;
  sourceStatus: 'reported-final';
};

export const TEXAS_TAX_RATE_DATASET_META = {
  sourceName: 'Texas Comptroller of Public Accounts — Property Tax Assistance Division',
  sourcePage: 'https://comptroller.texas.gov/taxes/property-tax/rates/',
  latestFinalizedYear: 2025,
  availableYears: [] as number[],
  generatedAt: null as string | null,
  recordCount: 0,
  status: 'pending-first-sync' as 'pending-first-sync' | 'synced',
};

export const TEXAS_TAX_RATE_RECORDS: TexasTaxRateRecord[] = [];
