import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";
import type { FishingAccessProfileData } from "@/data/fishing/access-profile-data.server";

export function FishingAccessProfile({ pageData }: { pageData: FishingAccessProfileData }) {
  const { point, lakes } = pageData;
  const amenities = "amenities" in point ? point.amenities : undefined;
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing">Fishing</Link></li><li aria-hidden>·</li><li><Link to="/fishing/access">Access</Link></li><li aria-hidden>·</li><li aria-current="page">{point.name}</li></ol></nav></Container>
    <header className="mt-5 border-y border-border bg-ink text-ink-foreground"><Container className="py-14 sm:py-20"><p className="eyebrow text-ink-foreground/65">Verified fishing access · {point.kind.replaceAll("-", " ")}</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.96] sm:text-7xl">{point.name}</h1>{point.description && <p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/80">{point.description}</p>}<p className="mt-6 text-xs uppercase tracking-[0.12em] text-ink-foreground/55">Verified {point.verifiedAt ? new Date(point.verifiedAt).toLocaleDateString("en-US", { dateStyle: "medium" }) : "from source record"}</p></Container></header>
    <Container className="py-12 sm:py-16"><div className="grid gap-12 lg:grid-cols-[1fr_0.65fr]"><main><p className="eyebrow text-primary">Access facts</p><dl className="mt-5 grid gap-5 border-t border-border pt-6 sm:grid-cols-2">{point.city && <Fact label="City" value={point.city} />}{point.county && <Fact label="County" value={`${point.county} County`} />}{point.address && <Fact label="Address" value={point.address} />}{"feeRequired" in point && point.feeRequired !== undefined && <Fact label="Fee required" value={point.feeRequired ? "Yes — verify current amount" : "No fee indicated by verified source"} />}{"fuelAvailable" in point && point.fuelAvailable !== undefined && <Fact label="Fuel" value={point.fuelAvailable ? "Available per verified source" : "Not indicated"} />}{"liveBaitAvailable" in point && point.liveBaitAvailable !== undefined && <Fact label="Live bait" value={point.liveBaitAvailable ? "Available per verified source" : "Not indicated"} />}</dl>{"launchNotes" in point && point.launchNotes && <TextSection title="Launch notes" text={point.launchNotes} />}{"accessNotes" in point && point.accessNotes && <TextSection title="Access notes" text={point.accessNotes} />}{"seasonalAccess" in point && point.seasonalAccess && <TextSection title="Seasonal access" text={point.seasonalAccess} />}{amenities?.length ? <section className="mt-10"><p className="eyebrow text-primary">Verified amenities</p><div className="mt-4 flex flex-wrap gap-2">{amenities.map((item) => <span key={item} className="border border-border px-3 py-2 text-xs">{item}</span>)}</div></section> : null}</main><aside className="border-t-2 border-foreground pt-5"><p className="eyebrow text-primary">Before you tow or travel</p><p className="mt-4 text-sm leading-7 text-muted-foreground">This is a sourced access record, not live operational status. Water level, ramp usability, fees, gates, hours and temporary closures can change after the last source check. Verify with the managing agency or operator before departure.</p>{point.website && <a href={point.website} target="_blank" rel="noreferrer noopener" className="mt-5 inline-block border-b border-primary text-sm font-semibold text-primary">Official/operator website →</a>}{point.phone && <p className="mt-4 text-sm">Phone: {point.phone}</p>}</aside></div>
      <section className="mt-14 border-t border-border pt-8"><p className="eyebrow text-primary">Connected water</p><div className="mt-5 flex flex-wrap gap-4">{lakes.map((lake) => <a key={lake!.id} href={fishingFoundationAnchor("lake", lake!.slug)} className="border-b border-primary text-sm font-semibold text-primary">{lake!.name} fishing guide →</a>)}</div></section>
      <section className="mt-12 border-t border-border pt-8"><p className="eyebrow text-primary">Sources & corrections</p><div className="mt-4 space-y-3">{point.sources.map((source) => <p key={source.id} className="text-sm text-muted-foreground"><a href={source.url} target="_blank" rel="noreferrer noopener" className="text-primary underline underline-offset-4">{source.name}</a> · checked {new Date(source.checkedAt).toLocaleDateString("en-US")}</p>)}</div><a href="/partner-with-us" className="mt-5 inline-block border-b border-primary text-sm font-semibold text-primary">Submit a correction →</a></section>
    </Container>
  </>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="eyebrow text-muted-foreground">{label}</dt><dd className="mt-1 text-sm">{value}</dd></div>; }
function TextSection({ title, text }: { title: string; text: string }) { return <section className="mt-8 border-t border-border pt-6"><p className="eyebrow text-primary">{title}</p><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></section>; }
