import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";
import type { FishingServiceProfileData } from "@/data/fishing/service-profile-data.server";

export function FishingServiceProfile({ pageData }: { pageData: FishingServiceProfileData }) {
  const { service, category, lakes } = pageData;
  const tackleSpecialties = "specialties" in service ? service.specialties : undefined;
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing">Fishing</Link></li><li aria-hidden>·</li><li><Link to="/fishing/services">Local services</Link></li><li aria-hidden>·</li><li aria-current="page">{service.name}</li></ol></nav></Container>
    <header className="mt-5 border-y border-border bg-ink text-ink-foreground"><Container className="py-14 sm:py-20"><p className="eyebrow text-ink-foreground/65">Verified fishing service · {category.replaceAll("-", " ")}</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.96] sm:text-7xl">{service.name}</h1>{service.description && <p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/80">{service.description}</p>}<p className="mt-6 text-xs uppercase tracking-[0.12em] text-ink-foreground/55">Verified {service.verifiedAt ? new Date(service.verifiedAt).toLocaleDateString("en-US", { dateStyle: "medium" }) : "from source record"}</p></Container></header>
    <Container className="py-12 sm:py-16"><div className="grid gap-12 lg:grid-cols-[1fr_0.65fr]"><main><p className="eyebrow text-primary">Verified business facts</p><dl className="mt-5 grid gap-5 border-t border-border pt-6 sm:grid-cols-2">{service.city && <Fact label="City" value={service.city} />}{service.county && <Fact label="County" value={`${service.county} County`} />}{service.address && <Fact label="Address" value={service.address} />}{"liveBaitAvailable" in service && service.liveBaitAvailable !== undefined && <Fact label="Live bait" value={service.liveBaitAvailable ? "Available per verified source" : "Not indicated by source"} />}</dl>{tackleSpecialties?.length ? <section className="mt-10"><p className="eyebrow text-primary">Verified specialties</p><div className="mt-4 flex flex-wrap gap-2">{tackleSpecialties.map((item) => <span key={item} className="border border-border px-3 py-2 text-xs">{item}</span>)}</div></section> : null}</main><aside className="border-t-2 border-foreground pt-5"><p className="eyebrow text-primary">Plan with current information</p><p className="mt-4 text-sm leading-7 text-muted-foreground">This page does not guess current hours, inventory, rates, availability or reviews. Those details can change faster than the verified listing. Confirm directly with the business before making a special trip.</p>{service.website && <a href={service.website} target="_blank" rel="noreferrer noopener" className="mt-5 inline-block border-b border-primary text-sm font-semibold text-primary">Business website →</a>}{service.phone && <p className="mt-4 text-sm">Phone: {service.phone}</p>}</aside></div>
      <section className="mt-14 border-t border-border pt-8"><p className="eyebrow text-primary">Lakes served</p><div className="mt-5 flex flex-wrap gap-4">{lakes.map((lake) => <a key={lake!.id} href={fishingFoundationAnchor("lake", lake!.slug)} className="border-b border-primary text-sm font-semibold text-primary">{lake!.name} fishing guide →</a>)}</div></section>
      <section className="mt-12 border-t border-border pt-8"><p className="eyebrow text-primary">Sources & corrections</p><div className="mt-4 space-y-3">{service.sources.map((source) => <p key={source.id} className="text-sm text-muted-foreground"><a href={source.url} target="_blank" rel="noreferrer noopener" className="text-primary underline underline-offset-4">{source.name}</a> · checked {new Date(source.checkedAt).toLocaleDateString("en-US")}</p>)}</div><a href="/partner-with-us" className="mt-5 inline-block border-b border-primary text-sm font-semibold text-primary">Claim or update this listing →</a></section>
      <section className="mt-12 border-t border-border pt-8"><p className="eyebrow text-primary">Advertising policy</p><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">A business can purchase a clearly labeled sponsored placement elsewhere in the fishing platform, but payment can never change this profile's verified facts, editorial ordering, lake recommendations or fishing advice.</p></section>
    </Container>
  </>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="eyebrow text-muted-foreground">{label}</dt><dd className="mt-1 text-sm">{value}</dd></div>; }
