import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";
import type { FishingServicesDirectoryData } from "@/data/fishing/services-directory-data.server";

export function FishingServicesDirectory({ pageData, search }: { pageData: FishingServicesDirectoryData; search: { lake?: string; category?: string; city?: string; county?: string } }) {
  const rows = pageData.services.filter(({ service, category }) => (!search.lake || service.lakeIds.includes(search.lake)) && (!search.category || category === search.category) && (!search.city || service.city === search.city) && (!search.county || service.county === search.county));
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing">Fishing</Link></li><li aria-hidden>·</li><li aria-current="page">Local services</li></ol></nav></Container>
    <header className="mt-5 border-y border-border bg-ink text-ink-foreground"><Container className="py-14 sm:py-20"><p className="eyebrow text-ink-foreground/65">Texas Defined Fishing</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.96] sm:text-7xl">Fishing services around Texas lakes.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/80">Verified tackle shops and lake-area fishing businesses tied to the waters they actually serve. TexasDefined publishes sourced business facts only; hours, inventory, rates, reviews and availability are never guessed.</p></Container></header>
    <Container className="py-12 sm:py-16">
      <form method="get" className="grid gap-4 border-y border-border py-6 sm:grid-cols-2 lg:grid-cols-4">
        <Filter name="lake" label="Lake" value={search.lake} options={pageData.filters.lakes.map((lake) => [lake.id, lake.name])} />
        <Filter name="category" label="Service" value={search.category} options={pageData.filters.categories.map((value) => [value, value.replaceAll("-", " ")])} />
        <Filter name="city" label="City" value={search.city} options={pageData.filters.cities.map((value) => [value, value])} />
        <Filter name="county" label="County" value={search.county} options={pageData.filters.counties.map((value) => [value, value])} />
        <div className="sm:col-span-2 lg:col-span-4 flex gap-4"><button className="border border-foreground px-4 py-2 text-xs font-semibold uppercase tracking-[0.12em]">Apply filters</button><a href="/fishing/services" className="px-2 py-2 text-xs text-muted-foreground">Clear</a></div>
      </form>
      {rows.length ? <div className="mt-10 grid gap-x-8 border-t border-border lg:grid-cols-2">{rows.map(({ service, category, href, lakes }) => <article key={service.id} className="border-b border-border py-7"><p className="eyebrow text-primary">Verified {category.replaceAll("-", " ")}</p><h2 className="mt-2 font-display text-3xl"><a href={href} className="hover:text-primary">{service.name}</a></h2>{service.description && <p className="mt-3 text-sm leading-7 text-muted-foreground">{service.description}</p>}<div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground">{service.city && <span>{service.city}</span>}{service.county && <span>{service.county} County</span>}</div><div className="mt-4 flex flex-wrap gap-3">{lakes.map((lake) => <a key={lake!.id} href={fishingFoundationAnchor("lake", lake!.slug)} className="border-b border-primary text-sm text-primary">{lake!.name}</a>)}</div><a href={href} className="eyebrow mt-5 inline-block border-b border-primary pb-1 text-primary">Service details →</a></article>)}</div> : <EmptyState />}
      <section className="mt-14 border-t border-border pt-8"><p className="eyebrow text-primary">List or update a business</p><h2 className="mt-3 font-display text-3xl">Build the lake-area service layer with verified facts.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">Use Partner With Us to submit or update a tackle shop, rental, repair shop, campground, lodging, restaurant, fuel stop or other fishing-related local business. Include the lakes served and sources TexasDefined can verify.</p><a href="/partner-with-us" className="mt-5 inline-block border-b border-primary text-sm font-semibold text-primary">Submit or update a listing →</a></section>
      <Sponsored entries={pageData.sponsoredPlacements} />
    </Container>
  </>;
}
function Filter({ name, label, value, options }: { name: string; label: string; value?: string; options: [string, string][] }) { return <label className="text-xs font-semibold uppercase tracking-[0.1em]">{label}<select name={name} defaultValue={value ?? ""} className="mt-2 block w-full border border-border bg-background px-3 py-2 text-sm font-normal normal-case tracking-normal"><option value="">All</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function EmptyState() { return <section className="mt-10 border border-border p-8"><p className="eyebrow text-primary">Verification first</p><h2 className="mt-3 font-display text-3xl">No verified local-service listings match yet.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">The statewide service directory is ready, but TexasDefined does not invent businesses, hours, prices, inventory, reviews or availability to populate it.</p></section>; }
function Sponsored({ entries }: { entries: FishingServicesDirectoryData["sponsoredPlacements"] }) { if (!entries.length) return null; return <section className="mt-14 border-t border-border pt-8"><p className="eyebrow text-primary">Sponsored placement</p><p className="mt-3 max-w-3xl text-sm text-muted-foreground">Paid visibility is separate from alphabetical editorial listings and can never change fishing advice, lake rankings or service recommendations.</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{entries.map(({ placement, advertiser }) => <a key={placement.id} href={placement.destinationUrl} rel="noopener sponsored" className="border border-border p-5"><p className="eyebrow text-primary">Sponsored</p><h3 className="mt-2 font-display text-xl">{advertiser!.name}</h3></a>)}</div></section>; }
