import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";
import type { FishingReportDirectoryData } from "@/data/fishing/report-directory-data.server";

export function FishingReportDirectory({ pageData, search }: { pageData: FishingReportDirectoryData; search: { lake?: string; species?: string; freshness?: string } }) {
  const rows = pageData.reports.filter((entry) => (!search.lake || entry.lake?.slug === search.lake) && (!search.species || entry.species.some((fish) => fish?.slug === search.species)) && (!search.freshness || entry.freshness === search.freshness));
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing">Fishing</Link></li><li aria-hidden>·</li><li aria-current="page">Reports</li></ol></nav></Container>
    <header className="mt-5 border-y border-border bg-ink text-ink-foreground"><Container className="py-14 sm:py-20"><p className="eyebrow text-ink-foreground/65">Texas fishing reports</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.96] sm:text-7xl">Verified reports, dated and freshness-labeled.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/80">TexasDefined treats a fishing report as a time-stamped snapshot, not evergreen advice. Only source-backed verified reports publish, and stale or expired reports are labeled so old conditions never masquerade as today’s bite.</p></Container></header>
    <Container className="py-12 sm:py-16">
      <form method="get" className="grid gap-4 border-y border-border py-6 sm:grid-cols-3"><label className="text-sm">Lake<select name="lake" defaultValue={search.lake ?? ""} className="mt-2 block w-full border border-border bg-background p-2"><option value="">All verified lakes</option>{pageData.filters.lakes.map((lake) => <option key={lake.id} value={lake.slug}>{lake.name}</option>)}</select></label><label className="text-sm">Target species<select name="species" defaultValue={search.species ?? ""} className="mt-2 block w-full border border-border bg-background p-2"><option value="">All verified species</option>{pageData.filters.species.map((fish) => <option key={fish.id} value={fish.slug}>{fish.commonName}</option>)}</select></label><label className="text-sm">Freshness<select name="freshness" defaultValue={search.freshness ?? ""} className="mt-2 block w-full border border-border bg-background p-2"><option value="">All reports</option><option value="current">Current window</option><option value="stale">Stale</option><option value="expired">Historical / expired</option></select></label><div className="sm:col-span-3"><button className="border border-foreground px-4 py-2 text-sm font-semibold">Apply filters</button></div></form>
      {rows.length ? <div className="mt-8 divide-y divide-border border-t border-border">{rows.map(({ report, href, freshness, lake, species, contributorGuide }) => <article key={report.id} className="py-8"><div className="flex flex-wrap items-center gap-3"><span className="eyebrow text-primary">{freshness === "current" ? "Current window" : freshness === "stale" ? "Stale report" : "Historical snapshot"}</span><span className="text-xs text-muted-foreground">Published {formatDate(report.publishedAt)}</span></div><h2 className="mt-3 font-display text-3xl"><a href={href} className="hover:text-primary">{report.title}</a></h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">{report.summary}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm">{lake && <a href={fishingFoundationAnchor("lake", lake.slug)} className="border-b border-primary text-primary">{lake.name}</a>}{species.map((fish) => fish && <a key={fish.id} href={fishingFoundationAnchor("species", fish.slug)} className="border-b border-primary text-primary">{fish.commonName}</a>)}</div>{contributorGuide && <p className="mt-4 text-xs text-muted-foreground">Contributor: verified guide {contributorGuide.businessName}</p>}</article>)}</div> : <section className="mt-10 border-t border-border pt-8"><h2 className="font-display text-3xl">No verified fishing reports are published yet.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">TexasDefined does not create placeholder bite reports, water temperatures, lake levels, clarity claims, guide quotes, or current-condition summaries. A report appears here only after its source, date, lake and species relationships pass verification.</p><p className="mt-4 text-sm text-muted-foreground">Guides approved as contributors can submit dated, attributable reports through the listing process. Editorial review and freshness rules apply equally to paid and unpaid participants.</p><Link to="/fishing/guides" className="mt-5 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Guide listing and contributor process →</Link></section>}
      <section className="mt-14 border-t border-border pt-8"><p className="eyebrow text-primary">Advertising policy</p><h2 className="mt-3 font-display text-3xl">Advertising stays outside report rankings.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">Reports are ordered by verified publication date. Sponsorship never changes report order, freshness labels, species recommendations or editorial treatment.</p>{pageData.sponsoredPlacements.map(({ placement, advertiser }) => <aside key={placement.id} className="mt-5 border border-border p-5"><p className="eyebrow text-muted-foreground">Sponsored placement</p><p className="mt-2 font-display text-xl">{advertiser?.name}</p><a href={placement.destinationUrl} rel="noopener sponsored" className="mt-3 inline-block border-b border-primary text-sm text-primary">Visit sponsor →</a></aside>)}</section>
    </Container>
  </>;
}

function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
