import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";
import type { FishingGuideDirectoryData } from "@/data/fishing/guide-directory-data.server";

type GuideDirectorySearch = { lake?: string; region?: string; species?: string; trip?: string };

export function FishingGuideDirectory({ pageData, search }: { pageData: FishingGuideDirectoryData; search: GuideDirectorySearch }) {
  const filtered = pageData.guides.filter(({ guide, lakes, species }) => {
    if (search.lake && !lakes.some(({ lake }) => lake?.slug === search.lake)) return false;
    if (search.region && !guide.serviceRegions?.includes(search.region as never)) return false;
    if (search.species && !species.some(({ species: fish }) => fish?.slug === search.species)) return false;
    return true;
  });

  return <>
    <Container className="pt-8 sm:pt-10">
      <nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/" className="hover:text-foreground">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing" className="hover:text-foreground">Fishing</Link></li><li aria-hidden>·</li><li aria-current="page">Fishing guides</li></ol></nav>
    </Container>
    <section className="mt-5 border-b border-border bg-ink text-ink-foreground">
      <Container className="py-16 sm:py-24"><p className="eyebrow text-ink-foreground/70">Texas Defined Fishing</p><h1 className="mt-4 max-w-4xl font-display text-5xl leading-[0.96] sm:text-7xl">Texas fishing guides, verified before they publish.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/82">A statewide directory designed to connect anglers with real guide businesses only after TexasDefined can verify the listing and its lake and target-species relationships.</p></Container>
    </section>
    <Container className="py-14 sm:py-20">
      <section aria-labelledby="guide-directory-heading">
        <div className="flex flex-wrap items-end justify-between gap-6"><div className="max-w-3xl"><p className="eyebrow text-primary">Verified directory</p><h2 id="guide-directory-heading" className="mt-3 font-display text-4xl sm:text-5xl">Find a guide by the water and fish you actually want to target.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Public results include only listings with <strong className="text-foreground">verifiedListing=true</strong>. TexasDefined does not create placeholder guide identities, copy scraped directory profiles, or infer prices, boats, phone numbers, reviews, schedules or booking details.</p></div><p className="max-w-md text-xs leading-6 text-muted-foreground">Editorial order: {pageData.editorialOrder}</p></div>

        {(pageData.filters.lakes.length || pageData.filters.regions.length || pageData.filters.species.length) ? <form method="get" className="mt-8 grid gap-4 border-y border-border py-6 sm:grid-cols-2 lg:grid-cols-4" aria-label="Filter verified fishing guides">
          <Filter name="lake" label="Lake" value={search.lake} options={pageData.filters.lakes.map((lake) => [lake.slug, lake.name])} />
          <Filter name="region" label="Region" value={search.region} options={pageData.filters.regions.map((region) => [region, region.replaceAll("-", " ")])} />
          <Filter name="species" label="Target species" value={search.species} options={pageData.filters.species.map((fish) => [fish.slug, fish.commonName])} />
          <label className="grid gap-2 text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">Trip type<select name="trip" disabled className="min-h-11 border border-border bg-background px-3 py-2 text-sm font-normal normal-case tracking-normal text-foreground disabled:opacity-60"><option>Available when verified</option></select></label>
          <div className="flex flex-wrap gap-4 sm:col-span-2 lg:col-span-4"><button type="submit" className="border border-primary bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Apply filters</button><a href="/fishing/guides" className="px-1 py-2.5 text-sm font-semibold text-primary">Clear filters</a></div>
        </form> : <div className="mt-8 border-y border-border py-5 text-sm leading-7 text-muted-foreground">Lake, region, target-species and trip-type filters activate only when verified guide data supports them. No empty filter choices are invented.</div>}

        {filtered.length ? <div className="mt-8 grid gap-x-8 border-t border-border lg:grid-cols-2">{filtered.map(({ guide, href, lakes, species }) => <article key={guide.id} className="border-b border-border py-8"><p className="eyebrow text-primary">Verified fishing guide</p><h3 className="mt-2 font-display text-3xl"><a href={href} className="hover:text-primary">{guide.businessName}</a></h3>{guide.guideName ? <p className="mt-2 text-sm text-muted-foreground">Guide: {guide.guideName}</p> : null}{guide.bio ? <p className="mt-4 text-sm leading-7 text-muted-foreground">{guide.bio}</p> : null}{lakes.length ? <div className="mt-5"><p className="eyebrow text-muted-foreground">Verified waters</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm">{lakes.map(({ relation, lake }) => lake ? <a key={relation.id} href={fishingFoundationAnchor("lake", lake.slug)} className="border-b border-border hover:border-primary hover:text-primary">{lake.name}</a> : null)}</div></div> : null}{species.length ? <div className="mt-5"><p className="eyebrow text-muted-foreground">Verified target species</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm">{species.map(({ relation, species: fish }) => fish ? <a key={relation.id} href={fishingFoundationAnchor("species", fish.slug)} className="border-b border-border hover:border-primary hover:text-primary">{fish.commonName}</a> : null)}</div></div> : null}<a href={href} className="mt-6 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">View verified guide profile →</a></article>)}</div> : <div className="mt-10 border-y border-border py-10"><p className="eyebrow text-primary">Directory launch status</p><h3 className="mt-3 font-display text-3xl">No fishing guide has cleared the statewide verified-listing gate yet.</h3><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">That is intentional. The directory is live, but TexasDefined will not fill it with unverified names or invented profile details just to make it look populated. As guides are verified, their profiles will appear here automatically and become discoverable from the lakes and species they actually serve.</p></div>}
      </section>

      <section aria-labelledby="guide-listing-process" className="mt-16 border-t border-border pt-10"><p className="eyebrow text-primary">For Texas fishing guides</p><h2 id="guide-listing-process" className="mt-3 font-display text-4xl">Submit, claim or update a listing.</h2><ol className="mt-7 grid gap-6 text-sm leading-7 text-muted-foreground md:grid-cols-3"><li><strong className="block font-display text-xl text-foreground">1. Send the business details.</strong>Use the partnership form and state whether this is a new submission, a claim of an existing profile, or an update.</li><li><strong className="block font-display text-xl text-foreground">2. Give us verifiable sources.</strong>Include the guide business website and the lakes, regions and target species you want associated with the listing. Only facts TexasDefined can verify are published.</li><li><strong className="block font-display text-xl text-foreground">3. Keep the profile current.</strong>Use the same process later to correct or remove information. Unverified changes stay off the public profile until checked.</li></ol><Link to="/partner-with-us" className="mt-7 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Submit, claim or update a fishing-guide listing →</Link></section>

      <section aria-labelledby="guide-sponsorship" className="mt-16 border-t border-border pt-10"><p className="eyebrow text-primary">Commercial opportunities</p><h2 id="guide-sponsorship" className="mt-3 font-display text-4xl">Featured placements are available, but they are advertising.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">A verified guide can inquire about statewide, regional, lake or species sponsorship. Every paid placement is labeled <strong className="text-foreground">Sponsored</strong>, lives outside the editorial ordering logic, and cannot buy a higher editorial rank or recommendation.</p>{pageData.sponsoredPlacements.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2">{pageData.sponsoredPlacements.map(({ placement, advertiser }) => advertiser ? <article key={placement.id} className="border border-border p-5"><p className="eyebrow text-primary">Sponsored placement</p><h3 className="mt-2 font-display text-2xl">{advertiser.name}</h3><a href={placement.destinationUrl} rel="noopener sponsored" className="mt-4 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Visit sponsor →</a></article> : null)}</div> : null}<Link to="/partner-with-us" className="mt-7 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Ask about a sponsored fishing-guide placement →</Link></section>
    </Container>
  </>;
}

function Filter({ name, label, value, options }: { name: string; label: string; value?: string; options: Array<[string, string]> }) {
  return <label className="grid gap-2 text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{label}<select name={name} defaultValue={value ?? ""} className="min-h-11 border border-border bg-background px-3 py-2 text-sm font-normal normal-case tracking-normal text-foreground"><option value="">All</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>;
}
