import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import type { FishingGuideProfileData } from "@/data/fishing/guide-profile-data.server";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";

export function FishingGuideProfile({ pageData }: { pageData: FishingGuideProfileData }) {
  const { guide } = pageData;
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/" className="hover:text-foreground">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing" className="hover:text-foreground">Fishing</Link></li><li aria-hidden>·</li><li><Link to="/fishing/guides" className="hover:text-foreground">Fishing guides</Link></li><li aria-hidden>·</li><li aria-current="page">{guide.businessName}</li></ol></nav></Container>
    <section className="mt-5 border-b border-border bg-ink text-ink-foreground"><Container className="py-16 sm:py-24"><p className="eyebrow text-ink-foreground/70">Verified Texas fishing guide</p><h1 className="mt-4 max-w-4xl font-display text-5xl leading-[0.96] sm:text-7xl">{guide.businessName}</h1>{guide.guideName ? <p className="mt-5 text-lg text-ink-foreground/82">Guide: {guide.guideName}</p> : null}{guide.bio ? <p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/82">{guide.bio}</p> : null}</Container></section>
    <Container className="py-14 sm:py-20">
      <div className="grid gap-14 lg:grid-cols-[1.15fr_0.85fr]">
        <main>
          <section aria-labelledby="guide-service-heading"><p className="eyebrow text-primary">Verified service relationships</p><h2 id="guide-service-heading" className="mt-3 font-display text-4xl">Where this guide is verified to fish.</h2>{pageData.lakes.length ? <div className="mt-7"><h3 className="font-display text-2xl">Waters served</h3><ul className="mt-4 grid gap-3 sm:grid-cols-2">{pageData.lakes.map(({ relation, lake }) => lake ? <li key={relation.id} className="border-t border-border pt-3"><a href={fishingFoundationAnchor("lake", lake.slug)} className="font-semibold hover:text-primary">{lake.name}</a>{relation.primary ? <span className="ml-2 text-xs uppercase tracking-[0.12em] text-muted-foreground">Primary water</span> : null}</li> : null)}</ul></div> : null}{pageData.species.length ? <div className="mt-8"><h3 className="font-display text-2xl">Target species</h3><ul className="mt-4 flex flex-wrap gap-x-5 gap-y-3 text-sm">{pageData.species.map(({ relation, species }) => species ? <li key={relation.id}><a href={fishingFoundationAnchor("species", species.slug)} className="border-b border-border hover:border-primary hover:text-primary">{species.commonName}</a>{relation.primary ? <span className="ml-2 text-xs uppercase tracking-[0.12em] text-muted-foreground">Primary</span> : null}</li> : null)}</ul></div> : null}{pageData.techniques.length ? <div className="mt-8"><h3 className="font-display text-2xl">Verified techniques</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{pageData.techniques.map((row) => row?.name).filter(Boolean).join(", ")}</p></div> : null}</section>

          <section aria-labelledby="listing-verification" className="mt-14 border-t border-border pt-9"><p className="eyebrow text-primary">Listing standard</p><h2 id="listing-verification" className="mt-3 font-display text-3xl">Missing details stay missing until they are verified.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">TexasDefined publishes only sourced guide-profile facts. If a price, boat description, phone number, booking link or other detail is absent here, the directory does not guess or fill the gap. This profile was last verified {guide.verifiedAt ? new Date(guide.verifiedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "from its listed sources"}.</p><div className="mt-5 flex flex-wrap gap-5 text-sm"><Link to="/partner-with-us" className="border-b border-primary pb-1 font-semibold text-primary">Claim or update this listing →</Link><Link to="/fishing/guides" className="border-b border-border pb-1 hover:border-primary hover:text-primary">Back to all verified guides →</Link></div></section>
        </main>

        <aside className="space-y-8">
          <section className="border-y border-border py-6"><p className="eyebrow text-primary">Verified listing details</p><dl className="mt-5 space-y-5 text-sm">{guide.phone ? <div><dt className="font-semibold">Phone</dt><dd className="mt-1 text-muted-foreground">{guide.phone}</dd></div> : null}{guide.startingPriceCents !== undefined ? <div><dt className="font-semibold">Starting price</dt><dd className="mt-1 text-muted-foreground">${(guide.startingPriceCents / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })}</dd></div> : null}{guide.maxGuests !== undefined ? <div><dt className="font-semibold">Maximum guests</dt><dd className="mt-1 text-muted-foreground">{guide.maxGuests}</dd></div> : null}{guide.boatDescription ? <div><dt className="font-semibold">Boat</dt><dd className="mt-1 leading-6 text-muted-foreground">{guide.boatDescription}</dd></div> : null}</dl>{guide.website ? <a href={guide.website} rel="noopener noreferrer" className="mt-6 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Guide website →</a> : null}{guide.bookingUrl ? <a href={guide.bookingUrl} rel="noopener noreferrer" className="mt-4 block w-fit border-b border-primary pb-1 text-sm font-semibold text-primary">Booking information →</a> : null}</section>
          <section><p className="eyebrow text-primary">Verification sources</p><ul className="mt-4 space-y-3 text-sm leading-6 text-muted-foreground">{guide.sources.map((source) => <li key={source.id}><a href={source.url} rel="noopener noreferrer" className="hover:text-primary">{source.name} ↗</a><span className="block text-xs">Checked {source.checkedAt}</span></li>)}</ul></section>
        </aside>
      </div>

      <section aria-labelledby="profile-sponsored" className="mt-16 border-t border-border pt-10"><p className="eyebrow text-primary">Advertising is separate</p><h2 id="profile-sponsored" className="mt-3 font-display text-3xl">Sponsorship cannot change this profile’s editorial treatment.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">Paid placements are rendered separately and labeled Sponsored. Payment cannot change the guide’s verified lake/species relationships, ranking, recommendation status or factual profile fields.</p>{pageData.sponsoredPlacements.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2">{pageData.sponsoredPlacements.map(({ placement, advertiser }) => advertiser ? <article key={placement.id} className="border border-border p-5"><p className="eyebrow text-primary">Sponsored placement</p><h3 className="mt-2 font-display text-2xl">{advertiser.name}</h3><a href={placement.destinationUrl} rel="noopener sponsored" className="mt-4 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Visit sponsor →</a></article> : null)}</div> : null}<Link to="/partner-with-us" className="mt-7 inline-block border-b border-primary pb-1 text-sm font-semibold text-primary">Ask about sponsored fishing placements →</Link></section>
    </Container>
  </>;
}
