import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";
import type { FishingAccessDirectoryData } from "@/data/fishing/access-directory-data.server";

export function FishingAccessDirectory({ pageData, search }: { pageData: FishingAccessDirectoryData; search: { lake?: string; kind?: string; city?: string; county?: string } }) {
  const rows = pageData.access.filter(({ point }) => (!search.lake || point.lakeIds.includes(search.lake)) && (!search.kind || point.kind === search.kind) && (!search.city || point.city === search.city) && (!search.county || point.county === search.county));
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing">Fishing</Link></li><li aria-hidden>·</li><li aria-current="page">Access</li></ol></nav></Container>
    <header className="mt-5 border-y border-border bg-ink text-ink-foreground"><Container className="py-14 sm:py-20"><p className="eyebrow text-ink-foreground/65">Texas Defined Fishing</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.96] sm:text-7xl">Texas fishing access.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/80">Verified boat ramps, marinas, shore access, piers and kayak launches tied to the lakes they actually serve. Fees, closures and launch usability can change, so every listing keeps source dates visible instead of pretending to be live availability.</p></Container></header>
    <Container className="py-12 sm:py-16">
      <form method="get" className="grid gap-4 border-y border-border py-6 sm:grid-cols-2 lg:grid-cols-4">
        <Filter name="lake" label="Lake" value={search.lake} options={pageData.filters.lakes.map((lake) => [lake.id, lake.name])} />
        <Filter name="kind" label="Access type" value={search.kind} options={pageData.filters.kinds.map((value) => [value, value.replaceAll("-", " ")])} />
        <Filter name="city" label="City" value={search.city} options={pageData.filters.cities.map((value) => [value, value])} />
        <Filter name="county" label="County" value={search.county} options={pageData.filters.counties.map((value) => [value, value])} />
        <div className="sm:col-span-2 lg:col-span-4 flex gap-4"><button className="border border-foreground px-4 py-2 text-xs font-semibold uppercase tracking-[0.12em]">Apply filters</button><a href="/fishing/access" className="px-2 py-2 text-xs text-muted-foreground">Clear</a></div>
      </form>
      {rows.length ? <div className="mt-10 grid gap-x-8 border-t border-border lg:grid-cols-2">{rows.map(({ point, href, lakes }) => <article key={point.id} className="border-b border-border py-7"><p className="eyebrow text-primary">Verified {point.kind.replaceAll("-", " ")}</p><h2 className="mt-2 font-display text-3xl"><a href={href} className="hover:text-primary">{point.name}</a></h2>{point.description && <p className="mt-3 text-sm leading-7 text-muted-foreground">{point.description}</p>}<div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground">{point.city && <span>{point.city}</span>}{point.county && <span>{point.county} County</span>}</div><div className="mt-4 flex flex-wrap gap-3">{lakes.map((lake) => <a key={lake!.id} href={fishingFoundationAnchor("lake", lake!.slug)} className="border-b border-primary text-sm text-primary">{lake!.name}</a>)}</div><a href={href} className="eyebrow mt-5 inline-block border-b border-primary pb-1 text-primary">Access details →</a></article>)}</div> : <EmptyState />}
      <section className="mt-14 border-t border-border pt-8"><p className="eyebrow text-primary">Add or correct access</p><h2 className="mt-3 font-display text-3xl">Submit a source-backed access listing.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">Use Partner With Us for a new ramp, marina, shore site, pier or kayak launch, or to correct an existing record. Include the managing agency or operator source and the lake served. TexasDefined does not infer fees, launch condition, operating hours or closure status.</p><a href="/partner-with-us" className="mt-5 inline-block border-b border-primary text-sm font-semibold text-primary">Submit or update access →</a></section>
      <Sponsored entries={pageData.sponsoredPlacements} />
    </Container>
  </>;
}

function Filter({ name, label, value, options }: { name: string; label: string; value?: string; options: [string, string][] }) { return <label className="text-xs font-semibold uppercase tracking-[0.1em]">{label}<select name={name} defaultValue={value ?? ""} className="mt-2 block w-full border border-border bg-background px-3 py-2 text-sm font-normal normal-case tracking-normal"><option value="">All</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function EmptyState() { return <section className="mt-10 border border-border p-8"><p className="eyebrow text-primary">Verification first</p><h2 className="mt-3 font-display text-3xl">No verified access listings match yet.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">The statewide access platform is live, but TexasDefined does not create placeholder ramps or guess fees, amenities, closures or launch conditions to make the directory look full.</p></section>; }
function Sponsored({ entries }: { entries: FishingAccessDirectoryData["sponsoredPlacements"] }) { if (!entries.length) return null; return <section className="mt-14 border-t border-border pt-8"><p className="eyebrow text-primary">Sponsored placement</p><p className="mt-3 max-w-3xl text-sm text-muted-foreground">Paid visibility is separate from the alphabetical access directory and can never change access recommendations or source verification.</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{entries.map(({ placement, advertiser }) => <a key={placement.id} href={placement.destinationUrl} rel="noopener sponsored" className="border border-border p-5"><p className="eyebrow text-primary">Sponsored</p><h3 className="mt-2 font-display text-xl">{advertiser!.name}</h3></a>)}</div></section>; }
