import { Link } from "@tanstack/react-router";

import { Container } from "@/components/layout/Container";
import { fishingGuideCanonicalPath } from "@/data/fishing/guide-routing";
import { fishingFoundationAnchor } from "@/data/fishing/slugs";
import type { FishingReportProfileData } from "@/data/fishing/report-profile-data.server";

export function FishingReportProfile({ pageData }: { pageData: FishingReportProfileData }) {
  const { report, freshness, lake, updates, contributorGuide } = pageData;
  const historical = freshness === "expired";
  return <>
    <Container className="pt-8 sm:pt-10"><nav aria-label="Breadcrumb" className="text-[0.72rem] uppercase tracking-[0.14em] text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link to="/">Front page</Link></li><li aria-hidden>·</li><li><Link to="/fishing">Fishing</Link></li><li aria-hidden>·</li><li><Link to="/fishing/reports">Reports</Link></li><li aria-hidden>·</li><li aria-current="page">{report.title}</li></ol></nav></Container>
    <header className="mt-5 border-y border-border bg-ink text-ink-foreground"><Container className="py-14 sm:py-20"><p className="eyebrow text-ink-foreground/65">{freshness === "current" ? "Verified current-window report" : freshness === "stale" ? "Verified stale report" : "Verified historical report"}</p><h1 className="mt-4 max-w-5xl font-display text-5xl leading-[0.96] sm:text-7xl">{report.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-ink-foreground/80">{report.summary}</p><p className="mt-5 text-sm text-ink-foreground/65">Published {formatDate(report.publishedAt)}{report.expiresAt ? ` · report window ends ${formatDate(report.expiresAt)}` : ""}</p></Container></header>
    <Container className="py-12 sm:py-16"><section className="border-l-4 border-primary pl-5"><h2 className="font-display text-2xl">{historical ? "Historical snapshot — not current conditions" : freshness === "stale" ? "Use as a dated snapshot, not a live bite claim" : "Current only within this report’s verified window"}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Fishing conditions can change quickly. Every condition below is attributed to this report’s publication window and sources; TexasDefined does not roll old observations forward as current facts.</p></section>
      <section className="mt-10"><p className="eyebrow text-primary">Water & place</p><h2 className="mt-3 font-display text-3xl"><a href={fishingFoundationAnchor("lake", lake.slug)} className="hover:text-primary">{lake.name}</a></h2><dl className="mt-6 grid gap-5 sm:grid-cols-3">{report.waterTemperatureF !== undefined && <Fact label="Reported water temperature" value={`${report.waterTemperatureF}°F`} />}{report.waterLevelSummary && <Fact label="Reported water level" value={report.waterLevelSummary} />}{report.waterClarity && <Fact label="Reported clarity" value={report.waterClarity} />}</dl></section>
      <section className="mt-12 border-t border-border pt-8"><p className="eyebrow text-primary">Species updates</p><div className="mt-6 space-y-8">{updates.map(({ update, species, techniques }) => <article key={update.speciesId} className="border-t border-border pt-6"><div className="flex flex-wrap items-center gap-3"><h3 className="font-display text-2xl">{species && <a href={fishingFoundationAnchor("species", species.slug)} className="hover:text-primary">{species.commonName}</a>}</h3>{update.activity && <span className="eyebrow text-muted-foreground">Reported activity: {update.activity}</span>}</div><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">{update.summary}</p>{update.depthGuidance && <p className="mt-3 text-sm"><strong>Reported depth:</strong> {update.depthGuidance}</p>}{update.productiveHabitats?.length ? <p className="mt-2 text-sm"><strong>Reported habitat:</strong> {update.productiveHabitats.join(", ")}</p> : null}{techniques.length ? <p className="mt-2 text-sm"><strong>Techniques:</strong> {techniques.map((item) => item?.name).filter(Boolean).join(", ")}</p> : null}{update.recommendedBaits?.length ? <p className="mt-2 text-sm"><strong>Reported baits:</strong> {update.recommendedBaits.join(", ")}</p> : null}</article>)}</div></section>
      <section className="mt-12 border-t border-border pt-8"><p className="eyebrow text-primary">Attribution & sources</p>{contributorGuide ? <p className="mt-3 text-sm">Contributed by verified, contributor-approved guide <a href={fishingGuideCanonicalPath(contributorGuide.slug)} className="border-b border-primary text-primary">{contributorGuide.businessName}</a>.</p> : <p className="mt-3 text-sm text-muted-foreground">No guide attribution is displayed unless the contributor is a verified, contributor-approved fishing guide.</p>}<ul className="mt-5 space-y-3">{report.sources.map((source) => <li key={source.id} className="text-sm"><a href={source.url} target="_blank" rel="noreferrer noopener" className="border-b border-primary text-primary">{source.name}</a> <span className="text-muted-foreground">· checked {formatDate(source.checkedAt)}</span></li>)}</ul></section>
      <p className="mt-10 text-xs leading-6 text-muted-foreground">Sponsored status can never change this report’s freshness label, ordering, condition wording, species recommendations, attribution or editorial treatment.</p>
    </Container>
  </>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="eyebrow text-muted-foreground">{label}</dt><dd className="mt-2 text-sm leading-6">{value}</dd></div>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
