import { Link } from "@tanstack/react-router";

import { paintedChurchImageSources } from "@/data/painted-church-image-sources";
import { expandedPaintedChurches } from "@/data/painted-churches-expanded";

const sourceLibrary = [
  { label: "Discover Victoria Texas", url: "https://www.discovervictoriatexas.com/business/painted-churches-of-texas", role: "Regional visitor context", note: "Useful for Victoria-area framing and travel context. Church-specific historical claims remain secondary to THC, NPS, parish and archival records." },
  { label: "Painted Churches in Texas", url: "https://paintedchurchesintexas.com/", role: "Dedicated church catalog", note: "Useful for church-by-church visitor leads. Historical dates, artist attributions and current access are independently verified before publication." },
  { label: "Roaming the USA", url: "https://www.roamingtheusa.com/painted-churches-of-texas/", role: "Travel and visual interpretation", note: "Useful for visual descriptions and route context. Time-sensitive information is rechecked locally." },
  { label: "Traveller’s Elixir", url: "https://www.travellerselixir.com/texas-painted-churches-road-trip/", role: "Expansion and road-trip lead", note: "Helped surface Plantersville and Corn Hill as candidates before Texas Defined independently verified them." },
  { label: "Portal to Texas History", url: "https://texashistory.unt.edu/search/?q=painted+churches+texas", role: "Primary-source photographs and scans", note: "Especially valuable for historic interior photographs and locally held archival collections. Item-level reproduction rights are checked before image publication." },
  { label: "Buie Harwood decorative-painting research archive", url: "https://txarchives.org/utaaa/finding_aids/00136.xml", role: "Scholarly field-research archive", note: "Documents survey cards, designation drafts, painter research, restoration material and extensive church-specific slide groups." },
  { label: "Texas Monthly / Anthony Head research", url: "https://www.texasmonthly.com/", role: "Expert secondary research", note: "Useful for decorative-painting analysis, unresolved attribution questions and expansion leads while primary records retain precedence for hard facts." },
] as const;

const authorityLinks = [
  ["Master census", "/explore/painted-churches/census"], ["Painting techniques", "/explore/painted-churches/techniques"],
  ["Symbols & iconography", "/explore/painted-churches/symbols"], ["Artists, architects & researchers", "/explore/painted-churches/people"],
  ["Heritage communities", "/explore/painted-churches/heritage"], ["Preservation & authenticity", "/explore/painted-churches/preservation"],
  ["Then & now archive project", "/explore/painted-churches/then-and-now"], ["Knowledge graph", "/explore/painted-churches/knowledge-graph"],
  ["Harwood archive guide", "/explore/painted-churches/harwood-archive"], ["How to read a Painted Church", "/explore/painted-churches/how-to-read"],
  ["Architecture glossary", "/explore/painted-churches/glossary"], ["Statewide timeline", "/explore/painted-churches/timeline"],
  ["Routes & itineraries", "/explore/painted-churches/routes"], ["Documentary & oral histories", "/explore/painted-churches/media"],
  ["Cite this collection", "/explore/painted-churches/cite"],
] as const;

const verifiedAdditions = [
  { slug: "plantersville-st-marys-catholic-church", name: "St. Mary’s Catholic Church", place: "Plantersville, Texas", result: "Verified and added. THC documents the 1917 Gothic Revival church, German and Polish immigrant parish history, heritage stained glass and Recorded Texas Historic Landmark status; independent visual documentation confirms the decorated interior." },
  { slug: "corn-hill-holy-trinity-catholic-church", name: "Holy Trinity Catholic Church", place: "Corn Hill, Texas", result: "Verified and added to the broader tradition. Parish and Williamson County records document the 1889 founding, Moravian heritage and 1913 twin-spired church." },
  { slug: "palestine-sacred-heart-catholic-church", name: "Sacred Heart Catholic Church", place: "Palestine, Texas", result: "Verified from Portal to Texas History interior photographs, Harwood decorative-painting research and current parish visitor records." },
  { slug: "bandera-st-stanislaus-catholic-church", name: "St. Stanislaus Catholic Church", place: "Bandera, Texas", result: "Verified as a living Painted Church tradition. The historic parish is an RTHL and the parish itself documents the artists, subjects and 2003–2008 modern painted campaign." },
  { slug: "corpus-christi-sacred-heart-catholic-church", name: "Sacred Heart Catholic Church", place: "Corpus Christi, Texas", result: "Verified and added from parish, diocesan, Texas A&M–Corpus Christi and SAH Archipedia evidence documenting Antonio E. Garcia's monumental 1940s true-fresco campaign." },
  { slug: "san-antonio-st-joseph-catholic-church", name: "St. Joseph Catholic Church", place: "San Antonio, Texas", result: "Verified and added from active-parish history, Portal to Texas History fresco photography and Harwood decorative-painting research." },
  { slug: "anderson-st-stanislaus-kostka", name: "St. Stanislaus Kostka Catholic Church", place: "Anderson, Texas", result: "Verified and added from the parish's own record of restored original ceiling painting, historic altars and glass, and a separately dated 2014 altar mural." },
  { slug: "castroville-st-louis-catholic-church", name: "St. Louis Catholic Church", place: "Castroville, Texas", result: "Verified and added from the active parish’s painted-interior documentation, Buie Harwood decorative-painting research and Texas Historical Commission Recorded Texas Historic Landmark records." },
  { slug: "lacoste-our-lady-of-grace", name: "Our Lady of Grace Catholic Church", place: "La Coste, Texas", result: "Verified and added from the active parish, Texas Historical Commission records and a dedicated 21-slide Buie Harwood decorative-painting research group for the 1911 church." },
] as const;

const researchQueue = [
  { slug: "ellinger-st-marys-catholic-church", name: "St. Mary’s Church", place: "Ellinger / Hostyn Hill, Texas", status: "Historic church history is verified, but painted-interior evidence has not yet met the church-specific standard for public inclusion." },
  { slug: "rockne-sacred-heart-catholic-church", name: "Sacred Heart Catholic Church", place: "Rockne, Texas", status: "German-Catholic history and a reusable exterior are documented; Painted Church classification still needs stronger interior evidence." },
  { slug: "san-antonio-san-fernando-cathedral", name: "San Fernando Cathedral", place: "San Antonio, Texas", status: "A 1982 Buie Harwood decorative-painting research group verifies a serious lead, but surviving-program scope, authorship and fit with this collection still need stronger evidence before inclusion." },
] as const;

export function PaintedChurchSourceLibrary() {
  return (
    <section aria-labelledby="source-library" className="mt-16 border-t-2 border-foreground pt-8">
      <p className="eyebrow text-primary">Research library</p>
      <h2 id="source-library" className="mt-3 font-display text-4xl sm:text-5xl">How Texas Defined keeps expanding the record</h2>
      <p className="mt-5 max-w-4xl text-base leading-8 text-muted-foreground">Primary records lead: Texas Historical Commission, National Register documentation, parish archives and official church sources take precedence for dates, architects, artists, designations and access. Secondary sources and archives are used to discover candidates, interpret decorative work and locate photography, but every public addition receives a church-specific verification pass first.</p>

      <div className="mt-10 border-l-2 border-primary bg-surface p-6 sm:p-8"><p className="eyebrow text-primary">Authority system</p><h3 className="mt-3 font-display text-3xl">Research the churches by entity, not just by destination.</h3><p className="mt-4 max-w-4xl text-sm leading-7 text-muted-foreground">The Painted Churches section now has canonical authority pages for techniques, symbols, people, cultural communities, preservation concepts, archival comparisons and architecture terms, all joined by an evidence-backed knowledge graph.</p><div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 text-sm">{authorityLinks.map(([label, href]) => <Link key={href} to={href as any} className="border-b border-primary text-primary">{label}</Link>)}</div></div>

      <div className="mt-9 grid gap-px border border-border bg-border md:grid-cols-2">{sourceLibrary.map((source) => <article key={source.label} className="bg-background p-6"><p className="eyebrow text-muted-foreground">{source.role}</p><h3 className="mt-2 font-display text-2xl leading-tight"><a href={source.url} target="_blank" rel="noreferrer" className="hover:text-primary">{source.label}</a></h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{source.note}</p></article>)}</div>

      <div className="mt-10 border-t border-border pt-8"><p className="eyebrow text-primary">Free-use image research</p><h3 className="mt-3 font-display text-3xl">Exact-subject archives first. Generic stock only as a labeled fallback.</h3><p className="mt-4 max-w-4xl text-sm leading-7 text-muted-foreground">Texas Defined prioritizes Wikimedia Commons, the Portal to Texas History and Library of Congress/HABS records because they are most likely to identify the actual church. PICRYL/GetArchive and license-filtered Flickr are secondary discovery channels. Stock libraries are used only for clearly labeled illustrative context and never as if a generic church photo depicts the named Painted Church.</p><div className="mt-7 grid gap-px border border-border bg-border md:grid-cols-2">{paintedChurchImageSources.map((source) => <article key={source.label} className="bg-background p-6"><p className="eyebrow text-muted-foreground">Priority {source.priority} · {source.tier.replace("-", " ")}</p><h4 className="mt-2 font-display text-2xl"><a href={source.url} target="_blank" rel="noreferrer" className="hover:text-primary">{source.label}</a></h4><p className="mt-3 text-sm leading-7 text-muted-foreground">{source.bestFor}</p><p className="mt-3 text-xs leading-6 text-muted-foreground"><strong className="text-foreground">Rights rule:</strong> {source.rightsRule}</p></article>)}</div><p className="mt-5 max-w-4xl text-xs leading-6 text-muted-foreground">Library of Congress HABS/HAER/HALS and Highsmith records can carry favorable reuse advisories, but the individual record controls. Copied-source materials are not assumed public domain merely because they appear at LOC.</p></div>

      <div className="mt-10 border-l-2 border-primary bg-surface p-6 sm:p-8"><p className="eyebrow text-primary">Expansion research completed</p><h3 className="mt-3 font-display text-3xl">The collection now includes {expandedPaintedChurches.length} verified church profiles.</h3><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">Each promotion requires church-specific decorative-interior evidence and a defensible classification. Formal National Register membership, broader historic Painted Church status and later living decorative campaigns remain distinct labels.</p><div className="mt-6 grid gap-6 sm:grid-cols-2">{verifiedAdditions.map((lead) => <div key={lead.slug} className="border-t border-border pt-4"><h4 className="font-display text-2xl"><Link to="/explore/painted-churches/$slug" params={{ slug: lead.slug }} className="hover:text-primary">{lead.name}</Link></h4><p className="eyebrow mt-2 text-muted-foreground">{lead.place}</p><p className="mt-3 text-sm leading-7 text-muted-foreground">{lead.result}</p></div>)}</div></div>

      <div className="mt-10 border-t border-border pt-8"><p className="eyebrow text-primary">Still under verification</p><h3 className="mt-3 font-display text-3xl">Candidates are not counted until the evidence is there.</h3><div className="mt-6 grid gap-6 sm:grid-cols-2">{researchQueue.map((lead) => <div key={lead.slug} className="border-t border-border pt-4"><h4 className="font-display text-2xl">{lead.name}</h4><p className="eyebrow mt-2 text-muted-foreground">{lead.place}</p><p className="mt-3 text-sm leading-7 text-muted-foreground">{lead.status}</p></div>)}</div><Link to="/explore/painted-churches/census" className="mt-6 inline-block border-b border-primary text-sm text-primary">Open the complete candidate and exclusion census</Link></div>
    </section>
  );
}