import { Link } from '@tanstack/react-router';

import { DepartmentHero } from '@/components/editorial/DepartmentHero';
import { Section, SectionHeader } from '@/components/editorial/SectionHeader';
import { Container } from '@/components/layout/Container';
import type { LandscapeCatalogItem } from '@/data/texas-landscape-catalog';
import type { EnrichedLandscapeRecord } from '@/data/texas-landscape-profile-enrichment';

const TWDB_BASIN_MAP = 'https://www.twdb.texas.gov/mapping/doc/maps/Major_River_Basins_8x11.pdf';

const rivers = [
  { name: 'Rio Grande', region: 'West Texas & the border', href: '/article/texas-rio-grande-river-guide', image: '/images/explore/lakes-rivers/amistad-national-recreation-area.jpg', description: 'Texas’s great border river crosses desert basins, cuts spectacular canyons and ties mountain runoff, springs, reservoirs and irrigated valleys into one international system.' },
  { name: 'Pecos River', region: 'Far West Texas', href: '/explore/landscapes/trans-pecos-far-west-texas', image: '/images/explore/lakes-rivers/amistad-national-recreation-area.jpg', description: 'A desert river whose flow, salinity and broad valley show how scarce water behaves in the Trans-Pecos before joining the Rio Grande.' },
  { name: 'Brazos River', region: 'Plains to Gulf Coast', href: '/article/texas-brazos-river-guide', image: '/images/explore/lakes-rivers/lake-somerville-birch-creek-unit.jpg', description: 'One of the state’s longest rivers, linking High Plains tributaries, prairie country, reservoirs, agricultural bottomlands and a broad lower coastal valley.' },
  { name: 'Colorado River', region: 'West & Central Texas', href: '/article/texas-colorado-river-guide', image: '/images/explore/lakes-rivers/pedernales-falls-state-park.jpg', description: 'The Texas Colorado crosses limestone country, the Highland Lakes and Austin before flattening into a lower coastal river on its way to Matagorda Bay.' },
  { name: 'Guadalupe River', region: 'Hill Country to coast', href: '/article/texas-guadalupe-river-guide', image: '/images/editorial/texas-guadalupe-river.jpg', description: 'Spring-influenced Hill Country water, limestone channels and cypress-lined banks give way downstream to wider floodplain country and the Guadalupe estuary.' },
  { name: 'Trinity River', region: 'North Texas to Trinity Bay', href: '/article/texas-trinity-river-guide', image: '/images/editorial/texas-trinity-river.jpg', description: 'A major urban and water-supply system that drains Dallas–Fort Worth, crosses East Texas bottomlands and reaches the Galveston Bay system.' },
  { name: 'Sabine River', region: 'East Texas', href: '/explore/landscapes/piney-woods', image: '/images/editorial/texas-trinity-river.jpg', description: 'A humid, forested East Texas river with broad bottomlands, reservoirs and a lower valley influenced by Gulf Coast wetlands.' },
  { name: 'Neches River', region: 'Piney Woods', href: '/explore/landscapes/piney-woods', image: '/images/editorial/texas-trinity-river.jpg', description: 'Forested floodplains, sloughs and bottomland hardwoods make the Neches one of the clearest examples of an East Texas river landscape.' },
  { name: 'Nueces River', region: 'Edwards Plateau to South Texas', href: '/explore/lakes-rivers', image: '/images/editorial/texas-guadalupe-river.jpg', description: 'Clear upper reaches in limestone country transition toward drier South Texas landscapes and a much broader lower basin.' },
  { name: 'Frio River', region: 'Hill Country', href: '/explore/lakes-rivers', image: '/images/editorial/texas-guadalupe-river.jpg', description: 'Cold, clear water, limestone gravel and bald-cypress corridors make the Frio a classic spring-influenced Hill Country river.' },
  { name: 'San Antonio River', region: 'Central & South Texas', href: '/explore/lakes-rivers', image: '/images/editorial/texas-guadalupe-river.jpg', description: 'A spring-origin river whose upper urban reach gives way to a larger watershed that joins the Guadalupe system downstream.' },
  { name: 'Red River', region: 'North Texas', href: '/explore/landscapes/prairies-and-grasslands', image: '/images/explore/lakes-rivers/lake-somerville-birch-creek-unit.jpg', description: 'A sediment-rich northern boundary river shaped by plains runoff, wide valleys, tributaries and major reservoirs.' },
  { name: 'Canadian River', region: 'Texas Panhandle', href: '/explore/landscapes/texas-panhandle', image: '/images/explore/lakes-rivers/lake-somerville-birch-creek-unit.jpg', description: 'A High Plains and Panhandle river that cuts into canyon and breaks country, showing how streams dissect the edge of the plateau.' },
] as const;

const regions = [
  { title: 'Hill Country rivers', rivers: 'Guadalupe · Frio · Nueces · Llano · Blanco · Pedernales', body: 'Limestone, springs and aquifers help create some of Texas’s clearest and most recognizable river corridors. Bald cypress, gravel bars, exposed bedrock and sudden flood pulses are common visual clues.' },
  { title: 'East Texas rivers', rivers: 'Sabine · Neches · Angelina · Cypress', body: 'Higher rainfall, forests and lower gradients produce broader floodplains, sloughs, bottomland hardwoods and slower-moving water than most central and western rivers.' },
  { title: 'Prairie and plains rivers', rivers: 'Brazos · Colorado · Trinity · Red · Canadian', body: 'These systems cross large open landscapes, carry sediment over long distances and are heavily shaped by reservoirs, flood-control projects, agriculture and urban water demand.' },
  { title: 'Desert and border rivers', rivers: 'Rio Grande · Pecos · Devils', body: 'Low rainfall makes dependable water especially conspicuous. Canyons, spring-fed tributaries, reservoirs and dramatic changes in flow define river landscapes of far West Texas.' },
] as const;

const landforms = [
  { title: 'Floodplain', body: 'The low ground beside a river that is periodically inundated. Floodplains store sediment, support riparian forests and generally widen as rivers approach lower-gradient country.' },
  { title: 'Terrace', body: 'An older floodplain left above the modern river after the channel cut downward. Terraces often appear as step-like benches along valley walls.' },
  { title: 'Meander', body: 'A sweeping river bend created as water erodes the outside bank and deposits sediment on the inside. Meanders migrate over time across broad valleys.' },
  { title: 'Oxbow', body: 'A curved former river channel cut off when a meander is abandoned. Oxbows are especially common on wide, low-gradient floodplains.' },
  { title: 'Bottomland', body: 'Low, fertile land associated with river floodplains. In East Texas, bottomland hardwood forests can form some of the richest river habitat in the state.' },
  { title: 'Delta & estuary', body: 'Near the coast, river sediment, tides and bay waters interact. Some rivers build deltas while others enter estuaries where fresh and salt water mix.' },
] as const;

const riverJourney = [
  { step: '1', title: 'Headwaters', body: 'Small streams, springs or rainfall-fed channels collect water at higher elevations. In Texas this may mean Panhandle draws, Edwards Plateau springs or mountain drainage in the Trans-Pecos.' },
  { step: '2', title: 'Incised valley', body: 'Where slope is steeper or bedrock is resistant, the channel cuts downward. Limestone gorges, canyons and rock-bottomed reaches are common in Central and West Texas.' },
  { step: '3', title: 'Middle river', body: 'Tributaries add water and sediment. Channels widen, reservoirs interrupt flow, and rivers begin crossing larger agricultural and urban landscapes.' },
  { step: '4', title: 'Floodplain', body: 'On flatter terrain, rivers meander across broad valleys. Floodwater spreads sediment across bottomlands and may leave terraces, abandoned channels and oxbows.' },
  { step: '5', title: 'Bay, estuary or Gulf', body: 'Lower rivers slow further as they approach sea level. Freshwater, sediment and nutrients enter bays and coastal wetlands, connecting inland watersheds to the Gulf.' },
] as const;

const faq = [
  { q: 'How many major river basins are in Texas?', a: 'The Texas Water Development Board recognizes 15 major river basins and eight coastal basins. Basin boundaries follow drainage divides, not county or city lines.' },
  { q: 'Why are some Texas rivers clear and others muddy?', a: 'Water clarity reflects geology, sediment, rainfall, groundwater input, vegetation, channel type and recent flow conditions. Spring-fed limestone rivers can be exceptionally clear, while long prairie rivers often carry more suspended sediment.' },
  { q: 'Why do Texas rivers flood so quickly?', a: 'Parts of Central and West Texas combine intense thunderstorms, thin soils, steep or rocky watersheds and narrow valleys. Water can reach channels rapidly, causing dangerous flash floods even when skies are clear at the river itself.' },
  { q: 'What is the difference between a river and a river valley?', a: 'The river is the flowing channel. The river valley is the larger landform built and cut by the river over time, including floodplains, terraces, bottomlands, abandoned channels and valley walls.' },
  { q: 'Are Texas rivers natural if they contain reservoirs?', a: 'Yes, but most major systems are now strongly modified. Dams alter flow timing, sediment movement, temperature and aquatic habitat, while the underlying river valley remains part of the original drainage system.' },
  { q: 'Which Texas rivers are spring-fed?', a: 'Many Central Texas rivers receive important groundwater and spring contributions, especially in limestone and karst country. The Comal, San Marcos, upper Guadalupe, Frio, Nueces and Devils systems are among the best-known examples.' },
] as const;

function RiverMap() {
  return <figure className="overflow-hidden rounded-sm border border-border bg-surface">
    <div className="grid lg:grid-cols-2 lg:items-stretch">
      <div className="p-4 sm:p-6 lg:p-8">
        <svg viewBox="0 0 620 500" role="img" aria-labelledby="river-valleys-map-title river-valleys-map-desc" className="mx-auto h-auto w-full max-w-3xl">
          <title id="river-valleys-map-title">Orientation map of major Texas river systems</title>
          <desc id="river-valleys-map-desc">A simplified Texas outline with approximate paths for the Rio Grande, Brazos, Colorado, Guadalupe, Trinity, Red, Sabine, Neches and Nueces river systems.</desc>
          <path d="M126 38H292V99H357L383 119L447 123L471 145L516 151L536 185L548 229L538 273L553 312L532 352L502 367L476 394L446 409L420 447L380 458L350 438L319 410L280 390L241 362L201 332L172 299L144 263L116 233L86 213L67 177L73 133L103 110Z" fill="currentColor" className="text-primary" opacity="0.15" stroke="currentColor" strokeWidth="3" />
          <path d="M77 191C96 219 121 248 145 279C170 312 194 340 223 364C259 395 303 422 347 443" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" className="text-primary" />
          <path d="M156 102C195 127 237 151 278 184C318 216 347 252 375 294C399 331 423 362 458 393" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" className="text-primary" opacity="0.85" />
          <path d="M125 132C177 150 216 173 252 205C285 234 306 270 336 306C365 341 390 372 421 407" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" className="text-primary" opacity="0.75" />
          <path d="M245 208C274 229 297 250 318 281C340 313 358 343 386 374" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" className="text-primary" opacity="0.7" />
          <path d="M354 148C383 171 404 198 420 228C437 259 451 291 475 324" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" className="text-primary" opacity="0.8" />
          <path d="M292 80C357 96 422 102 492 126" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" className="text-primary" opacity="0.7" />
          <path d="M476 148C487 180 494 214 500 252C505 282 510 310 520 338" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" className="text-primary" opacity="0.7" />
          <path d="M455 159C465 193 469 224 473 258C478 286 483 309 492 337" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" className="text-primary" opacity="0.6" />
          <path d="M260 250C277 270 292 296 306 323C320 346 335 364 352 382" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" className="text-primary" opacity="0.65" />
          <g className="fill-foreground font-semibold" style={{ fontSize: '13px' }}>
            <text x="92" y="248">Rio Grande</text><text x="198" y="176">Colorado</text><text x="288" y="198">Brazos</text><text x="324" y="300">Guadalupe</text><text x="397" y="216">Trinity</text><text x="351" y="90">Red</text><text x="489" y="201">Sabine</text><text x="454" y="245">Neches</text><text x="248" y="337">Nueces</text>
          </g>
        </svg>
      </div>
      <figcaption className="border-t border-border p-5 sm:p-7 lg:border-l lg:border-t-0 lg:p-8">
        <p className="eyebrow text-primary">Texas river basins</p>
        <h2 className="mt-2 font-display text-3xl">One state, very different river systems</h2>
        <p className="mt-4 text-sm leading-7 text-muted-foreground">Texas Water Development Board identifies 15 major river basins plus eight coastal basins. This simplified map is for orientation; basin boundaries follow drainage divides rather than political borders.</p>
        <a href={TWDB_BASIN_MAP} target="_blank" rel="noreferrer" className="mt-6 inline-block text-sm font-semibold text-primary underline">Open the official TWDB basin map ↗</a>
      </figcaption>
    </div>
  </figure>;
}

export function TexasRiverValleysLandscapePage({ item, nearby }: { item: EnrichedLandscapeRecord; nearby: Pick<LandscapeCatalogItem, 'slug' | 'name' | 'dek'>[] }) {
  return <>
    <DepartmentHero current="Explore" eyebrow="Water-shaped Texas" title="Texas Rivers & River Valleys" description="How rivers carve canyons, build floodplains, connect aquifers to springs and carry Texas from high plains and limestone country to bays and the Gulf." />

    <Section><Container>
      <div className="overflow-hidden rounded-sm border border-border bg-surface"><img src="/images/editorial/texas-guadalupe-river.jpg" alt="Clear Guadalupe River flowing through a cypress-lined Texas river valley" className="aspect-video w-full object-cover" fetchPriority="high" /></div>
      <div className="mt-10 grid gap-12 lg:grid-cols-2">
        <div className="max-w-3xl"><p className="eyebrow text-primary">How water shapes Texas</p><p className="mt-4 text-lg leading-9 text-muted-foreground">{item.intro} A river is more than the water between its banks. Over thousands of years it cuts bedrock, shifts sediment, abandons old channels, builds bottomlands and links uplands to bays. Follow one Texas river from its source to the coast and the surrounding landscape can change several times.</p></div>
        <aside className="border-t-2 border-foreground pt-6"><h2 className="font-display text-2xl">At a glance</h2><dl className="mt-5 space-y-5 text-sm leading-7"><div><dt className="eyebrow text-muted-foreground">Where</dt><dd className="mt-1">Statewide, from Panhandle headwaters and West Texas desert rivers to East Texas forests and Gulf Coast estuaries.</dd></div><div><dt className="eyebrow text-muted-foreground">What changes</dt><dd className="mt-1">Rainfall, bedrock, elevation, groundwater, dams, vegetation, sediment and distance from the coast.</dd></div><div><dt className="eyebrow text-muted-foreground">Look for</dt><dd className="mt-1">Cypress corridors, gravel bars, terraces, oxbows, bottomlands, canyon reaches, reservoirs and broad coastal floodplains.</dd></div></dl></aside>
      </div>
    </Container></Section>

    <Section tone="surface"><Container><SectionHeader eyebrow="See the systems" title="Texas Rivers, Region by Region" description="The map is the fastest way to understand why a Hill Country river can look nothing like one in East Texas, the Panhandle or Big Bend." /><div className="mt-8"><RiverMap /></div></Container></Section>

    <Section><Container><SectionHeader eyebrow="River mechanics" title="How a Texas river valley forms" description="A valley records both erosion and deposition. The channel is only the most active part of a much larger system." /><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{riverJourney.map((stage) => <section key={stage.step} className="border-t-2 border-foreground pt-5"><p className="eyebrow text-primary">Stage {stage.step}</p><h3 className="mt-2 font-display text-2xl">{stage.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{stage.body}</p></section>)}</div></Container></Section>

    <Section tone="surface"><Container><SectionHeader eyebrow="Why they look different" title="Rainfall, geology and groundwater change the river" description="Texas rivers do not follow one visual template. Their character changes as the surrounding landscape changes." /><div className="mt-10 grid gap-px overflow-hidden rounded-sm border border-border bg-border md:grid-cols-2 lg:grid-cols-4">{regions.map((region) => <section key={region.title} className="bg-background p-6"><h3 className="font-display text-2xl">{region.title}</h3><p className="mt-3 text-xs font-semibold uppercase tracking-wide text-primary">{region.rivers}</p><p className="mt-4 text-sm leading-7 text-muted-foreground">{region.body}</p></section>)}</div>
      <div className="mt-10 grid gap-8 lg:grid-cols-3">
        <section className="border-t-2 border-foreground pt-5"><h2 className="font-display text-3xl">Spring-fed vs. runoff-driven rivers</h2><p className="mt-4 text-base leading-8 text-muted-foreground">In limestone country, groundwater emerging from springs can sustain clear baseflow between rain events. Elsewhere, flow depends more heavily on rainfall, tributaries and reservoir releases. That difference affects clarity, temperature, habitat and how dependable a river feels through the year.</p></section>
        <section className="border-t-2 border-foreground pt-5"><h2 className="font-display text-3xl">Bedrock controls the shape</h2><p className="mt-4 text-base leading-8 text-muted-foreground">Hard limestone can produce ledges, falls and narrow gorges. Softer sediments on the coastal plain allow channels to migrate and meander. In the Panhandle and Trans-Pecos, rivers can cut deeply into plateau margins, canyon country and desert basins.</p></section>
        <section className="border-t-2 border-foreground pt-5"><h2 className="font-display text-3xl">Slope controls the energy</h2><p className="mt-4 text-base leading-8 text-muted-foreground">Steeper upstream reaches have more erosive power. As gradient decreases downstream, rivers increasingly deposit sand, gravel and silt, widen their valleys and build floodplains.</p></section>
      </div>
    </Container></Section>

    <Section><Container><SectionHeader eyebrow="Read the landscape" title="Six river-valley features worth knowing" description="These plain-language terms explain what you are actually seeing beside a Texas river." /><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{landforms.map((feature) => <section key={feature.title} className="border-t-2 border-foreground pt-5"><h3 className="font-display text-2xl">{feature.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{feature.body}</p></section>)}</div></Container></Section>

    <Section tone="surface"><Container><SectionHeader eyebrow="Major systems" title="Thirteen rivers that explain Texas" description="These rivers are useful reference points because together they cross nearly every major Texas landscape." /><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{rivers.map((river) => <Link key={river.name} to={river.href} className="group overflow-hidden rounded-sm border border-border bg-background transition-colors hover:border-primary"><div className="aspect-[16/9] overflow-hidden bg-surface"><img src={river.image} alt={river.name + ' landscape in Texas'} loading="lazy" decoding="async" className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.02]" /></div><div className="p-5"><p className="eyebrow text-primary">{river.region}</p><h3 className="mt-2 font-display text-2xl group-hover:text-primary">{river.name}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{river.description}</p></div></Link>)}</div></Container></Section>

    <Section><Container>
      <div className="grid gap-10 lg:grid-cols-2">
        <section><p className="eyebrow text-primary">Aquifers and springs</p><h2 className="mt-3 font-display text-4xl">Some Texas rivers begin underground</h2><p className="mt-5 text-base leading-8 text-muted-foreground">Central Texas limestone is fractured, dissolved and cavernous. Rain can enter the subsurface through recharge features, move through aquifers and re-emerge at springs. Where that groundwater contribution is large, rivers may stay cooler and clearer and can maintain flow between storms. That connection is one reason river health cannot be separated from groundwater management.</p><p className="mt-4 text-base leading-8 text-muted-foreground">The Comal and San Marcos are famous spring rivers, while the Guadalupe, Frio, Nueces, Devils and many smaller streams also depend on spring and groundwater contributions in parts of their basins.</p><div className="mt-6 flex flex-wrap gap-4"><Link to="/explore/landscapes/caves-and-karst" className="text-sm font-semibold text-primary underline">Caves & karst →</Link><Link to="/explore/landscapes/hill-country" className="text-sm font-semibold text-primary underline">Hill Country landscape →</Link></div></section>
        <section><p className="eyebrow text-primary">Floods</p><h2 className="mt-3 font-display text-4xl">The floodplain is part of the river</h2><p className="mt-5 text-base leading-8 text-muted-foreground">A river valley is built to carry more than ordinary flow. During floods, water spreads onto low ground, deposits sediment, erodes banks and may cut new channels. Central Texas is particularly vulnerable to flash flooding because intense storms can fall on rocky, steep watersheds that route water into confined valleys very quickly.</p><p className="mt-4 text-base leading-8 text-muted-foreground">A dry crossing, gravel bar or broad grassy bottom is not evidence that a river is harmless. It may be part of the active floodplain. River visitors should treat weather upstream as seriously as weather overhead and follow local closure and flood warnings.</p><div className="mt-6"><Link to="/explore/landscapes/canyons" className="text-sm font-semibold text-primary underline">Texas canyons →</Link></div></section>
      </div>
    </Container></Section>

    <Section tone="surface"><Container>
      <div className="grid gap-10 lg:grid-cols-2">
        <section><p className="eyebrow text-primary">Human-shaped rivers</p><h2 className="mt-3 font-display text-4xl">Reservoirs changed the rhythm of Texas rivers</h2><p className="mt-5 text-base leading-8 text-muted-foreground">Dams store water, reduce some flood peaks, generate power and create major recreation lakes, but they also interrupt sediment transport and alter downstream flow patterns. Many of the state’s familiar lakes—including the Highland Lakes, Lake Livingston, Toledo Bend and Lake Texoma—occupy river valleys rather than natural lake basins.</p><p className="mt-4 text-base leading-8 text-muted-foreground">Below a dam, the river may carry clearer water but less sediment, experience different seasonal flow timing and respond to release schedules instead of rainfall alone. Cities, irrigation, wastewater return flows, groundwater pumping and channel engineering add additional layers of human influence.</p><div className="mt-6"><Link to="/explore/landscapes/lakes-and-reservoirs" className="text-sm font-semibold text-primary underline">Lakes & reservoir landscapes →</Link></div></section>
        <section><p className="eyebrow text-primary">Living corridors</p><h2 className="mt-3 font-display text-4xl">River valleys are ecological highways</h2><p className="mt-5 text-base leading-8 text-muted-foreground">Riparian vegetation follows water across landscapes that may otherwise be dry, open or heavily developed. Bald cypress is iconic along many Central Texas rivers; cottonwood and willow appear widely; pecan and other hardwoods occupy richer bottomlands; East Texas floodplains can support extensive bottomland hardwood forests, sloughs and wetlands.</p><p className="mt-4 text-base leading-8 text-muted-foreground">These corridors provide shade, stabilize banks, filter runoff and connect habitat for birds, mammals, reptiles, amphibians, fish and invertebrates. Near the coast, river water becomes part of estuarine systems where freshwater inflow supports bays, marshes and nursery habitat.</p><div className="mt-6 flex flex-wrap gap-4"><Link to="/explore/landscapes/wetlands-and-marshes" className="text-sm font-semibold text-primary underline">Wetlands & marshes →</Link><Link to="/explore/landscapes/gulf-coast" className="text-sm font-semibold text-primary underline">Gulf Coast landscape →</Link></div></section>
      </div>
    </Container></Section>

    <Section><Container><SectionHeader eyebrow="Experience the landscape" title="Where rivers become places to go" description="Use the physical geography as a starting point, then move into swimming, paddling, fishing, parks and destination guides." /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Link to="/explore/lakes-rivers" className="border border-border bg-background p-5 transition-colors hover:border-primary"><p className="eyebrow text-primary">Water destinations</p><h3 className="mt-2 font-display text-2xl">Lakes & Rivers →</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Find river corridors, reservoirs, swimming spots and places built around the water.</p></Link><Link to="/fishing" className="border border-border bg-background p-5 transition-colors hover:border-primary"><p className="eyebrow text-primary">On the water</p><h3 className="mt-2 font-display text-2xl">Texas Fishing →</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Move from landscape context to species, techniques and fishing destinations.</p></Link><Link to="/explore/state-parks" className="border border-border bg-background p-5 transition-colors hover:border-primary"><p className="eyebrow text-primary">Public access</p><h3 className="mt-2 font-display text-2xl">State Parks →</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Explore parks where rivers, canyons, bottomlands and springs shape the visit.</p></Link><Link to="/explore/road-trips" className="border border-border bg-background p-5 transition-colors hover:border-primary"><p className="eyebrow text-primary">See the change</p><h3 className="mt-2 font-display text-2xl">Road Trips →</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Follow the transition from one river landscape and Texas region to another.</p></Link></div></Container></Section>

    <Section tone="surface"><Container><SectionHeader eyebrow="Questions answered" title="Texas river valleys FAQ" description="Short answers to the questions that make the larger landscape easier to understand." /><div className="mt-8 grid gap-5 lg:grid-cols-2">{faq.map((item) => <section key={item.q} className="border-t border-border pt-5"><h3 className="font-display text-2xl">{item.q}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{item.a}</p></section>)}</div></Container></Section>

    <Section><Container><section className="border-t-2 border-foreground pt-7"><p className="eyebrow text-primary">Sources</p><h2 className="mt-3 font-display text-3xl">Authoritative river and basin references</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">This guide focuses on physical geography and statewide patterns. River conditions and access can change quickly, so check current flow, weather, park access, water quality and local closures before travel.</p><ul className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><li><a href="https://www.twdb.texas.gov/surfacewater/rivers/river_basins/index.asp" target="_blank" rel="noreferrer" className="font-semibold text-primary underline">Texas Water Development Board — River basins ↗</a></li><li><a href={TWDB_BASIN_MAP} target="_blank" rel="noreferrer" className="font-semibold text-primary underline">TWDB — Major river basin map ↗</a></li><li><a href="https://tpwd.texas.gov/landwater/water/habitats/rivers/" target="_blank" rel="noreferrer" className="font-semibold text-primary underline">Texas Parks & Wildlife — Rivers ↗</a></li><li><a href="https://waterdata.usgs.gov/tx/nwis/rt" target="_blank" rel="noreferrer" className="font-semibold text-primary underline">USGS — Texas real-time water data ↗</a></li><li><a href="https://www.usgs.gov/special-topics/water-science-school/science/rivers-streams-and-creeks" target="_blank" rel="noreferrer" className="font-semibold text-primary underline">USGS — River processes ↗</a></li><li><a href="https://www.nps.gov/rigr/index.htm" target="_blank" rel="noreferrer" className="font-semibold text-primary underline">National Park Service — Rio Grande Wild & Scenic River ↗</a></li></ul></section></Container></Section>

    <Section tone="surface"><Container><SectionHeader eyebrow="Keep exploring" title="Other Texas landscapes" /><ul className="mt-8 grid gap-x-8 gap-y-6 sm:grid-cols-2 lg:grid-cols-3">{nearby.map((landscape) => <li key={landscape.slug} className="border-t border-border pt-4"><Link to="/explore/landscapes/$slug" params={{ slug: landscape.slug }} className="group block"><h3 className="font-display text-2xl group-hover:text-primary">{landscape.name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{landscape.dek}</p></Link></li>)}</ul><Link to="/explore/landscapes" className="eyebrow mt-10 inline-block text-primary">See all Texas landscapes →</Link></Container></Section>
  </>;
}
