/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TexasHistoryRouteImport } from './routes/texas-history'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreCategoryRouteImport } from './routes/explore.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasHistoryRoute = TexasHistoryRouteImport.update({
  id: '/texas-history',
  path: '/texas-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategoryRoute = ExploreCategoryRouteImport.update({
  id: '/explore/$category',
  path: '/explore/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/sports': typeof SportsRoute
  '/texas-history': typeof TexasHistoryRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/sports': typeof SportsRoute
  '/texas-history': typeof TexasHistoryRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/sports': typeof SportsRoute
  '/texas-history': typeof TexasHistoryRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/sports'
    | '/texas-history'
    | '/explore/$category'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/sports'
    | '/texas-history'
    | '/explore/$category'
    | '/explore'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/sports'
    | '/texas-history'
    | '/explore/$category'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  SportsRoute: typeof SportsRoute
  TexasHistoryRoute: typeof TexasHistoryRoute
  ExploreCategoryRoute: typeof ExploreCategoryRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texas-history': {
      id: '/texas-history'
      path: '/texas-history'
      fullPath: '/texas-history'
      preLoaderRoute: typeof TexasHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$category': {
      id: '/explore/$category'
      path: '/explore/$category'
      fullPath: '/explore/$category'
      preLoaderRoute: typeof ExploreCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  SportsRoute: SportsRoute,
  TexasHistoryRoute: TexasHistoryRoute,
  ExploreCategoryRoute: ExploreCategoryRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
