/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HomeGardenRouteImport } from './routes/home-garden'
import { Route as MovingToTexasRouteImport } from './routes/moving-to-texas'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TexasHistoryRouteImport } from './routes/texas-history'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as DestinationSlugRouteImport } from './routes/destination.$slug'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreCategoryRouteImport } from './routes/explore.$category'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCollectionRouteImport } from './routes/shop.$collection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeGardenRoute = HomeGardenRouteImport.update({
  id: '/home-garden',
  path: '/home-garden',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingToTexasRoute = MovingToTexasRouteImport.update({
  id: '/moving-to-texas',
  path: '/moving-to-texas',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasHistoryRoute = TexasHistoryRouteImport.update({
  id: '/texas-history',
  path: '/texas-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationSlugRoute = DestinationSlugRouteImport.update({
  id: '/destination/$slug',
  path: '/destination/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategoryRoute = ExploreCategoryRouteImport.update({
  id: '/explore/$category',
  path: '/explore/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCollectionRoute = ShopCollectionRouteImport.update({
  id: '/shop/$collection',
  path: '/shop/$collection',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/guides': typeof GuidesRoute
  '/home-garden': typeof HomeGardenRoute
  '/moving-to-texas': typeof MovingToTexasRoute
  '/real-estate': typeof RealEstateRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/texas-history': typeof TexasHistoryRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/shop/$collection': typeof ShopCollectionRoute
  '/explore/': typeof ExploreIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/guides': typeof GuidesRoute
  '/home-garden': typeof HomeGardenRoute
  '/moving-to-texas': typeof MovingToTexasRoute
  '/real-estate': typeof RealEstateRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/texas-history': typeof TexasHistoryRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/shop/$collection': typeof ShopCollectionRoute
  '/explore': typeof ExploreIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/guides': typeof GuidesRoute
  '/home-garden': typeof HomeGardenRoute
  '/moving-to-texas': typeof MovingToTexasRoute
  '/real-estate': typeof RealEstateRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/texas-history': typeof TexasHistoryRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/shop/$collection': typeof ShopCollectionRoute
  '/explore/': typeof ExploreIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/guides'
    | '/home-garden'
    | '/moving-to-texas'
    | '/real-estate'
    | '/search'
    | '/sitemap.xml'
    | '/sports'
    | '/texas-history'
    | '/article/$slug'
    | '/destination/$slug'
    | '/explore/$category'
    | '/shop/$collection'
    | '/explore/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/guides'
    | '/home-garden'
    | '/moving-to-texas'
    | '/real-estate'
    | '/search'
    | '/sitemap.xml'
    | '/sports'
    | '/texas-history'
    | '/article/$slug'
    | '/destination/$slug'
    | '/explore/$category'
    | '/shop/$collection'
    | '/explore'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/guides'
    | '/home-garden'
    | '/moving-to-texas'
    | '/real-estate'
    | '/search'
    | '/sitemap.xml'
    | '/sports'
    | '/texas-history'
    | '/article/$slug'
    | '/destination/$slug'
    | '/explore/$category'
    | '/shop/$collection'
    | '/explore/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  GuidesRoute: typeof GuidesRoute
  HomeGardenRoute: typeof HomeGardenRoute
  MovingToTexasRoute: typeof MovingToTexasRoute
  RealEstateRoute: typeof RealEstateRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  TexasHistoryRoute: typeof TexasHistoryRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  DestinationSlugRoute: typeof DestinationSlugRoute
  ExploreCategoryRoute: typeof ExploreCategoryRoute
  ShopCollectionRoute: typeof ShopCollectionRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-garden': {
      id: '/home-garden'
      path: '/home-garden'
      fullPath: '/home-garden'
      preLoaderRoute: typeof HomeGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-to-texas': {
      id: '/moving-to-texas'
      path: '/moving-to-texas'
      fullPath: '/moving-to-texas'
      preLoaderRoute: typeof MovingToTexasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texas-history': {
      id: '/texas-history'
      path: '/texas-history'
      fullPath: '/texas-history'
      preLoaderRoute: typeof TexasHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$slug': {
      id: '/destination/$slug'
      path: '/destination/$slug'
      fullPath: '/destination/$slug'
      preLoaderRoute: typeof DestinationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$category': {
      id: '/explore/$category'
      path: '/explore/$category'
      fullPath: '/explore/$category'
      preLoaderRoute: typeof ExploreCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$collection': {
      id: '/shop/$collection'
      path: '/shop/$collection'
      fullPath: '/shop/$collection'
      preLoaderRoute: typeof ShopCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  GuidesRoute: GuidesRoute,
  HomeGardenRoute: HomeGardenRoute,
  MovingToTexasRoute: MovingToTexasRoute,
  RealEstateRoute: RealEstateRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  TexasHistoryRoute: TexasHistoryRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  DestinationSlugRoute: DestinationSlugRoute,
  ExploreCategoryRoute: ExploreCategoryRoute,
  ShopCollectionRoute: ShopCollectionRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
