create table if not exists public.texasdefined_reader_quality_events (
  id bigint generated by default as identity primary key,
  metric_date date not null,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  session_hash text not null check (session_hash ~ '^[0-9a-f]{32,64}$'),
  path text not null check (char_length(path) between 1 and 500),
  quality_score smallint not null check (quality_score between 0 and 100),
  classification text not null check (classification in ('engaged_reader','likely_human','uncertain','automation_suspected')),
  visible_ms integer not null default 0 check (visible_ms between 0 and 86400000),
  interaction_count smallint not null default 0 check (interaction_count between 0 and 500),
  max_scroll_percent smallint not null default 0 check (max_scroll_percent between 0 and 100),
  signal_count smallint not null default 0 check (signal_count between 0 and 32),
  referrer_class text not null default 'unknown' check (referrer_class in ('direct','internal','search','social','ai','other','unknown')),
  signals jsonb not null default '{}'::jsonb check (jsonb_typeof(signals) = 'object')
);

alter table public.texasdefined_reader_quality_events enable row level security;
revoke all on table public.texasdefined_reader_quality_events from anon, authenticated;
grant all on table public.texasdefined_reader_quality_events to service_role;

create index if not exists texasdefined_reader_quality_date_idx
  on public.texasdefined_reader_quality_events (metric_date desc);
create index if not exists texasdefined_reader_quality_session_idx
  on public.texasdefined_reader_quality_events (metric_date, session_hash);
create index if not exists texasdefined_reader_quality_classification_idx
  on public.texasdefined_reader_quality_events (metric_date, classification);

create or replace view public.texasdefined_reader_quality_daily
with (security_invoker = true) as
with per_session as (
  select
    metric_date,
    session_hash,
    max(quality_score)::integer as quality_score,
    max(visible_ms)::integer as visible_ms,
    max(interaction_count)::integer as interaction_count,
    max(max_scroll_percent)::integer as max_scroll_percent
  from public.texasdefined_reader_quality_events
  group by metric_date, session_hash
)
select
  metric_date,
  count(*)::bigint as observed_sessions,
  count(*) filter (where quality_score >= 60)::bigint as likely_genuine_readers,
  count(*) filter (where quality_score >= 80)::bigint as engaged_readers,
  count(*) filter (
    where quality_score <= 20
      and visible_ms < 2000
      and interaction_count = 0
      and max_scroll_percent < 10
  )::bigint as suspicious_sessions,
  round(avg(quality_score)::numeric, 1) as average_quality_score
from per_session
group by metric_date;

revoke all on public.texasdefined_reader_quality_daily from anon, authenticated;
grant select on public.texasdefined_reader_quality_daily to service_role;

comment on table public.texasdefined_reader_quality_events is 'Privacy-minimized TexasDefined reader-quality signals. No IP address, name, email, or raw user-agent storage.';
comment on view public.texasdefined_reader_quality_daily is 'Daily privacy-minimized reader-quality rollup using the strongest signal observed per pseudonymous session.';
