create table if not exists public.texasdefined_bing_webmaster_snapshots (
  id bigint generated by default as identity primary key,
  fetched_at timestamptz not null,
  site_url text not null,
  collector_version text not null,
  user_sites jsonb not null default '[]'::jsonb,
  rank_traffic jsonb not null default '[]'::jsonb,
  query_stats jsonb not null default '[]'::jsonb,
  page_stats jsonb not null default '[]'::jsonb,
  crawl_stats jsonb not null default '[]'::jsonb,
  crawl_issues jsonb not null default '[]'::jsonb,
  feeds jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.texasdefined_bing_webmaster_snapshots is
  'Server-only snapshots from Bing Webmaster Tools for TexasDefined. Contains site performance, crawl, and sitemap data; no reader identifiers or credentials.';

create index if not exists texasdefined_bing_webmaster_snapshots_fetched_at_idx
  on public.texasdefined_bing_webmaster_snapshots (fetched_at desc);

alter table public.texasdefined_bing_webmaster_snapshots enable row level security;

revoke all on table public.texasdefined_bing_webmaster_snapshots from anon, authenticated;
grant select, insert, update, delete on table public.texasdefined_bing_webmaster_snapshots to service_role;

revoke all on sequence public.texasdefined_bing_webmaster_snapshots_id_seq from anon, authenticated;
grant usage, select on sequence public.texasdefined_bing_webmaster_snapshots_id_seq to service_role;
