-- Shared-backend article channel for stories routed to TexasDefined.
-- Discovery stays in texas_news_feed; publication requires a completed original
-- TexasDefined article payload and is never inferred from a raw source blurb.
--
-- IMPORTANT: author_id values map to institutional Texas Defined editorial desks.
-- They are not fictional human contributor identities. The legacy-compatible
-- default ID a-hollis resolves to the Texas Defined Editorial Desk in app data.

ALTER TABLE public.texas_news_feed
  ADD COLUMN IF NOT EXISTS texasdefined_slug text;

CREATE TABLE IF NOT EXISTS public.texasdefined_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_feed_id bigint UNIQUE REFERENCES public.texas_news_feed(id) ON DELETE SET NULL,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  dek text NOT NULL,
  category text NOT NULL,
  region text,
  hero_url text NOT NULL,
  hero_alt text NOT NULL,
  author_id text NOT NULL DEFAULT 'a-hollis',
  published_at timestamptz NOT NULL DEFAULT now(),
  tags text[] NOT NULL DEFAULT '{}',
  body_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  related_collections text[] NOT NULL DEFAULT '{}',
  related_destinations text[] NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
  source_name text,
  source_url text,
  canonical_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_texasdefined_articles_status_published
  ON public.texasdefined_articles(status, published_at DESC);

CREATE OR REPLACE VIEW public.texasdefined_ready_queue AS
SELECT f.*
FROM public.texasdefined_story_queue f
WHERE f.texasdefined_slug IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.texasdefined_articles a WHERE a.source_feed_id = f.id
  );

CREATE OR REPLACE FUNCTION public.publish_texasdefined_queue_item(
  p_feed_id bigint,
  p_slug text,
  p_title text,
  p_dek text,
  p_category text,
  p_region text,
  p_hero_url text,
  p_hero_alt text,
  p_author_id text,
  p_tags text[],
  p_body_json jsonb,
  p_related_collections text[] DEFAULT '{}',
  p_related_destinations text[] DEFAULT '{}'
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_feed public.texas_news_feed%ROWTYPE;
BEGIN
  SELECT * INTO v_feed FROM public.texas_news_feed WHERE id = p_feed_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Feed item % not found', p_feed_id; END IF;
  IF v_feed.target_site IS DISTINCT FROM 'texasdefined' THEN
    RAISE EXCEPTION 'Feed item % is routed to %, not TexasDefined', p_feed_id, coalesce(v_feed.target_site,'unrouted');
  END IF;
  IF length(trim(coalesce(p_title,''))) < 20 OR length(trim(coalesce(p_dek,''))) < 80 THEN
    RAISE EXCEPTION 'TexasDefined article title/dek is too thin';
  END IF;
  IF jsonb_typeof(p_body_json) <> 'array' OR length(p_body_json::text) < 2500 THEN
    RAISE EXCEPTION 'TexasDefined article body is too thin';
  END IF;
  IF coalesce(p_hero_url,'') = '' OR coalesce(p_hero_alt,'') = '' THEN
    RAISE EXCEPTION 'TexasDefined article requires a hero image and alt text';
  END IF;

  INSERT INTO public.texasdefined_articles(
    source_feed_id,slug,title,dek,category,region,hero_url,hero_alt,author_id,
    tags,body_json,related_collections,related_destinations,status,source_name,
    source_url,canonical_url,published_at,updated_at
  ) VALUES (
    p_feed_id,p_slug,p_title,p_dek,p_category,nullif(p_region,''),p_hero_url,p_hero_alt,
    coalesce(nullif(p_author_id,''),'a-hollis'),coalesce(p_tags,'{}'),p_body_json,
    coalesce(p_related_collections,'{}'),coalesce(p_related_destinations,'{}'),'published',
    v_feed.source,v_feed.link,'https://texasdefined.com/article/'||p_slug,now(),now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    title=excluded.title,dek=excluded.dek,category=excluded.category,region=excluded.region,
    hero_url=excluded.hero_url,hero_alt=excluded.hero_alt,author_id=excluded.author_id,
    tags=excluded.tags,body_json=excluded.body_json,related_collections=excluded.related_collections,
    related_destinations=excluded.related_destinations,status='published',source_name=excluded.source_name,
    source_url=excluded.source_url,canonical_url=excluded.canonical_url,updated_at=now();

  UPDATE public.texas_news_feed SET texasdefined_slug = p_slug WHERE id = p_feed_id;
  RETURN p_slug;
END;
$$;

ALTER TABLE public.texasdefined_articles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS texasdefined_articles_public_read ON public.texasdefined_articles;
CREATE POLICY texasdefined_articles_public_read
ON public.texasdefined_articles FOR SELECT
USING (status = 'published');

GRANT SELECT ON public.texasdefined_articles TO anon, authenticated;
GRANT SELECT ON public.texasdefined_ready_queue TO authenticated;
REVOKE ALL ON FUNCTION public.publish_texasdefined_queue_item(bigint,text,text,text,text,text,text,text,text,text[],jsonb,text[],text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.publish_texasdefined_queue_item(bigint,text,text,text,text,text,text,text,text,text[],jsonb,text[],text[]) TO service_role;
