import { useMemo, useState, type ReactNode } from 'react';
import {
  BreakdownChart,
  BreakdownTable,
  CalculatorActions,
  CalculatorResult,
  CurrencyInput,
  MethodologyPanel,
  NumberInput,
  PercentageInput,
  formatMoney,
  useCalculatorPersistence,
  type CalculatorState,
} from '@/components/property/PropertyCalculatorFramework';
import { calculateClosingCosts, calculateDownPayment, calculateDownPaymentAssistance } from '@/lib/financial/closing-costs';
import { calculateEquityGrowth, calculateHomeEquity, calculateHomeownershipCost } from '@/lib/financial/homeownership';
import { calculateMortgagePayoff, calculateRefinance } from '@/lib/financial/mortgage';
import { calculateBudget, calculateSalaryComparison } from '@/lib/financial/planning';

const money = formatMoney;

function Workspace<T extends CalculatorState>({ storageKey, state, onRestore, defaults, children, note }: { storageKey: string; state: T; onRestore: (state: T) => void; defaults: T; children: ReactNode; note: string }) {
  const persistence = useCalculatorPersistence({ storageKey, state, onRestore });
  return <><section className="mt-10 grid gap-5 border-y border-border py-7 sm:grid-cols-2 lg:grid-cols-3">{children}</section><p className="mt-6 border-b border-border pb-6 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Planning estimate.</strong> {note}</p><CalculatorActions onSave={persistence.save} onRestore={persistence.restore} onShare={persistence.share} onPrint={persistence.print} status={persistence.status} onReset={() => onRestore(defaults)}/></>;
}
function Results({ values }: { values: Array<[string, string, string?]> }) { return <section className="mt-8" aria-live="polite" aria-atomic="true"><h2 className="sr-only">Updated estimate</h2><div className="grid gap-x-6 sm:grid-cols-2 lg:grid-cols-3">{values.map(([label,value,note]) => <CalculatorResult key={label} label={label} value={value} note={note}/>)}</div></section>; }

type DownState={price:number;percent:number;closing:number;reserve:number};
const DOWN_DEFAULTS:DownState={price:400000,percent:20,closing:3,reserve:10000};
export function DownPaymentCalculator(){const[state,setState]=useState(DOWN_DEFAULTS);const set=<K extends keyof DownState>(k:K,v:DownState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateDownPayment({homePrice:state.price,downPaymentPercent:state.percent,closingCostPercent:state.closing,reserve:state.reserve}),[state]);return <><Workspace storageKey="texasdefined:down-payment:v2" state={state} onRestore={setState} defaults={DOWN_DEFAULTS} note="Your final cash needed may also include lender credits, prepaid taxes and insurance, earnest money and program rules."><CurrencyInput label="Home price" value={state.price} onChange={v=>set('price',v)} step={1000}/><PercentageInput label="Down payment" value={state.percent} onChange={v=>set('percent',v)} step={0.5} max={100}/><PercentageInput label="Closing costs" value={state.closing} onChange={v=>set('closing',v)} step={0.1} max={100}/><CurrencyInput label="Emergency cushion" value={state.reserve} onChange={v=>set('reserve',v)} step={500}/></Workspace><Results values={[['Down payment',money(result.downPayment)],['Closing costs',money(result.closingCosts)],['Estimated cash needed',money(result.cashNeeded)],['Estimated loan',money(result.loanAmount)]]}/></>}

type ClosingState={price:number;buyer:number;seller:number;credits:number};
const CLOSING_DEFAULTS:ClosingState={price:400000,buyer:3,seller:7,credits:0};
export function ClosingCostCalculator(){const[state,setState]=useState(CLOSING_DEFAULTS);const set=<K extends keyof ClosingState>(k:K,v:ClosingState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateClosingCosts({salePrice:state.price,buyerCostPercent:state.buyer,sellerCostPercent:state.seller,sellerCredits:state.credits}),[state]);return <><Workspace storageKey="texasdefined:closing-costs:v2" state={state} onRestore={setState} defaults={CLOSING_DEFAULTS} note="Title, lender, survey, appraisal, prepaid bills, negotiated credits and agent charges vary by sale and contract."><CurrencyInput label="Sale price" value={state.price} onChange={v=>set('price',v)} step={1000}/><PercentageInput label="Buyer cost estimate" value={state.buyer} onChange={v=>set('buyer',v)} step={0.1} max={100}/><PercentageInput label="Seller cost estimate" value={state.seller} onChange={v=>set('seller',v)} step={0.1} max={100}/><CurrencyInput label="Seller credits for the buyer" value={state.credits} onChange={v=>set('credits',v)} step={500}/></Workspace><Results values={[['Buyer costs after credits',money(result.buyerCostsAfterCredits)],['Seller costs including credits',money(result.sellerCostsIncludingCredits)],['Seller amount before loan payoff',money(result.sellerProceedsBeforeLoanPayoff)]]}/></>}

type EquityState={value:number;balance:number;maxLtv:number};const EQUITY_DEFAULTS:EquityState={value:500000,balance:280000,maxLtv:80};
export function HomeEquityCalculator(){const[state,setState]=useState(EQUITY_DEFAULTS);const set=<K extends keyof EquityState>(k:K,v:EquityState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateHomeEquity({homeValue:state.value,balance:state.balance,maxLtvPercent:state.maxLtv}),[state]);return <><Workspace storageKey="texasdefined:home-equity:v2" state={state} onRestore={setState} defaults={EQUITY_DEFAULTS} note="What you can actually borrow depends on lender approval, Texas homestead rules, other loans tied to the home, closing costs and product limits."><CurrencyInput label="Estimated home value" value={state.value} onChange={v=>set('value',v)} step={1000}/><CurrencyInput label="Total owed on the home" value={state.balance} onChange={v=>set('balance',v)} step={1000}/><PercentageInput label="Maximum share of home value that can be owed" value={state.maxLtv} onChange={v=>set('maxLtv',v)} step={1} max={100}/></Workspace><Results values={[['Current equity',money(result.equity)],['Share of home value still owed',result.ltvPercent.toFixed(1)+'%'],['Possible equity available to borrow',money(result.availableAtMaxLtv)]]}/></>}

type GrowthState={value:number;balance:number;appreciation:number;annualPaydown:number;years:number};const GROWTH_DEFAULTS:GrowthState={value:400000,balance:320000,appreciation:3,annualPaydown:6000,years:10};
export function HomeEquityGrowthCalculator(){const[state,setState]=useState(GROWTH_DEFAULTS);const set=<K extends keyof GrowthState>(k:K,v:GrowthState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateEquityGrowth({homeValue:state.value,balance:state.balance,annualAppreciationPercent:state.appreciation,annualPrincipalPaydown:state.annualPaydown,years:state.years}),[state]);return <><Workspace storageKey="texasdefined:equity-growth:v2" state={state} onRestore={setState} defaults={GROWTH_DEFAULTS} note="Home values and loan balances can change. This scenario does not replace an appraisal or your lender's amortization schedule."><CurrencyInput label="Current home value" value={state.value} onChange={v=>set('value',v)} step={1000}/><CurrencyInput label="Current loan balance" value={state.balance} onChange={v=>set('balance',v)} step={1000}/><PercentageInput label="Expected yearly home-value growth" value={state.appreciation} onChange={v=>set('appreciation',v)} step={0.1} max={100}/><CurrencyInput label="Loan balance paid down each year" value={state.annualPaydown} onChange={v=>set('annualPaydown',v)} step={500}/><NumberInput label="Years ahead" value={state.years} onChange={v=>set('years',v)} min={0} max={100} suffix="years"/></Workspace><Results values={[['Future home value',money(result.futureHomeValue)],['Estimated loan balance',money(result.futureLoanBalance)],['Estimated equity',money(result.equity)],['Equity gained',money(result.equityGrowth)]]}/></>}

type PayoffState={balance:number;rate:number;payment:number;extra:number};const PAYOFF_DEFAULTS:PayoffState={balance:300000,rate:6.5,payment:2000,extra:300};
export function MortgagePayoffCalculator(){const[state,setState]=useState(PAYOFF_DEFAULTS);const set=<K extends keyof PayoffState>(k:K,v:PayoffState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateMortgagePayoff({balance:state.balance,annualRatePercent:state.rate,regularPayment:state.payment,extraMonthlyPrincipal:state.extra}),[state]);return <><Workspace storageKey="texasdefined:mortgage-payoff:v2" state={state} onRestore={setState} defaults={PAYOFF_DEFAULTS} note="Taxes and insurance are not included. Confirm how the servicer applies extra principal and whether any restrictions apply."><CurrencyInput label="Loan balance" value={state.balance} onChange={v=>set('balance',v)} step={1000}/><PercentageInput label="Interest rate" value={state.rate} onChange={v=>set('rate',v)} step={0.01} max={100}/><CurrencyInput label="Regular loan payment" value={state.payment} onChange={v=>set('payment',v)} step={50}/><CurrencyInput label="Extra amount paid each month" value={state.extra} onChange={v=>set('extra',v)} step={50}/></Workspace><Results values={[['Estimated payoff',Number.isFinite(result.months)?`${Math.floor(result.months/12)} yr ${result.months%12} mo`:'Payment too low'],['Estimated interest still to pay',Number.isFinite(result.interest)?money(result.interest):'Payment too low']]}/></>}

type RefiState={balance:number;oldRate:number;newRate:number;years:number;costs:number};const REFI_DEFAULTS:RefiState={balance:300000,oldRate:7,newRate:6,years:30,costs:7000};
export function RefinanceCalculator(){const[state,setState]=useState(REFI_DEFAULTS);const set=<K extends keyof RefiState>(k:K,v:RefiState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateRefinance({balance:state.balance,currentRatePercent:state.oldRate,newRatePercent:state.newRate,newTermYears:state.years,closingCosts:state.costs}),[state]);return <><Workspace storageKey="texasdefined:refinance:v2" state={state} onRestore={setState} defaults={REFI_DEFAULTS} note="Compare the true loan term, cash needed at closing, mortgage insurance and total interest—not just the monthly payment."><CurrencyInput label="Loan balance" value={state.balance} onChange={v=>set('balance',v)} step={1000}/><PercentageInput label="Current rate" value={state.oldRate} onChange={v=>set('oldRate',v)} step={0.01} max={100}/><PercentageInput label="New rate" value={state.newRate} onChange={v=>set('newRate',v)} step={0.01} max={100}/><NumberInput label="New loan length" value={state.years} onChange={v=>set('years',v)} min={1} max={50} suffix="years"/><CurrencyInput label="Refinance costs" value={state.costs} onChange={v=>set('costs',v)} step={500}/></Workspace><Results values={[['Current payment',money(result.currentPayment)+'/mo'],['New payment',money(result.newPayment)+'/mo'],['Monthly savings',money(result.monthlySavings)],['Months until savings cover refinance cost',Number.isFinite(result.breakEvenMonths)?`${Math.ceil(result.breakEvenMonths)} months`:'No savings']]}/><MethodologyPanel><p>Both payment scenarios use the shared fixed-rate mortgage payment engine. Break-even divides entered refinance costs by monthly payment savings and does not claim that refinancing is beneficial after considering every transaction-specific factor.</p></MethodologyPanel></>}

type OwnState={mortgage:number;taxes:number;insurance:number;pmi:number;hoa:number;special:number;maintenance:number;utilities:number;pool:number;other:number};const OWN_DEFAULTS:OwnState={mortgage:2400,taxes:700,insurance:250,pmi:0,hoa:100,special:0,maintenance:400,utilities:350,pool:0,other:0};
export function HomeownershipCostCalculator(){const[state,setState]=useState(OWN_DEFAULTS);const set=<K extends keyof OwnState>(k:K,v:OwnState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateHomeownershipCost({mortgage:state.mortgage,propertyTaxes:state.taxes,insurance:state.insurance,pmi:state.pmi,hoa:state.hoa,specialDistricts:state.special,maintenance:state.maintenance,utilities:state.utilities,pool:state.pool,other:state.other}),[state]);const breakdown=[{label:'Mortgage',value:result.breakdown.mortgage},{label:'Property taxes',value:result.breakdown.propertyTaxes},{label:'Insurance',value:result.breakdown.insurance},{label:'PMI',value:result.breakdown.pmi},{label:'HOA',value:result.breakdown.hoa},{label:'Special districts',value:result.breakdown.specialDistricts},{label:'Maintenance',value:result.breakdown.maintenance},{label:'Utilities',value:result.breakdown.utilities},{label:'Pool',value:result.breakdown.pool},{label:'Other',value:result.breakdown.other}];return <><Workspace storageKey="texasdefined:homeownership-basic:v2" state={state} onRestore={setState} defaults={OWN_DEFAULTS} note="Add the recurring property-specific costs that apply rather than relying on mortgage payment alone."><CurrencyInput label="Mortgage" value={state.mortgage} onChange={v=>set('mortgage',v)}/><CurrencyInput label="Property taxes" value={state.taxes} onChange={v=>set('taxes',v)}/><CurrencyInput label="Insurance" value={state.insurance} onChange={v=>set('insurance',v)}/><CurrencyInput label="PMI" value={state.pmi} onChange={v=>set('pmi',v)}/><CurrencyInput label="HOA and other fees" value={state.hoa} onChange={v=>set('hoa',v)}/><CurrencyInput label="Special districts / assessments" value={state.special} onChange={v=>set('special',v)}/><CurrencyInput label="Maintenance cushion" value={state.maintenance} onChange={v=>set('maintenance',v)}/><CurrencyInput label="Utilities" value={state.utilities} onChange={v=>set('utilities',v)}/><CurrencyInput label="Pool" value={state.pool} onChange={v=>set('pool',v)}/><CurrencyInput label="Other recurring costs" value={state.other} onChange={v=>set('other',v)}/></Workspace><Results values={[['Monthly ownership cost',money(result.monthly)],['Annual ownership cost',money(result.annual)]]}/><div className="mt-10 grid gap-8 lg:grid-cols-2"><BreakdownChart items={breakdown}/><BreakdownTable items={breakdown} total={result.monthly} totalLabel="Monthly ownership cost"/></div></>}

type BudgetState={income:number;housing:number;transport:number;food:number;utilities:number;debt:number;savings:number;other:number};const BUDGET_DEFAULTS:BudgetState={income:7000,housing:2400,transport:900,food:900,utilities:450,debt:600,savings:700,other:0};
export function BudgetCalculator(){const[state,setState]=useState(BUDGET_DEFAULTS);const set=<K extends keyof BudgetState>(k:K,v:BudgetState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateBudget({income:state.income,housing:state.housing,transportation:state.transport,food:state.food,utilities:state.utilities,debt:state.debt,savings:state.savings,other:state.other}),[state]);const breakdown=[{label:'Housing',value:state.housing},{label:'Transportation',value:state.transport},{label:'Food',value:state.food},{label:'Utilities',value:state.utilities},{label:'Debt payments',value:state.debt},{label:'Savings',value:state.savings},{label:'Other',value:state.other}];return <><Workspace storageKey="texasdefined:budget:v2" state={state} onRestore={setState} defaults={BUDGET_DEFAULTS} note="Use real take-home income and include irregular bills, healthcare, childcare, insurance, taxes and annual expenses where they apply."><CurrencyInput label="Monthly take-home income" value={state.income} onChange={v=>set('income',v)}/><CurrencyInput label="Housing" value={state.housing} onChange={v=>set('housing',v)}/><CurrencyInput label="Transportation" value={state.transport} onChange={v=>set('transport',v)}/><CurrencyInput label="Food" value={state.food} onChange={v=>set('food',v)}/><CurrencyInput label="Utilities" value={state.utilities} onChange={v=>set('utilities',v)}/><CurrencyInput label="Debt payments" value={state.debt} onChange={v=>set('debt',v)}/><CurrencyInput label="Savings goal" value={state.savings} onChange={v=>set('savings',v)}/><CurrencyInput label="Other" value={state.other} onChange={v=>set('other',v)}/></Workspace><Results values={[['Planned spending',money(result.plannedSpending)],['Left over',money(result.remaining)],['Share of income going to savings',result.savingsPercent.toFixed(1)+'%']]}/><div className="mt-10"><BreakdownChart items={breakdown}/></div></>}

type AidState={price:number;required:number;assistance:number;closing:number;cash:number};const AID_DEFAULTS:AidState={price:300000,required:3.5,assistance:4,closing:3,cash:15000};
export function DownPaymentAssistanceCalculator(){const[state,setState]=useState(AID_DEFAULTS);const set=<K extends keyof AidState>(k:K,v:AidState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateDownPaymentAssistance({homePrice:state.price,requiredDownPercent:state.required,assistancePercent:state.assistance,closingCostPercent:state.closing,availableCash:state.cash}),[state]);return <><Workspace storageKey="texasdefined:down-payment-assistance:v2" state={state} onRestore={setState} defaults={AID_DEFAULTS} note="Programs can have income, credit, property, occupancy, lender, repayment and location requirements. This scenario cannot determine eligibility."><CurrencyInput label="Home price" value={state.price} onChange={v=>set('price',v)} step={1000}/><PercentageInput label="Required down payment" value={state.required} onChange={v=>set('required',v)} step={0.1} max={100}/><PercentageInput label="Possible assistance" value={state.assistance} onChange={v=>set('assistance',v)} step={0.1} max={100}/><PercentageInput label="Closing costs" value={state.closing} onChange={v=>set('closing',v)} step={0.1} max={100}/><CurrencyInput label="Cash you have available" value={state.cash} onChange={v=>set('cash',v)} step={500}/></Workspace><Results values={[['Required down payment',money(result.requiredDownPayment)],['Potential assistance',money(result.potentialAssistance)],['Estimated closing costs',money(result.closingCosts)],['Total cash needed',money(result.totalCashNeeded)],['Remaining cash gap',money(result.remainingCashGap)]]}/></>}

type SalaryCompareState={salary:number;currentIndex:number;targetIndex:number};const SALARY_COMPARE_DEFAULTS:SalaryCompareState={salary:90000,currentIndex:100,targetIndex:92};
export function SalaryComparisonCalculator(){const[state,setState]=useState(SALARY_COMPARE_DEFAULTS);const set=<K extends keyof SalaryCompareState>(k:K,v:SalaryCompareState[K])=>setState(s=>({...s,[k]:v}));const result=useMemo(()=>calculateSalaryComparison({salary:state.salary,currentIndex:state.currentIndex,targetIndex:state.targetIndex}),[state]);return <><Workspace storageKey="texasdefined:salary-comparison:v2" state={state} onRestore={setState} defaults={SALARY_COMPARE_DEFAULTS} note="Cost indexes are broad estimates and cannot capture taxes, benefits, housing choices, commutes, family size or personal spending."><CurrencyInput label="Current salary" value={state.salary} onChange={v=>set('salary',v)} step={1000}/><NumberInput label="Current city cost index" value={state.currentIndex} onChange={v=>set('currentIndex',v)} step={0.1} min={0.01}/><NumberInput label="Target city cost index" value={state.targetIndex} onChange={v=>set('targetIndex',v)} step={0.1} min={0.01}/></Workspace><Results values={[['Comparable target salary',money(result.equivalentSalary)],['Salary difference',money(result.difference)],['Change in what your salary can buy',result.purchasingPowerChangePercent.toFixed(1)+'%']]}/></>}
