import { useMemo, useState, type ReactNode } from 'react';

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number.isFinite(value) ? value : 0);
const number = (value: unknown) => Math.max(0, Number(value) || 0);

function Field({ label, value, onChange, step = 1, suffix }: { label: string; value: number; onChange: (value: number) => void; step?: number; suffix?: string }) {
  return <label className="space-y-2"><span className="text-sm font-medium">{label}</span><div className="flex items-center rounded border border-border bg-background"><input className="w-full bg-transparent p-3 outline-none" type="number" min="0" step={step} value={value} onChange={(event) => onChange(number(event.target.value))} />{suffix ? <span className="pr-3 text-sm text-muted-foreground">{suffix}</span> : null}</div></label>;
}
function Results({ values }: { values: Array<[string, string]> }) { return <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{values.map(([label, value]) => <article key={label} className="rounded-lg bg-muted p-5"><p className="text-sm text-muted-foreground">{label}</p><strong className="mt-2 block font-display text-2xl">{value}</strong></article>)}</section>; }
function Shell({ children, note }: { children: ReactNode; note: string }) { return <><section className="mt-10 grid gap-5 rounded-lg border border-border p-6 sm:grid-cols-2 lg:grid-cols-3">{children}</section><p className="mt-6 rounded-lg border border-border p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Planning estimate only.</strong> {note}</p></>; }

export function MortgageCalculator() {
  const [price, setPrice] = useState(400000), [down, setDown] = useState(80000), [rate, setRate] = useState(6.5), [years, setYears] = useState(30), [tax, setTax] = useState(2.1), [insurance, setInsurance] = useState(2400);
  const result = useMemo(() => { const principal = Math.max(0, price - down); const months = Math.max(1, years * 12); const monthlyRate = rate / 1200; const principalInterest = monthlyRate ? principal * monthlyRate * Math.pow(1 + monthlyRate, months) / (Math.pow(1 + monthlyRate, months) - 1) : principal / months; const taxes = price * tax / 100 / 12; return { principal, principalInterest, taxes, total: principalInterest + taxes + insurance / 12 }; }, [price, down, rate, years, tax, insurance]);
  return <><Shell note="Actual lender payments can include mortgage insurance, HOA dues, special districts, escrow adjustments and closing costs."><Field label="Home price" value={price} onChange={setPrice} step={1000}/><Field label="Down payment" value={down} onChange={setDown} step={1000}/><Field label="Interest rate" value={rate} onChange={setRate} step={0.01} suffix="%"/><Field label="Loan term" value={years} onChange={setYears} suffix="years"/><Field label="Property-tax rate" value={tax} onChange={setTax} step={0.01} suffix="%"/><Field label="Annual insurance" value={insurance} onChange={setInsurance} step={100}/></Shell><Results values={[["Loan amount", money(result.principal)],["Principal & interest", money(result.principalInterest) + '/mo'],["Property taxes", money(result.taxes) + '/mo'],["Estimated total", money(result.total) + '/mo']]}/></>;
}

export function AffordabilityCalculator() {
  const [income, setIncome] = useState(120000), [debt, setDebt] = useState(800), [down, setDown] = useState(60000), [rate, setRate] = useState(6.5), [taxInsurance, setTaxInsurance] = useState(900);
  const result = useMemo(() => { const gross = income / 12; const housingBudget = Math.max(0, gross * .28 - debt); const piBudget = Math.max(0, housingBudget - taxInsurance); const r = rate / 1200; const n = 360; const loan = r ? piBudget * (Math.pow(1 + r, n) - 1) / (r * Math.pow(1 + r, n)) : piBudget * n; return { gross, housingBudget, price: loan + down }; }, [income, debt, down, rate, taxInsurance]);
  return <><Shell note="Lenders use their own debt-to-income rules, credit standards, reserves and loan-program requirements."><Field label="Annual household income" value={income} onChange={setIncome} step={1000}/><Field label="Monthly non-housing debt" value={debt} onChange={setDebt} step={50}/><Field label="Available down payment" value={down} onChange={setDown} step={1000}/><Field label="Interest rate" value={rate} onChange={setRate} step={0.01} suffix="%"/><Field label="Monthly taxes & insurance" value={taxInsurance} onChange={setTaxInsurance} step={50}/></Shell><Results values={[["Gross monthly income", money(result.gross)],["Target housing budget", money(result.housingBudget) + '/mo'],["Illustrative home price", money(result.price)]]}/></>;
}

export function RentVsBuyCalculator() {
  const [rent, setRent] = useState(2200), [price, setPrice] = useState(400000), [down, setDown] = useState(80000), [buyMonthly, setBuyMonthly] = useState(3300), [years, setYears] = useState(7), [appreciation, setAppreciation] = useState(3);
  const result = useMemo(() => { const rentCost = rent * 12 * years; const buyCash = down + buyMonthly * 12 * years; const futureValue = price * Math.pow(1 + appreciation / 100, years); const equityGain = Math.max(0, futureValue - price); return { rentCost, buyCash, futureValue, netBuy: Math.max(0, buyCash - equityGain), difference: rentCost - Math.max(0, buyCash - equityGain) }; }, [rent, price, down, buyMonthly, years, appreciation]);
  return <><Shell note="This simplified comparison excludes selling costs, maintenance variability, investment returns, tax effects and loan amortization."><Field label="Monthly rent" value={rent} onChange={setRent} step={50}/><Field label="Home price" value={price} onChange={setPrice} step={1000}/><Field label="Down payment" value={down} onChange={setDown} step={1000}/><Field label="Estimated owner cost" value={buyMonthly} onChange={setBuyMonthly} step={50}/><Field label="Comparison period" value={years} onChange={setYears} suffix="years"/><Field label="Annual appreciation" value={appreciation} onChange={setAppreciation} step={0.1} suffix="%"/></Shell><Results values={[["Rent paid", money(result.rentCost)],["Owner cash outflow", money(result.buyCash)],["Estimated future value", money(result.futureValue)],["Simplified net owner cost", money(result.netBuy)],["Rent minus buy", money(result.difference)]]}/></>;
}

export function CostOfLivingCalculator() {
  const [current, setCurrent] = useState(6000), [currentIndex, setCurrentIndex] = useState(100), [texasIndex, setTexasIndex] = useState(94);
  const equivalent = useMemo(() => current * texasIndex / Math.max(1, currentIndex), [current, currentIndex, texasIndex]);
  return <><Shell note="Indexes vary by provider, metro, household size and spending pattern. Replace defaults with the most relevant local figures."><Field label="Current monthly spending" value={current} onChange={setCurrent} step={100}/><Field label="Current-area index" value={currentIndex} onChange={setCurrentIndex} step={0.1}/><Field label="Texas-area index" value={texasIndex} onChange={setTexasIndex} step={0.1}/></Shell><Results values={[["Texas equivalent", money(equivalent) + '/mo'],["Monthly difference", money(equivalent - current)],["Annual difference", money((equivalent - current) * 12)]]}/></>;
}

export function SalaryCalculator() {
  const [salary, setSalary] = useState(90000), [federal, setFederal] = useState(16), [benefits, setBenefits] = useState(6), [other, setOther] = useState(0);
  const result = useMemo(() => { const payroll = 7.65; const deductions = salary * (federal + payroll + benefits + other) / 100; const net = Math.max(0, salary - deductions); return { deductions, net, monthly: net / 12 }; }, [salary, federal, benefits, other]);
  return <><Shell note="Texas has no individual state income tax, but federal tax, payroll tax and benefit deductions depend on personal circumstances."><Field label="Annual gross salary" value={salary} onChange={setSalary} step={1000}/><Field label="Estimated federal rate" value={federal} onChange={setFederal} step={0.1} suffix="%"/><Field label="Benefits & retirement" value={benefits} onChange={setBenefits} step={0.1} suffix="%"/><Field label="Other deductions" value={other} onChange={setOther} step={0.1} suffix="%"/></Shell><Results values={[["Estimated deductions", money(result.deductions)],["Annual take-home", money(result.net)],["Monthly take-home", money(result.monthly)]]}/></>;
}

export function MovingCostCalculator() {
  const [distance, setDistance] = useState(500), [homeSize, setHomeSize] = useState(3), [packing, setPacking] = useState(1200), [travel, setTravel] = useState(800), [deposits, setDeposits] = useState(1500);
  const result = useMemo(() => { const transport = 900 + distance * 2.25 + homeSize * 650; const total = transport + packing + travel + deposits; return { transport, total, reserve: total * 1.15 }; }, [distance, homeSize, packing, travel, deposits]);
  return <><Shell note="Obtain written quotes and verify valuation coverage, access fees, storage, timing and prohibited items."><Field label="Move distance" value={distance} onChange={setDistance} suffix="miles"/><Field label="Bedrooms" value={homeSize} onChange={setHomeSize}/><Field label="Packing & supplies" value={packing} onChange={setPacking} step={100}/><Field label="Travel costs" value={travel} onChange={setTravel} step={100}/><Field label="Deposits & setup" value={deposits} onChange={setDeposits} step={100}/></Shell><Results values={[["Estimated transport", money(result.transport)],["Estimated total", money(result.total)],["Total with 15% reserve", money(result.reserve)]]}/></>;
}

export function UtilityCalculator() {
  const [electric, setElectric] = useState(190), [water, setWater] = useState(85), [gas, setGas] = useState(45), [internet, setInternet] = useState(75), [trash, setTrash] = useState(35);
  const total = electric + water + gas + internet + trash;
  return <><Shell note="Actual bills vary by climate, provider, household size, home efficiency, municipal fees and deregulated electricity plan."><Field label="Electricity" value={electric} onChange={setElectric}/><Field label="Water & sewer" value={water} onChange={setWater}/><Field label="Natural gas" value={gas} onChange={setGas}/><Field label="Internet" value={internet} onChange={setInternet}/><Field label="Trash & recycling" value={trash} onChange={setTrash}/></Shell><Results values={[["Monthly utilities", money(total)],["Annual utilities", money(total * 12)]]}/></>;
}

export function HomeInsuranceCalculator() {
  const [replacement, setReplacement] = useState(350000), [baseRate, setBaseRate] = useState(.75), [windFlood, setWindFlood] = useState(1200), [deductibleCredit, setDeductibleCredit] = useState(0);
  const result = useMemo(() => { const base = replacement * baseRate / 100; const annual = Math.max(0, base + windFlood - deductibleCredit); return { base, annual, monthly: annual / 12 }; }, [replacement, baseRate, windFlood, deductibleCredit]);
  return <><Shell note="Homeowners, windstorm and flood coverage may be separate. Insurers use location, roof, claims, construction and credit-based factors where permitted."><Field label="Replacement cost" value={replacement} onChange={setReplacement} step={1000}/><Field label="Illustrative base rate" value={baseRate} onChange={setBaseRate} step={0.01} suffix="%"/><Field label="Wind/flood additions" value={windFlood} onChange={setWindFlood} step={100}/><Field label="Deductible/discount credit" value={deductibleCredit} onChange={setDeductibleCredit} step={100}/></Shell><Results values={[["Base premium", money(result.base)],["Annual estimate", money(result.annual)],["Monthly equivalent", money(result.monthly)]]}/></>;
}
