import type { MajorEventSchemaEnrichment } from "./major-event-schema-enrichment.server";

// First-party tournament research pass completed 2026-09-05. Optional Event
// properties stay absent unless a current official source supports a stable value.
export const majorEventSchemaEnrichmentBatch17: MajorEventSchemaEnrichment[] = [
  {
    slug: "uil-volleyball-state-tournament",
    image: {
      url: "https://texasdefined.com/images/events/uil-volleyball-state-tournament.jpg",
      alt: "AI-generated photorealistic editorial depiction representing UIL Volleyball State Tournament in Texas",
      sourceUrl: "https://texasdefined.com/images/events/uil-volleyball-state-tournament.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "UIL Volleyball State Tournament official page", url: "https://www.uiltexas.org/volleyball/state" },
      { label: "UIL volleyball postseason information", url: "https://www.uiltexas.org/volleyball/manual/volleyball-post-season-information" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "uil-cross-country-state-championships",
    image: {
      url: "https://texasdefined.com/images/events/uil-cross-country-state-championships.jpg",
      alt: "AI-generated photorealistic editorial depiction representing UIL Cross Country State Championships in Texas",
      sourceUrl: "https://texasdefined.com/images/events/uil-cross-country-state-championships.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [{ label: "UIL Cross Country State Championships official page", url: "https://www.uiltexas.org/cross-country/state" }],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "uil-wrestling-state-championships",
    image: {
      url: "https://texasdefined.com/images/events/uil-wrestling-state-championships.jpg",
      alt: "AI-generated photorealistic editorial depiction representing UIL Wrestling State Championships in Texas",
      sourceUrl: "https://texasdefined.com/images/events/uil-wrestling-state-championships.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "UIL Wrestling State Tournament official page", url: "https://www.uiltexas.org/wrestling/state" },
      { label: "UIL wrestling postseason information", url: "https://www.uiltexas.org/wrestling/manual/wrestling-manual-post-season-information" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "uil-spirit-state-championships",
    image: {
      url: "https://texasdefined.com/images/events/uil-spirit-state-championships.jpg",
      alt: "AI-generated photorealistic editorial depiction representing UIL Spirit State Championships in Texas",
      sourceUrl: "https://texasdefined.com/images/events/uil-spirit-state-championships.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "UIL Spirit State Championships official page", url: "https://www.uiltexas.org/spirit/spirit-state-championships" },
      { label: "UIL Spirit State Championships schedule", url: "https://www.uiltexas.org/spirit/spirit-state-championships/schedule" },
    ],
    verifiedAt: "2026-09-05",
  },
];
