import type { MajorEventSchemaEnrichment } from "./major-event-schema-enrichment.server";

// First-party verification completed 2026-09-05. Optional Event properties are
// omitted when the current organizer source does not publish a stable value yet.
export const majorEventSchemaEnrichmentBatch19: MajorEventSchemaEnrichment[] = [
  {
    slug: "nsca-national-sporting-clays-championship",
    image: {
      url: "https://texasdefined.com/images/events/nsca-national-sporting-clays-championship.jpg",
      alt: "AI-generated photorealistic editorial depiction representing NSCA National Sporting Clays Championship in Texas",
      sourceUrl: "https://texasdefined.com/images/events/nsca-national-sporting-clays-championship.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: {
      type: "Organization",
      name: "National Sporting Clays Association",
      url: "https://nsca.nssa-nsca.org/",
    },
    sources: [
      { label: "NSCA 2027 Championship Tour", url: "https://nsca.nssa-nsca.org/nsca-championship-tour/" },
      { label: "National Shooting Complex contact and location", url: "https://nsc.nssa-nsca.org/contact/" },
      { label: "National Shooting Complex official site", url: "https://nsc.nssa-nsca.org/" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "texas-state-science-and-engineering-fair",
    image: {
      url: "https://texasdefined.com/images/events/texas-state-science-and-engineering-fair.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Texas State Science And Engineering Fair in Texas",
      sourceUrl: "https://texasdefined.com/images/events/texas-state-science-and-engineering-fair.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Texas Science & Engineering Fair official site", url: "https://txsef.tamu.edu/" },
      { label: "Texas Science & Engineering Fair regional qualification information", url: "https://txsef.tamu.edu/texas-regional-fairs/" },
    ],
    verifiedAt: "2026-09-05",
  },
];
