import type { EventSchemaEntity, MajorEventSchemaEnrichment } from "./major-event-schema-enrichment.server";

const organization = (name: string, url: string): EventSchemaEntity => ({ type: "Organization", name, url });

// First-party optional-schema research pass completed 2026-09-05. Properties are
// intentionally limited to values supported by current organizer or host sources.
export const majorEventSchemaEnrichmentBatch14: MajorEventSchemaEnrichment[] = [
  {
    slug: "hummerbird-celebration",
    image: {
      url: "https://texasdefined.com/images/events/hummerbird-celebration.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Hummerbird Celebration in Texas",
      sourceUrl: "https://texasdefined.com/images/events/hummerbird-celebration.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Rockport-Fulton Chamber of Commerce", "https://www.rockport-fulton.org/"),
    sources: [
      { label: "HummerBird Celebration official page", url: "https://www.rockport-fulton.org/hummerbird-celebration/" },
      { label: "2026 HummerBird Celebration chamber listing", url: "https://members.rockport-fulton.org/events/details/2026-hummerbird-celebration-64768" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "washington-county-fair",
    image: {
      url: "https://texasdefined.com/images/events/washington-county-fair.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Washington County Fair in Texas",
      sourceUrl: "https://texasdefined.com/images/events/washington-county-fair.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Washington County Fair Association", "https://www.washingtoncofair.com/"),
    sources: [
      { label: "Washington County Fair official schedule", url: "https://www.washingtoncofair.com/events" },
      { label: "Washington County Fair official rodeo schedule", url: "https://www.washingtoncofair.com/events/rodeo" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "kendall-county-fair-rodeo",
    image: {
      url: "https://texasdefined.com/images/events/kendall-county-fair-rodeo.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Kendall County Fair Rodeo in Texas",
      sourceUrl: "https://texasdefined.com/images/events/kendall-county-fair-rodeo.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Kendall County Fair Association, Inc.", "https://kcfa.org/"),
    sources: [
      { label: "Kendall County Fair Association official site", url: "https://kcfa.org/" },
      { label: "Kendall County Fair Association September 2026 calendar", url: "https://kcfa.org/events/month/2026-09/" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "galveston-island-shrimp-festival",
    image: {
      url: "https://texasdefined.com/images/events/galveston-island-shrimp-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Galveston Island Shrimp Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/galveston-island-shrimp-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Yaga’s Entertainment", "https://galvestonislandshrimpfestival.com/"),
    sources: [
      { label: "Galveston Island Shrimp Festival official schedule", url: "https://galvestonislandshrimpfestival.com/schedule/" },
      { label: "Galveston Island Shrimp Festival official FAQ", url: "https://galvestonislandshrimpfestival.com/faqs/" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "rockport-fulton-seafair",
    image: {
      url: "https://texasdefined.com/images/events/rockport-fulton-seafair.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Rockport Fulton Seafair in Texas",
      sourceUrl: "https://texasdefined.com/images/events/rockport-fulton-seafair.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Rockport-Fulton Chamber of Commerce", "https://www.rockport-fulton.org/"),
    sources: [
      { label: "2026 SeaFair chamber listing", url: "https://members.rockport-fulton.org/events/details/2026-seafair-64771" },
    ],
    verifiedAt: "2026-09-05",
  },
  {
    slug: "rockport-songwriter-festival",
    image: {
      url: "https://texasdefined.com/images/events/rockport-songwriter-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Rockport Songwriter Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/rockport-songwriter-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Rockport Songwriter Association", "https://rockportsongwriterassociation.com/"),
    sources: [
      { label: "2026 Rockport Songwriter Festival chamber listing", url: "https://members.rockport-fulton.org/events/details/5th-annual-rockport-songwriter-festival-64419" },
    ],
    verifiedAt: "2026-09-05",
  },
];
