import type { EventSchemaEntity, EventSchemaOffer, MajorEventSchemaEnrichment } from "./major-event-schema-enrichment.server";

const usdOffer = (name: string, price: number, url: string): EventSchemaOffer => ({
  name,
  price,
  priceCurrency: "USD",
  url,
});

const organization = (name: string, url: string): EventSchemaEntity => ({ type: "Organization", name, url });
const group = (name: string, url?: string): EventSchemaEntity => ({ type: "PerformingGroup", name, ...(url ? { url } : {}) });
const person = (name: string, url?: string): EventSchemaEntity => ({ type: "Person", name, ...(url ? { url } : {}) });

// Supplemental dedicated Event leaves, reviewed against current official event/organizer sources.
// Year-specific offers and performers are only carried when the dedicated leaf represents that same event year.
// Event imagery remains omitted unless Texas Defined can publish a representative image with clear reuse rights.
export const majorEventSchemaEnrichmentBatch3: MajorEventSchemaEnrichment[] = [
  {
    slug: "dobie-dichos",
    image: {
      url: "https://texasdefined.com/images/events/dobie-dichos.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Dobie Dichos in Texas",
      sourceUrl: "https://texasdefined.com/images/events/dobie-dichos.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Dobie Dichos, Inc.", "https://www.dobiedichos.com/"),
    offers: [
      usdOffer("Adult program + meal admission", 30, "https://www.dobiedichos.com/tickets-schedule"),
      usdOffer("Child 12 and under program + meal admission", 10, "https://www.dobiedichos.com/tickets-schedule"),
      usdOffer("Adult program-only advance admission", 20, "https://www.dobiedichos.com/tickets-schedule"),
      usdOffer("Child 12 and under program-only admission", 5, "https://www.dobiedichos.com/tickets-schedule"),
      usdOffer("Adult program-only gate admission", 25, "https://www.dobiedichos.com/tickets-schedule"),
    ],
    sources: [
      { label: "Dobie Dichos official 2026 event page", url: "https://www.dobiedichos.com/" },
      { label: "Dobie Dichos official 2026 tickets and schedule", url: "https://www.dobiedichos.com/tickets-schedule" },
    ],
    verifiedAt: "2026-09-01",
  },
  {
    slug: "dallas-holiday-parade",
    image: {
      url: "https://texasdefined.com/images/events/dallas-holiday-parade.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Dallas Holiday Parade in Texas",
      sourceUrl: "https://texasdefined.com/images/events/dallas-holiday-parade.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("HTEDance and Spirit Group", "https://dallasholidayparade.com/"),
    offers: [
      usdOffer("Public parade route admission", 0, "https://dallasholidayparade.com/things-to-know"),
    ],
    sources: [
      { label: "Dallas Holiday Parade official history and current operator", url: "https://dallasholidayparade.com/" },
      { label: "Dallas Holiday Parade official spectator FAQ", url: "https://dallasholidayparade.com/things-to-know" },
    ],
    verifiedAt: "2026-09-01",
  },
  {
    slug: "schulenburg-festival",
    image: {
      url: "https://texasdefined.com/images/events/schulenburg-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Schulenburg Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/schulenburg-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Schulenburg Festival Association, Inc.", "https://www.schulenburgfestival.org/"),
    sources: [
      { label: "Schulenburg Festival Association official site", url: "https://www.schulenburgfestival.org/" },
      { label: "Schulenburg Festival official schedule", url: "https://www.schulenburgfestival.org/schedule" },
    ],
    verifiedAt: "2026-09-01",
  },
  {
    slug: "westfest",
    image: {
      url: "https://texasdefined.com/images/events/westfest.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Westfest in Texas",
      sourceUrl: "https://texasdefined.com/images/events/westfest.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Westfest Inc.", "https://westfest.com/"),
    sources: [
      { label: "Westfest official event and nonprofit background", url: "https://westfest.com/about" },
      { label: "Westfest Inc. official contact page", url: "https://westfest.com/contact" },
    ],
    verifiedAt: "2026-09-01",
  },
  {
    slug: "luling-watermelon-thump",
    image: {
      url: "https://texasdefined.com/images/events/luling-watermelon-thump.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Luling Watermelon Thump in Texas",
      sourceUrl: "https://texasdefined.com/images/events/luling-watermelon-thump.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Luling Watermelon Thump Association", "https://www.watermelonthump.com/"),
    sources: [
      { label: "Luling Watermelon Thump official site", url: "https://www.watermelonthump.com/" },
      { label: "Luling Watermelon Thump Association official parade terms", url: "https://www.watermelonthump.com/parade-form" },
    ],
    verifiedAt: "2026-09-01",
  },
  {
    slug: "national-polka-festival",
    image: {
      url: "https://texasdefined.com/images/events/national-polka-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing National Polka Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/national-polka-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("National Polka Festival", "https://www.nationalpolkafestival.com/"),
    sources: [
      { label: "National Polka Festival official site", url: "https://www.nationalpolkafestival.com/" },
      { label: "National Polka Festival official ticket information", url: "https://www.nationalpolkafestival.com/purchasetickets" },
    ],
    verifiedAt: "2026-09-01",
  },
  {
    slug: "gillespie-county-fair",
    image: {
      url: "https://texasdefined.com/images/events/gillespie-county-fair.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Gillespie County Fair in Texas",
      sourceUrl: "https://texasdefined.com/images/events/gillespie-county-fair.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Gillespie County Fair & Festivals Association, Inc.", "https://gillespiefair.com/"),
    performers: [
      group("Conjunto Cats"),
      group("Pepe Tovar Y Los Chacales"),
      person("Rick Trevino"),
      group("Bellamy Brothers"),
      person("Tristan Roberson"),
      person("Tracy Byrd"),
    ],
    sources: [
      { label: "Gillespie County Fair official 2026 fair page and entertainment schedule", url: "https://gillespiefair.com/gillespie-county-fair" },
      { label: "Gillespie County Fair & Festivals Association official organization page", url: "https://gillespiefair.com/" },
    ],
    verifiedAt: "2026-09-01",
  },
  {
    slug: "north-texas-fair-rodeo",
    image: {
      url: "https://texasdefined.com/images/events/north-texas-fair-rodeo.jpg",
      alt: "AI-generated photorealistic editorial depiction representing North Texas Fair Rodeo in Texas",
      sourceUrl: "https://texasdefined.com/images/events/north-texas-fair-rodeo.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("North Texas State Fair Association, Inc.", "https://ntfair.com/"),
    sources: [
      { label: "North Texas Fair & Rodeo official 2027 event page", url: "https://ntfair.com/" },
    ],
    verifiedAt: "2026-09-11",
  },
  {
    slug: "austin-chronicle-hot-sauce-festival",
    image: {
      url: "https://texasdefined.com/images/events/austin-chronicle-hot-sauce-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Austin Chronicle Hot Sauce Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/austin-chronicle-hot-sauce-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("The Austin Chronicle", "https://www.austinchronicle.com/"),
    offers: [
      usdOffer("Presale admission", 20, "https://www.austinchronicle.com/hot-sauce/"),
      usdOffer("Door admission", 25, "https://www.austinchronicle.com/hot-sauce/"),
      usdOffer("Child age 6 and under admission", 0, "https://www.austinchronicle.com/hot-sauce/"),
    ],
    performers: [
      person("Lauren Lakis"),
      group("Latin Dukes"),
      group("Libby and the Loveless"),
      person("DJ Mahealani"),
    ],
    sources: [
      { label: "Austin Chronicle Hot Sauce Festival official 2026 event page", url: "https://www.austinchronicle.com/hot-sauce/" },
      { label: "Austin Chronicle official 2026 festival music lineup", url: "https://www.austinchronicle.com/music/lauren-lakis-latin-dukes-libby-and-the-loveless-and-dj-mahealani-bring-sonic-heat-to-hot-sauce-festival/" },
    ],
    verifiedAt: "2026-09-01",
  },
];
