import type { EventSchemaEntity, EventSchemaOffer, MajorEventSchemaEnrichment } from "./major-event-schema-enrichment.server";

const usdOffer = (name: string, price: number, url: string): EventSchemaOffer => ({
  name,
  price,
  priceCurrency: "USD",
  url,
});

const organization = (name: string, url: string): EventSchemaEntity => ({ type: "Organization", name, url });

// Supplemental dedicated Event leaves, official-source research wave 4.
// Only values supported by the current authority sources are emitted; unclear organizers,
// changing ticket tiers, future lineups, and rights-unclear imagery stay omitted.
export const majorEventSchemaEnrichmentBatch6: MajorEventSchemaEnrichment[] = [
  {
    slug: "fredericksburg-oktoberfest",
    image: {
      url: "https://texasdefined.com/images/events/fredericksburg-oktoberfest.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Fredericksburg Oktoberfest in Texas",
      sourceUrl: "https://texasdefined.com/images/events/fredericksburg-oktoberfest.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Pedernales Creative Arts Alliance", "https://www.oktoberfestinfbg.com/"),
    sources: [
      { label: "Fredericksburg Oktoberfest official site", url: "https://www.oktoberfestinfbg.com/" },
      { label: "Fredericksburg Oktoberfest official festival details", url: "https://www.oktoberfestinfbg.com/fest-details" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "texas-book-festival",
    image: {
      url: "https://texasdefined.com/images/events/texas-book-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Texas Book Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/texas-book-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Texas Book Festival", "https://texasbookfestival.org/"),
    offers: [usdOffer("Festival admission", 0, "https://texasbookfestival.org/festival/")],
    sources: [
      { label: "Texas Book Festival official 2026 festival page", url: "https://texasbookfestival.org/festival/" },
      { label: "Texas Book Festival official 2026 dates announcement", url: "https://texasbookfestival.org/news/2025/12/announcing-the-2026-festival-dates/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "houston-art-car-parade",
    image: {
      url: "https://texasdefined.com/images/events/houston-art-car-parade.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Houston Art Car Parade in Texas",
      sourceUrl: "https://texasdefined.com/images/events/houston-art-car-parade.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("The Orange Show Center for Visionary Art", "https://orangeshow.org/"),
    offers: [usdOffer("Parade admission", 0, "https://www.thehoustonartcarparade.com/")],
    sources: [
      { label: "Houston Art Car Parade official site", url: "https://www.thehoustonartcarparade.com/" },
      { label: "Houston Art Car Parade official history", url: "https://www.thehoustonartcarparade.com/history-of-the-houston-art-car-para" },
      { label: "Houston Art Car Parade official FAQ", url: "https://www.thehoustonartcarparade.com/faq" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "mardi-gras-galveston",
    image: {
      url: "https://texasdefined.com/images/events/mardi-gras-galveston.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Mardi Gras Galveston in Texas",
      sourceUrl: "https://texasdefined.com/images/events/mardi-gras-galveston.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Mardi Gras! Galveston official site", url: "https://www.mardigrasgalveston.com/" },
      { label: "Mardi Gras! Galveston official 2027 parade schedule", url: "https://www.mardigrasgalveston.com/parade-schedule/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "texas-state-forest-festival",
    image: {
      url: "https://texasdefined.com/images/events/texas-state-forest-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Texas State Forest Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/texas-state-forest-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Texas State Forest Festival official site", url: "https://www.texasstateforestfestival.com/" },
      { label: "Texas State Forest Festival official FAQ", url: "https://www.texasstateforestfestival.com/faq" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "bayou-city-art-festival-memorial-park",
    image: {
      url: "https://texasdefined.com/images/events/bayou-city-art-festival-memorial-park.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Bayou City Art Festival Memorial Park in Texas",
      sourceUrl: "https://texasdefined.com/images/events/bayou-city-art-festival-memorial-park.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Art Colony Association, Inc.", "https://www.bayoucityartfestival.com/"),
    sources: [
      { label: "Bayou City Art Festival official site", url: "https://www.bayoucityartfestival.com/" },
      { label: "Bayou City Art Festival official festival information", url: "https://www.bayoucityartfestival.com/festival-info" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "western-heritage-classic",
    image: {
      url: "https://texasdefined.com/images/events/western-heritage-classic.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Western Heritage Classic in Texas",
      sourceUrl: "https://texasdefined.com/images/events/western-heritage-classic.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Western Heritage Classic", "https://www.westernheritageclassic.com/"),
    sources: [
      { label: "Western Heritage Classic official site", url: "https://www.westernheritageclassic.com/" },
      { label: "Western Heritage Classic official 2027 schedule", url: "https://www.westernheritageclassic.com/p/events/schedule" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "bob-wills-day",
    image: {
      url: "https://texasdefined.com/images/events/bob-wills-day.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Bob Wills Day in Texas",
      sourceUrl: "https://texasdefined.com/images/events/bob-wills-day.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Bob Wills Foundation", "https://bobwillsday.com/"),
    sources: [
      { label: "Bob Wills Day official 2027 save-the-date", url: "https://bobwillsday.com/home-2/" },
      { label: "Bob Wills Foundation official annual-tradition page", url: "https://bobwillsday.com/bwd-2/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "lone-star-cowboy-poetry-gathering-alpine",
    image: {
      url: "https://texasdefined.com/images/events/lone-star-cowboy-poetry-gathering-alpine.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Lone Star Cowboy Poetry Gathering Alpine in Texas",
      sourceUrl: "https://texasdefined.com/images/events/lone-star-cowboy-poetry-gathering-alpine.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Lone Star Cowboy Poetry Gathering", "https://lonestarcowboypoetry.com/"),
    sources: [
      { label: "Lone Star Cowboy Poetry Gathering official Alpine 2027 page", url: "https://lonestarcowboypoetry.com/2027/alpine/index.html" },
      { label: "Lone Star Cowboy Poetry Gathering official welcome page", url: "https://lonestarcowboypoetry.com/welcome/index.html" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "lone-star-cowboy-poetry-gathering-bastrop",
    image: {
      url: "https://texasdefined.com/images/events/lone-star-cowboy-poetry-gathering-bastrop.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Lone Star Cowboy Poetry Gathering Bastrop in Texas",
      sourceUrl: "https://texasdefined.com/images/events/lone-star-cowboy-poetry-gathering-bastrop.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Lone Star Cowboy Poetry Gathering", "https://lonestarcowboypoetry.com/"),
    sources: [
      { label: "Lone Star Cowboy Poetry Gathering official Bastrop 2027 page", url: "https://lonestarcowboypoetry.com/2027/bastrop/index.html" },
      { label: "Lone Star Cowboy Poetry Gathering official welcome page", url: "https://lonestarcowboypoetry.com/welcome/index.html" },
    ],
    verifiedAt: "2026-09-02",
  },
];
