import type { EventSchemaEntity, EventSchemaOffer, MajorEventSchemaEnrichment } from "./major-event-schema-enrichment.server";

const usdOffer = (name: string, price: number, url: string): EventSchemaOffer => ({
  name,
  price,
  priceCurrency: "USD",
  url,
});

const organization = (name: string, url: string): EventSchemaEntity => ({ type: "Organization", name, url });

// Supplemental dedicated Event leaves, official-source research wave 5.
// Multi-producer events remain source-reviewed without an organizer assertion when the
// official material does not support one unambiguous responsible organization.
export const majorEventSchemaEnrichmentBatch7: MajorEventSchemaEnrichment[] = [
  {
    slug: "texas-jazz-festival",
    image: {
      url: "https://texasdefined.com/images/events/texas-jazz-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Texas Jazz Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/texas-jazz-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Texas Jazz Festival Society", "https://www.texasjazz-fest.org/"),
    offers: [usdOffer("Festival admission", 0, "https://www.texasjazz-fest.org/")],
    sources: [
      { label: "Texas Jazz Festival Society official 2026 festival page", url: "https://www.texasjazz-fest.org/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "red-steagall-cowboy-gathering",
    image: {
      url: "https://texasdefined.com/images/events/red-steagall-cowboy-gathering.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Red Steagall Cowboy Gathering in Texas",
      sourceUrl: "https://texasdefined.com/images/events/red-steagall-cowboy-gathering.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Red Steagall Cowboy Gathering official site", url: "https://www.redsteagallcowboygathering.com/" },
      { label: "Red Steagall Cowboy Gathering official history and current management", url: "https://www.redsteagallcowboygathering.com/our-story/" },
      { label: "Red Steagall Cowboy Gathering official schedule and tickets", url: "https://www.redsteagallcowboygathering.com/schedule-tickets/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "texas-rice-festival",
    image: {
      url: "https://texasdefined.com/images/events/texas-rice-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Texas Rice Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/texas-rice-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Texas Rice Festival official site", url: "https://texasricefestival.com/" },
      { label: "Texas Rice Festival official tickets and fees", url: "https://texasricefestival.com/festivalpark-info/ticketsfees/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "international-quilt-festival-houston",
    image: {
      url: "https://texasdefined.com/images/events/international-quilt-festival-houston.jpg",
      alt: "AI-generated photorealistic editorial depiction representing International Quilt Festival Houston in Texas",
      sourceUrl: "https://texasdefined.com/images/events/international-quilt-festival-houston.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Quilts, Inc.", "https://www.quilts.com/"),
    sources: [
      { label: "Quilts, Inc. official company and International Quilt Festival background", url: "https://www.quilts.com/about-us/" },
      { label: "International Quilt Festival/Houston official information", url: "https://www.quilts.com/quilt-festival/quilt-festival-houston/" },
      { label: "Quilts, Inc. official 2026 Houston Festival date announcement", url: "https://www.quilts.com/major-changes-announced-festival-dates-changed-market-discontinued/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "original-greek-festival-houston",
    image: {
      url: "https://texasdefined.com/images/events/original-greek-festival-houston.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Original Greek Festival Houston in Texas",
      sourceUrl: "https://texasdefined.com/images/events/original-greek-festival-houston.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Annunciation Greek Orthodox Cathedral", "https://www.agoc.org/"),
    sources: [
      { label: "The Original Greek Festival official site", url: "https://www.greekfestival.org/" },
      { label: "The Original Greek Festival official attending information", url: "https://www.greekfestival.org/pages/attending" },
      { label: "The Original Greek Festival official FAQ", url: "https://www.greekfestival.org/pages/faqs" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "san-antonio-muertos-fest",
    image: {
      url: "https://texasdefined.com/images/events/san-antonio-muertos-fest.jpg",
      alt: "AI-generated photorealistic editorial depiction representing San Antonio Muertos Fest in Texas",
      sourceUrl: "https://texasdefined.com/images/events/san-antonio-muertos-fest.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Muertos Fest official site", url: "https://muertosfest.com/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "austin-food-wine-festival",
    image: {
      url: "https://texasdefined.com/images/events/austin-food-wine-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Austin Food Wine Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/austin-food-wine-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Austin Food & Wine Festival official site", url: "https://www.austinfoodandwinefestival.com/" },
      { label: "Austin Food & Wine Festival official tickets and day formats", url: "https://www.austinfoodandwinefestival.com/tickets" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "gruene-music-wine-festival",
    image: {
      url: "https://texasdefined.com/images/events/gruene-music-wine-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Gruene Music Wine Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/gruene-music-wine-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Gruene Music & Wine Festival official site", url: "https://gruenemusicandwinefest.org/" },
      { label: "Gruene Music & Wine Festival official tickets and daily program", url: "https://gruenemusicandwinefest.org/tickets/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "texas-clay-festival",
    image: {
      url: "https://texasdefined.com/images/events/texas-clay-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Texas Clay Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/texas-clay-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    sources: [
      { label: "Texas Clay Festival official site", url: "https://texasclayfestival.com/" },
      { label: "Texas Clay Festival official about and schedule page", url: "https://texasclayfestival.com/about/" },
    ],
    verifiedAt: "2026-09-02",
  },
  {
    slug: "texas-craft-brewers-festival",
    image: {
      url: "https://texasdefined.com/images/events/texas-craft-brewers-festival.jpg",
      alt: "AI-generated photorealistic editorial depiction representing Texas Craft Brewers Festival in Texas",
      sourceUrl: "https://texasdefined.com/images/events/texas-craft-brewers-festival.jpg",
      sourceType: "ai-generated",
      rightsNote: "Generated by TexasDefined with Cloudflare Workers AI (FLUX.1 schnell) for TexasDefined-owned editorial use; no third-party source image was used.",
      exactLocation: false,
      approvedForCommercialUse: true,
      aiGenerated: true,
    },
    organizer: organization("Texas Craft Brewers Guild", "https://texascraftbrewersguild.org/"),
    sources: [
      { label: "Texas Craft Brewers Festival official site — organized by Texas Craft Brewers Guild", url: "https://texascraftbrewersfestival.org/" },
      { label: "Texas Craft Brewers Festival official visitor information", url: "https://texascraftbrewersfestival.org/info/" },
    ],
    verifiedAt: "2026-09-02",
  },
];
