import type { SportsVenuePhoto } from './sports-venue-images';

/** Generated by scripts/data/sync-sports-venue-hero-assets-wave7.mjs. Do not hand-edit. */
export const sportsVenuePhotoAdditionsWave7: Record<string, SportsVenuePhoto> = {};

export function getSportsVenuePhotoAdditionWave7(slug: string) {
  return sportsVenuePhotoAdditionsWave7[slug];
}
