import type { ImageRef } from "./types";

/** Generated by scripts/data/sync-state-park-hero-assets.mjs. Do not hand-edit. */
export const stateParkHeroMap: Record<string, ImageRef> = {
  "abilene-state-park": { src: "/images/state-parks/abilene-state-park.jpg", alt: "Abilene State Park in Texas", width: 1600, height: 900, credit: "Larry D. Moore · CC BY 4.0 · Wikimedia Commons" },
};
