import type { ImageRef } from "./types";

/**
 * Generated by scripts/data/sync-state-park-hero-assets.mjs.
 * Do not hand-edit. Existing destination-specific photos remain preferred;
 * these entries fill only missing or duplicate State Park heroes.
 */
export const stateParkHeroMap: Record<string, ImageRef> = {};
